### ISSUE TITLE
Unable to connect using ethminer 0.9.41 Genoil fork 1.0.7

### ISSUE THREAD

**Issue by DaveBarrron** [sammy007/open-ethereum-pool#1]
https://github.com/Genoil/cpp-ethereum/

**Comment by davembg** [comment]
@DaveBarrron what is the error?

**Comment by DaveBarrron** [comment]
I assume it is being used on PooLTo.Be Ethereum Pool and  DonkeyPool  I  get the same error on both.

Unable to connect:


using: ethminer  -U -F http://donkeypool.com/my account/rig1/20


log:

C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer  -U -F http://donkeypool.
com/myaccount/rig1/20
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_


Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d


Using grid size 8192, block size 128


miner  23:38:08|main  Getting work package...
  X  23:38:08|main  Failed to submit hashrate.
  X  23:38:08|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32603 : INTERNAL_ERROR: : <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.9.3 (Ubuntu)</center>
</body>
</html>




JSON-RPC problem. Probably couldn't connect. Retrying in 1...
miner  23:38:10|main  Getting work package...
  X  23:38:10|main  Failed to submit hashrate.
  X  23:38:10|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32603 : INTERNAL_ERROR: : <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.9.3 (Ubuntu)</center>
</body>
</html>




JSON-RPC problem. Probably couldn't connect. Retrying in 1...
miner  23:38:12|main  Getting work package...
  X  23:38:12|main  Failed to submit hashrate.
  X  23:38:12|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32603 : INTERNAL_ERROR: : <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.9.3 (Ubuntu)</center>
</body>
</html>




JSON-RPC problem. Probably couldn't connect. Retrying in 1...
miner  23:38:15|main  Getting work package...
  X  23:38:15|main  Failed to submit hashrate.
  X  23:38:15|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32603 : INTERNAL_ERROR: : <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.9.3 (Ubuntu)</center>
</body>
</html>




JSON-RPC problem. Probably couldn't connect. Retrying in 1...
miner  23:38:17|main  Getting work package...
  X  23:38:17|main  Failed to submit hashrate.
  X  23:38:17|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32603 : INTERNAL_ERROR: : <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.9.3 (Ubuntu)</center>
</body>
</html>

-----Original Message-----

**Comment by davembg** [comment]
that error isn't even for this pool.
Does your miner work for any other pools?

You'll also want to read the bitcointalk forum for Genoil's miner and maybe try 1.0.6.
https://github.com/Genoil/cpp-ethereum/blob/master/releases/ethminer-0.9.41-genoil-1.0.6.zip
If you're not using stratum, 1.0.6 will be fine.

**Comment by sammy007** [comment]
RIG-ID must be alphanumeric, spaces are not allowed there.

**Comment by sammy007** [comment]
Well, I see you are using wrong connection string. On pools running this software (like eth.poolto.be) you must use:

<code>ethminer -F http://eth.poolto.be:8546/0xb85150eb365e7df0941f0cf08235f987ba91506a/myfarm</code>
