### ISSUE TITLE
Issue to connect GPU miner

### ISSUE THREAD

**Issue by awsashish** [sammy007/open-ethereum-pool#100]
Hi There,

I am having an issue, I am able to connect my CPU miner on my stratum port, but when I am trying to connect GPU miner it return the rpc error and not able to connect.

Please help me on this issue.

Thanks,
Ashish

**Comment by mikeyb** [comment]
What error?  We can't help without details.

**Comment by vjune** [comment]
Anyone who has already built and run it completely? I am looking for one who can give me how to build and manage it. Please email james@tachsol-intl.com

**Comment by awsashish** [comment]
It seems, our redis db is not updating so we can not view the connected miners and stats on frontend. 

Please let me know if there are any more settings for redis which are not included on how to doc.

**Comment by mikeyb** [comment]
Is redis running?

**Comment by awsashish** [comment]
Yes Redis server is working,

`+1483790354.001282 [0 198.211.100.125:49464] "MULTI"
+1483790354.001315 [0 198.211.100.125:49464] "ZREMRANGEBYSCORE" "eth:hashrate" "-inf" "(1483788554"
+1483790354.001328 [0 198.211.100.125:49464] "ZRANGE" "eth:hashrate" "0" "-1" "WITHSCORES"
+1483790354.001335 [0 198.211.100.125:49464] "HGETALL" "eth:stats"
+1483790354.001339 [0 198.211.100.125:49464] "ZREVRANGE" "eth:blocks:candidates" "0" "-1" "WITHSCORES"
+1483790354.001346 [0 198.211.100.125:49464] "ZREVRANGE" "eth:blocks:immature" "0" "-1" "WITHSCORES"
+1483790354.001352 [0 198.211.100.125:49464] "ZREVRANGE" "eth:blocks:matured" "0" "49" "WITHSCORES"
+1483790354.001359 [0 198.211.100.125:49464] "ZCARD" "eth:blocks:candidates"
+1483790354.001363 [0 198.211.100.125:49464] "ZCARD" "eth:blocks:immature"
+1483790354.001367 [0 198.211.100.125:49464] "ZCARD" "eth:blocks:matured"
+1483790354.001371 [0 198.211.100.125:49464] "ZCARD" "eth:payments:all"
+1483790354.001375 [0 198.211.100.125:49464] "ZREVRANGE" "eth:payments:all" "0" "29" "WITHSCORES"
+1483790354.001383 [0 198.211.100.125:49464] "EXEC"
+1483790354.001523 [0 198.211.100.125:49464] "UNWATCH"
+1483790354.001614 [0 198.211.100.125:49464] "MULTI"
+1483790354.001621 [0 198.211.100.125:49464] "ZREVRANGE" "eth:blocks:immature" "0" "-1" "WITHSCORES"
+1483790354.001629 [0 198.211.100.125:49464] "ZREVRANGE" "eth:blocks:matured" "0" "255" "WITHSCORES"
+1483790354.001636 [0 198.211.100.125:49464] "EXEC"
+1483790354.001712 [0 198.211.100.125:49464] "UNWATCH"
+1483790354.070678 [0 198.211.100.125:49464] "MULTI"
+1483790354.070701 [0 198.211.100.125:49464] "HSET" "eth:nodes" "main:name" "main"
+1483790354.070713 [0 198.211.100.125:49464] "HSET" "eth:nodes" "main:height" "2951935"
+1483790354.070719 [0 198.211.100.125:49464] "HSET" "eth:nodes" "main:difficulty" "93793279046194"
+1483790354.070727 [0 198.211.100.125:49464] "HSET" "eth:nodes" "main:lastBeat" "1483790354"
+1483790354.070734 [0 198.211.100.125:49464] "EXEC"
+1483790354.070854 [0 198.211.100.125:49464] "UNWATCH"
+1483790354.347184 [0 198.211.100.125:49464] "HGETALL" "eth:nodes"
+1483790357.071325 [0 198.211.100.125:49464] "MULTI"
+1483790357.071347 [0 198.211.100.125:49464] "HSET" "eth:nodes" "main:name" "main"
+1483790357.071359 [0 198.211.100.125:49464] "HSET" "eth:nodes" "main:height" "2951935"
+1483790357.071368 [0 198.211.100.125:49464] "HSET" "eth:nodes" "main:difficulty" "93793279046194"
+1483790357.071382 [0 198.211.100.125:49464] "HSET" "eth:nodes" "main:lastBeat" "1483790357"
+1483790357.071395 [0 198.211.100.125:49464] "EXEC"
+1483790357.071545 [0 198.211.100.125:49464] "UNWATCH"
+1483790359.002748 [0 198.211.100.125:49464] "MULTI"
+1483790359.002778 [0 198.211.100.125:49464] "ZREMRANGEBYSCORE" "eth:hashrate" "-inf" "(1483788559"
+1483790359.002791 [0 198.211.100.125:49464] "ZRANGE" "eth:hashrate" "0" "-1" "WITHSCORES"
+1483790359.002799 [0 198.211.100.125:49464] "HGETALL" "eth:stats"
+1483790359.002803 [0 198.211.100.125:49464] "ZREVRANGE" "eth:blocks:candidates" "0" "-1" "WITHSCORES"
+1483790359.002809 [0 198.211.100.125:49464] "ZREVRANGE" "eth:blocks:immature" "0" "-1" "WITHSCORES"
+1483790359.002816 [0 198.211.100.125:49464] "ZREVRANGE" "eth:blocks:matured" "0" "49" "WITHSCORES"
+1483790359.002822 [0 198.211.100.125:49464] "ZCARD" "eth:blocks:candidates"
+1483790359.002827 [0 198.211.100.125:49464] "ZCARD" "eth:blocks:immature"
+1483790359.002831 [0 198.211.100.125:49464] "ZCARD" "eth:blocks:matured"
+1483790359.002835 [0 198.211.100.125:49464] "ZCARD" "eth:payments:all"
+1483790359.002840 [0 198.211.100.125:49464] "ZREVRANGE" "eth:payments:all" "0" "29" "WITHSCORES"
+1483790359.002847 [0 198.211.100.125:49464] "EXEC"
+1483790359.003017 [0 198.211.100.125:49464] "UNWATCH"
+1483790359.003165 [0 198.211.100.125:49464] "MULTI"
+1483790359.003174 [0 198.211.100.125:49464] "ZREVRANGE" "eth:blocks:immature" "0" "-1" "WITHSCORES"
+1483790359.003182 [0 198.211.100.125:49464] "ZREVRANGE" "eth:blocks:matured" "0" "255" "WITHSCORES"
+1483790359.003188 [0 198.211.100.125:49464] "EXEC"
+1483790359.003290 [0 198.211.100.125:49464] "UNWATCH"`

**Comment by awsashish** [comment]
1. **What GPU miner** (EthOS) or ethe-proxy
2. ** To where it connected ** (stratum or http) (stratum)
3. ** What an error ** ( What an error (SON-RPC problem. Probably couldn't connect. Retrying in 2... 
  m  05:05:46|ethminer  Getting work package...
  ✘  05:05:46|ethminer  Failed to submit hashrate.
  ✘  05:05:46|ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8080/30f907)

**Comment by sammy007** [comment]
Wait for 'community", I have no ethos, looks like it's commercial and you can ask their support.

**Comment by awsashish** [comment]
So what are you using for mining?

**Comment by awsashish** [comment]
Dear @sammy007 ,

I need to talk to you, please let me know how can I connect with you?

ashish.sharma2911 is my skype id.

**Comment by sammy007** [comment]
I don't talk via skype and also not going to guide anyone. if you are not capable to install everything using current manuals, you don't have to even try to run it.

Ask people in gitter. Closing.
