### ISSUE TITLE
Payouts run infinitely

### ISSUE THREAD

**Issue by zielas69** [sammy007/open-ethereum-pool#103]
#### System information
Geth version: `geth version` or commit hash if `develop`
pool@etc:~$ geth version
Geth
Version: 3.2.2-unstable-c653455c
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6
OS: linux
GOPATH=
GOROOT=/usr/lib/go
pool@etc:~$

Redis version: `redis-server --version`
pool@etc:~$ redis-server --version
Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9
pool@etc:~$

OS & Version: Linux/OSX
Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-042stab120.11.vvs.ovz6836 x86_64)

Since yesterday, everytime i run payouts module i'm waiting infinitely for tx confirmation. Today it ran for 9 hours for single payment.
I have to manually chek txpool.status.pending when it becomes 0, kill payouts module and run it again. (This way i can payout workers).

**Comment by sammy007** [comment]
Payouts run continuously, next payout requires previous tx to confirm. By design. If ETH does not confirm txes this is not a pool problem.

**Comment by mikeyb** [comment]
ETC just hardforked, make sure you are on the correct chain as well

https://www.reddit.com/r/EthereumClassic/comments/5kgcem/update_etc_geth_323_aka_diehard_hardfork/
