### ISSUE TITLE
Error when payment

### ISSUE THREAD

**Issue by phucvinh52** [sammy007/open-ethereum-pool#104]
Hello sammy007,
I have a problem with my system payment. 
>Failed to send payment to 0x020a2c148315aa7bb8c0606ba29c859445e0fbea, 2320165756 Shannon: invalid argument 0: hex number has leading zero digits after 0x. Check outgoing tx for 0x020a2c148315aa7bb8c0606ba29c859445e0fbea in block explorer and docs/PAYOUTS.md

Please tell me which resolve that poblem thank.

**Comment by mikeyb** [comment]
geth or parity?

**Comment by phucvinh52** [comment]
I'm using geth v1.5.7.

**Comment by jyap808** [comment]
@phucvinh52 Can you try building against Geth 1.5.4 as a dependency? Requires some tweaking.

Here are the build steps.

Build normally.

```
cd open-ethereum-pool
make
```

Clean the build environment.

```
make clean
```

Check out version 1.5.4 of Geth

```
cd build/_workspace/src/github.com/ethereum/go-ethereum/
git checkout b70acf3c5bd335d8dedc2a5aa6eff05c4c32105e
cd ../../../../../../
```

Build against version 1.5.4 of Geth

```
make
```

New version is now in build/bin

Test out payments.

**Comment by sammy007** [comment]
`Shannon: invalid argument 0: hex number has leading zero digits after 0x` either figure out why the fuck geth is bitching about that or just use parity. I highly suggest using parity instead of geth.

**Comment by rapsta** [comment]
change common.BigToHash(big.Int).Hex() (3 times) with hexutil.EncodeBig(big.Int) in payer.go, to process payouts with latest Geth Node.

**Comment by sammy007** [comment]
Nice, so ethereum fucked up compatibility and no one reported a bug. This is why I hate to write open source in crypto space, no one interested in reporting bugs because you have benefit to not do that.

**Comment by sammy007** [comment]
"Fixed" in `develop` branch.

https://github.com/sammy007/open-ethereum-pool/commit/39264b268a8db568634185828bb25466b957e36f

Somebody please test it with latest geth and parity.

**Comment by wariner84** [comment]
tested with geth, all ok

**Comment by jyap808** [comment]
tested and works. thanks.

**Comment by phucvinh52** [comment]
im using geth 1.5.4 for payment and it work again. Thanks

**Comment by sammy007** [comment]
Anyone with parity?

**Comment by zet-tech** [comment]
Work with Parity 1.4.10

**Comment by sammy007** [comment]
Okay, pushed to `master`.
