### ISSUE TITLE
question

### ISSUE THREAD

**Issue by hans3103** [sammy007/open-ethereum-pool#105]
hello,

I was following te readme file and run in to somthing that i don't understand. I am trying to use this to build a pool for my own learning and knowledge.
 I installed everything on a VPS and i got geth up and running but the part below i odnt understand. I cannot fing the nginx configfile.....

Serving API using nginx

Create an upstream for API:

upstream api {
    server 127.0.0.1:8080;
}

and add this setting after location /:

location /api {
    proxy_pass http://api;
}

I dont know if this is the right place to ask things like this?

many thanks,

Hans

**Comment by sammy007** [comment]
Use gitter for questions.
