### ISSUE TITLE
to sammy

### ISSUE THREAD

**Issue by slavserver** [sammy007/open-ethereum-pool#108]
приветсвую, нужна помощь -) во вкладке майнерс, решил добавить колонку о найденом блоке, колонка добавилась, а вот отображение блока нет,  я уже что только не впихивал в код (это как пример format-number stats.block.variance) не помогает.. хелпнни пожалуйста

**Comment by sammy007** [comment]
Я уже не помню как что, смотри как другие страницы сделаны.
