### ISSUE TITLE
Pool is not show worker name when using eth-proxy

### ISSUE THREAD

**Issue by phucvinh52** [sammy007/open-ethereum-pool#114]
Hi sammy007,
I have a little customer running with eth-proxy, craymore is set -eworker <name> and run via the-proxy, the problem is pool is not show worker name. Do you have any way for workaround or fix it.
Thanks. Love sammy007 :)

**Comment by sammy007** [comment]
Workaround is correct miner configuration.

**Comment by sammy007** [comment]
What is the-proxy? If it's dwarf proxy I have no idea. If it's ether-proxy consider dirrect connection instead otherwise there will be just 1 worker name specified in http connection string to pool.

**Comment by phucvinh52** [comment]
I have used eth-proxy dwarf. I can get name worker at  https://ethermine.org. Thanks for your answer.

**Comment by sammy007** [comment]
Sorry, I don't accept paypal.

You don't need eth-proxy if you are using claymore, IIRC eth-proxy only works with ethminer (via http). Just connect to pool directly using claymore in `sm 0` (default) mode.

**Comment by phucvinh52** [comment]
Thank you, I'll try to describe it to show it on pool.

**Comment by sammy007** [comment]
Double check config of eth-proxy there is an option to forward worker name IIRC.
