### ISSUE TITLE
make not working 

### ISSUE THREAD

**Issue by bapparabi** [sammy007/open-ethereum-pool#115]
pooladmin@xmr:~/open-ethereum-pool$ make
build/env.sh go get -v ./...
build/env.sh: 32: exec: go: not found
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 127

can you tell me why its not working ..

**Comment by phucvinh52** [comment]
You have to install golang to build source.

**Comment by sammy007** [comment]
apt-get install golang.
