### ISSUE TITLE
Front end empty page

### ISSUE THREAD

**Issue by slabon** [sammy007/open-ethereum-pool#116]
Everything is up and running fine, I get miners connected and mining but I get an empty front end page with background and footer.
I've been looking at each installation step again and again, even re-done the install but don't find a solution...
Any idea what could be my problem? 

Thank you!

**Comment by mikeyb** [comment]
Do you see anything in the dev console of your browser?  Are there any errors on the webserver that is suppose to render the page?

**Comment by slabon** [comment]
No errors visible
redis-server is fine
geth is fine
open-ethereun-pool is fine 
miners get work and shares are accepted
and I've balance in account.
just get a front end empty page  with background and footer :(

**Comment by slabon** [comment]
maybe my nginx config is wrong...
could you share how to config the api upstream and location /
to double check if I did that right?

**Comment by slabon** [comment]
Ok sorry, so ember wasn't running...
now this is what the dev console says:
`ember.debug.js:6797DEBUG: -------------------------------
ember.debug.js:6797DEBUG: Ember      : 2.8.3+c4330341
ember.debug.js:6797DEBUG: Ember Data : 2.10.0
ember.debug.js:6797DEBUG: jQuery     : 3.1.1
ember.debug.js:6797DEBUG: -------------------------------
ember.debug.js:6797DEBUG: For more advanced debugging, install the Ember Inspector from https://chrome.google.com/webstore/detail/ember-inspector/bmdblncegkenkacieihfhpjfppoconhi
http://localhost:8080/api/stats Failed to load resource: net::ERR_CONNECTION_RESET
vendor.js:29713 undefined
defaultDispatch @ vendor.js:29713`

And I get a Stats API Temporarily Down msg on the page.

I guess my upstream api isn't properly configured...

Could tell me how to?

**Comment by mikeyb** [comment]
what does the nginx config look like currently?

**Comment by slabon** [comment]
I edited /etc/nginx/sites-available/default

upstream api {
    server 127.0.0.1:8080;
}

server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /home/pool/open-ethereum-pool/www/dist/;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        location /api {
        proxy_pass http://api;
        }
        }
}

**Comment by mikeyb** [comment]
if you run build.sh does that get things going?

**Comment by slabon** [comment]
I'll try now.
Is my nginx config correct?

**Comment by slabon** [comment]
still the same after build.sh 
does this affects build?
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

**Comment by slabon** [comment]
I was about to clean install but it seem the go-ethereum repository got edited a few hours ago...

package github.com/ethereum/go-ethereum/logger: cannot find package "github.com/ethereum/go-ethereum/logger" in any of:
        /usr/local/go/src/github.com/ethereum/go-ethereum/logger (from $GOROOT)
        /home/pool/open-ethereum-pool/build/_workspace/src/github.com/ethereum/go-ethereum/logger (from $GOPATH)
package github.com/ethereum/go-ethereum/logger/glog: cannot find package "github.com/ethereum/go-ethereum/logger/glog" in any of:
        /usr/local/go/src/github.com/ethereum/go-ethereum/logger/glog (from $GOROOT)
        /home/pool/open-ethereum-pool/build/_workspace/src/github.com/ethereum/go-ethereum/logger/glog (from $GOPATH)

**Comment by sammy007** [comment]
It was fixed but `ethash` package is broken again by go-ethereum team. Waiting for a fix.
