### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by slabon** [sammy007/open-ethereum-pool#117]
I was about to do a clean install but
it seem go-ethereum repository have change a few hours ago...

build/env.sh go get -v ./...
github.com/gorilla/mux (download)
github.com/gorilla/context (download)
github.com/ethereum/go-ethereum (download)
Fetching https://gopkg.in/redis.v3?go-get=1
Parsing meta tags from https://gopkg.in/redis.v3?go-get=1 (status code 200)
get "gopkg.in/redis.v3": found meta tag main.metaImport{Prefix:"gopkg.in/redis.v3", VCS:"git", RepoRoot:"https://gopkg.in/redis.v3"} at https://gopkg.in/redis.v3?go-get=1
gopkg.in/redis.v3 (download)
Fetching https://gopkg.in/bsm/ratelimit.v1?go-get=1
Parsing meta tags from https://gopkg.in/bsm/ratelimit.v1?go-get=1 (status code 200)
get "gopkg.in/bsm/ratelimit.v1": found meta tag main.metaImport{Prefix:"gopkg.in/bsm/ratelimit.v1", VCS:"git", RepoRoot:"https://gopkg.in/bsm/ratelimit.v1"} at https://gopkg.in/bsm/ratelimit.v1?go-get=1
gopkg.in/bsm/ratelimit.v1 (download)
github.com/ethereum/ethash (download)
package github.com/ethereum/go-ethereum/logger: cannot find package "github.com/ethereum/go-ethereum/logger" in any of:
        /usr/local/go/src/github.com/ethereum/go-ethereum/logger (from $GOROOT)
        /home/pool/open-ethereum-pool/build/_workspace/src/github.com/ethereum/go-ethereum/logger (from $GOPATH)
package github.com/ethereum/go-ethereum/logger/glog: cannot find package "github.com/ethereum/go-ethereum/logger/glog" in any of:
        /usr/local/go/src/github.com/ethereum/go-ethereum/logger/glog (from $GOROOT)
        /home/pool/open-ethereum-pool/build/_workspace/src/github.com/ethereum/go-ethereum/logger/glog (from $GOPATH)
github.com/go-stack/stack (download)
github.com/mattn/go-colorable (download)
github.com/rcrowley/go-metrics (download)
Fetching https://gopkg.in/karalabe/cookiejar.v2/collections/prque?go-get=1
Parsing meta tags from https://gopkg.in/karalabe/cookiejar.v2/collections/prque?go-get=1 (status code 200)
get "gopkg.in/karalabe/cookiejar.v2/collections/prque": found meta tag main.metaImport{Prefix:"gopkg.in/karalabe/cookiejar.v2", VCS:"git", RepoRoot:"https://gopkg.in/karalabe/cookiejar.v2"} at https://gopkg.in/karalabe/cookiejar.v2/collections/prque?go-get=1
get "gopkg.in/karalabe/cookiejar.v2/collections/prque": verifying non-authoritative meta tag
Fetching https://gopkg.in/karalabe/cookiejar.v2?go-get=1
Parsing meta tags from https://gopkg.in/karalabe/cookiejar.v2?go-get=1 (status code 200)
gopkg.in/karalabe/cookiejar.v2 (download)
github.com/yvasiyarov/gorelic (download)
github.com/yvasiyarov/go-metrics (download)
github.com/yvasiyarov/newrelic_platform_go (download)
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by sammy007** [comment]
Me too. Investigating.

**Comment by sammy007** [comment]
https://github.com/ethereum/ethash/issues/91

**Comment by bapparabi** [comment]
yes same iisue for me alos

**Comment by phucvinh52** [comment]
Seem "github.com/ethereum/go-ethereum/logger" is deleted.

**Comment by bapparabi** [comment]
so what is solution now

**Comment by sammy007** [comment]
Fork go-ethereum repo to your github account, revert breaking changes, replace all occurences of "import ethereum/go-ethereum/*" to your repo. Then make.

**Comment by bapparabi** [comment]
not gettign it ..can't it be done simply using some command

**Comment by sammy007** [comment]
It can be done simply by fixing broken `ethash` package. There is a Swiss company backed by several millions of dollars and full time developers to serve you, please ask them in this issue https://github.com/ethereum/ethash/issues/91

**Comment by slabon** [comment]
> There is a Swiss company backed by several millions of dollars and full time developers to serve you, please ask them in this issue ethereum/ethash#91
LoL
Ok forked and reverted... Thank you for pointing at that...
Where do the occurence appear in /open-ethereum-pool ?

**Comment by sammy007** [comment]
Search in all `go` files. Or clone `ethash` repo and delete all code using logger. You don't need togger there. Would be simple. Then replace ethash imports in `miner.go`.

**Comment by slabon** [comment]
Will try that... Thanx!

**Comment by sammy007** [comment]
https://github.com/ethereum/ethash/pull/92

So ethash fix was easy, it's better if you will replace ethash in `miner.go` to your own forked version with my fix.

**Comment by karalabe** [comment]
Sorry about this breakage, we're in the process of swapping loggers in go-ethereum and ethash depended on the old one. Will merge now.

**Comment by sammy007** [comment]
Fixed in ethash upstream.
