### ISSUE TITLE
Lack of "Network Hash Rate" in API provision? 

### ISSUE THREAD

**Issue by immartian** [sammy007/open-ethereum-pool#118]
We ran up several instances with the most recent versions of this fancy pool system. However, seems there's no entry for "Network Hash Rate" as shown on web UI. Is there a way to patch or customize that? 

A sample API JSON output: 

{
candidatesTotal: 25,
hashrate: 18649680147,
immatureTotal: 62,
maturedTotal: 41526,
minersTotal: 55,
nodes: [
{
difficulty: "523213232300",
height: "86284",
lastBeat: "1487939442",
name: "main"
}
],
now: 1487939443951,
stats: {
lastBlockFound: 1487939431,
roundShares: 148000000000
}
}

**Comment by sammy007** [comment]
In UI nethash = `diff / blockTime`. There is no nethash in API.

**Comment by immartian** [comment]
got it, appreciate!
