### ISSUE TITLE
Reward in unlocking is wrong

### ISSUE THREAD

**Issue by phucvinh52** [sammy007/open-ethereum-pool#119]
Hi sammy
I have a problem with we source.
This situation:
Pool have miner A and miner B, A and B found a block, that block in new block. After Miner C join to pool. In unlocking that block, C have reward from block that A and B found.

Do you any idea for that problem?

**Comment by sammy007** [comment]
It's impossible. Pool rotates shares on block found so I guess C had shares in previous round.

**Comment by phucvinh52** [comment]
Thanks @sammy007 i'll check and feed back to you if i still have that trouble
