### ISSUE TITLE
Error while refreshing pending block on main

### ISSUE THREAD

**Issue by mmitech** [sammy007/open-ethereum-pool#12]
I keep getting this error then the Unlocker and payments eventually stops working:

`Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Comment by sammy007** [comment]
Http RPC request to geth failed with timeout. Check geth.

`curl -X POST http://127.0.0.1:8545 -d '{"jsonrpc":"2.0","method":"eth_getWork","params":[],"id":0}'`

**Comment by mmitech** [comment]
yes, when I do it manually I get a successful result:
`
{"jsonrpc":"2.0","id":0,"result":["0x2023daa9f5f82d6b8cb7bc47558c0fe92280ac9e2f7a0a39dca601631ad0c8da","0x95d53b63d0b531598853dfe1f1271a355a583c442d509d228ff92a2b0a0d801a","0x0000000000080b4c58b6f0c0ddff75735b1b8881fd0e64994050ca6946adc8b0"]}`

but from watching the logs it fails few times which eventually effect unlocker and payouts

**Comment by sammy007** [comment]
This is issue with geth, connection to geth, etc. Pool just can't perform rpc request, happens sometimes. You need a n unlimited number of upstreams to configure in order to switch to a working one and backup when first node is ok.
