### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by sergnet** [sammy007/open-ethereum-pool#120]
System:
Ubuntu Server 16.04.02
Go 1.6.2

make
build/env.sh go get -v ./...
github.com/gorilla/mux (download)
github.com/gorilla/context (download)
github.com/ethereum/go-ethereum (download)
Fetching https://gopkg.in/redis.v3?go-get=1
Parsing meta tags from https://gopkg.in/redis.v3?go-get=1 (status code 200)
get "gopkg.in/redis.v3": found meta tag main.metaImport{Prefix:"gopkg.in/redis.v3", VCS:"git", RepoRoot:"https://gopkg.in/redis.v3"} at https://gopkg.in/redis.v3?go-get=1
gopkg.in/redis.v3 (download)
Fetching https://gopkg.in/bsm/ratelimit.v1?go-get=1
Parsing meta tags from https://gopkg.in/bsm/ratelimit.v1?go-get=1 (status code 200)
get "gopkg.in/bsm/ratelimit.v1": found meta tag main.metaImport{Prefix:"gopkg.in/bsm/ratelimit.v1", VCS:"git", RepoRoot:"https://gopkg.in/bsm/ratelimit.v1"} at https://gopkg.in/bsm/ratelimit.v1?go-get=1
gopkg.in/bsm/ratelimit.v1 (download)
github.com/ethereum/ethash (download)
github.com/yvasiyarov/gorelic (download)
github.com/yvasiyarov/go-metrics (download)
github.com/yvasiyarov/newrelic_platform_go (download)
github.com/gorilla/context
github.com/ethereum/go-ethereum/common/hexutil
gopkg.in/redis.v3/internal
gopkg.in/redis.v3/internal/consistenthash
gopkg.in/redis.v3/internal/hashtag
gopkg.in/bsm/ratelimit.v1
github.com/ethereum/go-ethereum/common/math
gopkg.in/redis.v3/internal/pool
github.com/ethereum/go-ethereum/common
github.com/gorilla/mux
github.com/ethereum/go-ethereum/crypto/secp256k1
gopkg.in/redis.v3
github.com/sammy007/open-ethereum-pool/util
github.com/ethereum/go-ethereum/crypto/sha3
# github.com/sammy007/open-ethereum-pool/util
util/util.go:12: undefined: common.BigPow
util/util.go:39: undefined: common.BytesToBig
util/util.go:51: undefined: common.Ether
github.com/ethereum/go-ethereum/rlp
github.com/ethereum/go-ethereum/vendor/github.com/go-stack/stack
github.com/ethereum/go-ethereum/log
github.com/ethereum/go-ethereum/params
github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics
github.com/ethereum/go-ethereum/vendor/gopkg.in/karalabe/cookiejar.v2/collections/prque
github.com/yvasiyarov/go-metrics
github.com/ethereum/go-ethereum/trie
github.com/yvasiyarov/newrelic_platform_go
github.com/yvasiyarov/gorelic
github.com/ethereum/go-ethereum/crypto
github.com/ethereum/go-ethereum/core/types
github.com/ethereum/go-ethereum/pow
github.com/ethereum/ethash
Makefile:10: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

Sorry for Russian

**Comment by sammy007** [comment]
А если сказать `go get github.com/ethereum/ethash` что будет? Убедись что можешь этот пакет поставить, потом делай уже make пула.

**Comment by sergnet** [comment]
Сейчас попробую

**Comment by sammy007** [comment]
Ставь сначала go-ethereum как [тут](https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu) сказано чтобы все ровно было с пулом, не хватает каких-то пакетов у тебя.

**Comment by sergnet** [comment]
Это я все сделал только у меня parity

**Comment by sergnet** [comment]
package github.com/ethereum/ethash: cannot download, $GOPATH not set. For more details see: go help gopath

**Comment by inspiredjava** [comment]
У меня то же самое. После выполнения `go get github.com/ethereum/ethash` 
 
`build/env.sh go get -v ./...
package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/cmd/evm
	imports github.com/ethereum/go-ethereum/cmd/evm/internal/compiler: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/cmd/geth
	imports github.com/ethereum/go-ethereum/cmd/internal/browser: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/cmd/geth
	imports github.com/ethereum/go-ethereum/internal/debug: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/cmd/swarm
	imports github.com/ethereum/go-ethereum/internal/debug: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/cmd/utils
	imports github.com/ethereum/go-ethereum/internal/debug: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/console
	imports github.com/ethereum/go-ethereum/internal/jsre: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/console
	imports github.com/ethereum/go-ethereum/internal/web3ext: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/contracts/release
	imports github.com/ethereum/go-ethereum/internal/ethapi: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/eth
	imports github.com/ethereum/go-ethereum/internal/ethapi: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/eth/gasprice
	imports github.com/ethereum/go-ethereum/internal/ethapi: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/internal/jsre
	imports github.com/ethereum/go-ethereum/internal/jsre/deps: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/les
	imports github.com/ethereum/go-ethereum/internal/ethapi: use of internal package not allowed

package github.com/sammy007/open-ethereum-pool/src/github.com/ethereum/go-ethereum/node
	imports github.com/ethereum/go-ethereum/internal/debug: use of internal package not allowed

Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1`

Это может быть прчиной? https://travis-ci.org/ethereum/ethash

**Comment by sammy007** [comment]
Разбираюсь.

**Comment by sammy007** [comment]
Pool depends on `go-ethereum` package and recently its compatibility broken, working on patch. No ETA.

**Comment by sammy007** [comment]
Patch is in `develop` branch, fixes compat. issues with `go-ethereum/common` package.

Changes were pretty simple and I didn't run full stack testing, please go with testnet and make sure that it works and report in this thread.

Time is limited and I am a volunteer here. I can't dedicate a lot of time to this project.

**Comment by sergnet** [comment]
There is a problem:
in go-ethereum-master - no logger
in go-ethereum-develop /common - no hexutil
I added hexutil of go-ethereum-master in go-ethereum-develop /common 

Built Successfully
In general problems with the repository go-ethereum

**Comment by sammy007** [comment]
I said you have to test `develop` branch and report if it works for you.

**Comment by wolfqs** [comment]
I tested develop branch, it works, thanks!

**Comment by sergnet** [comment]
Yes, develop branch, it works!!!
Thanks

**Comment by Mrcoinzer** [comment]
how fix
ether@ubuntu:~/open-ethereum-pool$ make
build/env.sh go get -v ./...
github.com/sammy007/open-ethereum-pool/util
# github.com/sammy007/open-ethereum-pool/util
util/util.go:12: undefined: common.BigPow
util/util.go:39: undefined: common.BytesToBig
util/util.go:51: undefined: common.Ether
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sammy007** [comment]
Fixed in develop branch.

**Comment by sammy007** [comment]
Package `ethash` broken again waiting for a fix in upstream. I am not going to maintain these dependencies myself.
