### ISSUE TITLE
 recipe for target 'all' failed

### ISSUE THREAD

**Issue by vupv** [sammy007/open-ethereum-pool#121]
#### System information
Ubuntu 16.04 LTS (GNU/Linux 4.4.0-21-generic x86_64)

### Error
root@localhost:~# cd open-ethereum-pool/
root@localhost:~/open-ethereum-pool# make
build/env.sh go get -v ./...
github.com/sammy007/open-ethereum-pool/util
# github.com/sammy007/open-ethereum-pool/util
util/util.go:12: undefined: common.BigPow
util/util.go:39: undefined: common.BytesToBig
util/util.go:51: undefined: common.Ether
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Festors** [comment]
https://github.com/sammy007/open-ethereum-pool/issues/120

**Comment by sammy007** [comment]
All this crap fixed in develop branch.
