### ISSUE TITLE
Do not disconnect miners when they submit a duplicate shares (unless they trigger a limit)

### ISSUE THREAD

**Issue by checksum0** [sammy007/open-ethereum-pool#124]
Miners are currently getting disconnect when they submit a duplicate shares, no matter what the limits are. Miners shouldn't get disconnect if they submit a single duplicate share.

Limits are currently getting applied to invalid share, but not to duplicate share where a disconnect is applied immediately. 

You can find the code proxy/handlers.go, line 75-78.

	if exist {
		log.Printf("Duplicate share from %s@%s %v", login, cs.ip, params)
		return false, &ErrorReply{Code: 22, Message: "Duplicate share"}
	}

As shown here https://github.com/sammy007/open-ethereum-pool/blob/master/proxy/stratum.go#L56, if it returns an ErrorReply instead of nil, the client gets disconnected. I suggest adding a limit similar to invalid share found at line 80-87.

	if !validShare {
		log.Printf("Invalid share from %s@%s", login, cs.ip)
		// Bad shares limit reached, return error and close
		if !ok {
			return false, &ErrorReply{Code: 23, Message: "Invalid share"}
		}
		return false, nil
	}

Disconnecting peers with a single duplicate share currently breaks mining, especially with NiceHash rented hashpower (pay for unused hashrate) or with my own miners (lose hashrate due to disconnect).

I can submit a pull request if you agree with the assessment.

**Comment by sammy007** [comment]
You can adjust whatever you want for yourself. Policy for miners with duplicate share attempts will stay the same here.
