### ISSUE TITLE
what's wrong when running pool. how to solve this

### ISSUE THREAD

**Issue by janeterry** [sammy007/open-ethereum-pool#125]
2017/03/26 10:51:10 Loading config: /home/terry/open-ethereum-pool/config.json
2017/03/26 10:51:10 Running with 2 threads
2017/03/26 10:51:10 Backend check reply: PONG
2017/03/26 10:51:10 Starting API on 0.0.0.0:8080
2017/03/26 10:51:10 Set stats collect interval to 5s
2017/03/26 10:51:10 Set purge interval to 10m0s
2017/03/26 10:51:10 Purged stale stats from backend, 0 shares affected, elapsed time 234.057µs
2017/03/26 10:51:10 Policy state refresh complete
2017/03/26 10:51:10 Set policy stats reset every 1h0m0s
2017/03/26 10:51:10 Set policy state refresh every 1m0s
2017/03/26 10:51:10 Running with 8 policy workers
2017/03/26 10:51:10 Upstream: main => http://127.0.0.1:8545
2017/03/26 10:51:10 Upstream: backup => http://127.0.0.2:8545
2017/03/26 10:51:10 Default upstream: main => http://127.0.0.1:8545
2017/03/26 10:51:10 Stratum listening on 0.0.0.0:8008
2017/03/26 10:51:10 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2017/03/26 10:51:10 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2017/03/26 10:51:10 Set block refresh every 120ms
2017/03/26 10:51:10 Starting proxy on 0.0.0.0:8888
2017/03/26 10:51:10 Stats collection finished 591.231µs
2017/03/26 10:51:11 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2017/03/26 10:51:11 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2017/03/26 10:51:11 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2017/03/26 10:51:11 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refuse

**Comment by phucvinh52** [comment]
You must run ethereum first (turn on rpc).
https://github.com/ethereum/go-ethereum

**Comment by sammy007** [comment]
Please learn basics before opening issues. Pool requires geth or parity node to run.
