### ISSUE TITLE
Stats API Temporarily Down Usually - full resolved

### ISSUE THREAD

**Issue by douglashipocreme** [sammy007/open-ethereum-pool#127]
after build .. i only see 

Stats API Temporarily Down
Usually it's just a temporal issue and mining is not affected.

i am using ubuntu 16.04.1 
npm 4.5.0
node v4.8.1
bower 1.8.0
ember-cli@2.9.1

what am i missing? 
pool and other services are ok 

same thing on my Mac OSX 10.12.1

**Comment by douglashipocreme** [comment]
all done with ubuntu 14 ..
follow this steps and all is good 

sudo -i 
apt install ssh 
apt-get install software-properties-common
add-apt-repository -y ppa:ethereum/ethereum
apt-get update
apt-get install ethereum

add-apt-repository ppa:hectane/go-1.6
apt-get update
apt install golang

add-apt-repository ppa:chris-lea/redis-server
apt-get update
apt install redis-server

curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
apt-get install -y nodejs

npm upgrade -g npm
apt install nginx 

apt-get install git
apt-get install build-essential
npm install -g ember-cli@2.9.1
npm install -g bower

exit (return to ubuntu user )
id to check

cd 
git config --global http.https://gopkg.in.followRedirects true
git clone https://github.com/sammy007/open-ethereum-pool.git
cd open-ethereum-pool

cp config.example.json config.json 
make adjusts config.json change the address to eth wallet
make

screen -dmS geth geth --rpcaddr 127.0.0.1 --rpcport 8545 --rpc --cache=1024 --jitvm --fast --mine --minerthreads=2 --etherbase '0xBCEf79A3572c36062e201A0e831852c57EBAAF72'
screen -x geth 
               (wait dag at 100%)

               copy your keystore if you have one on another geth client

cd /home/ubuntu/open-ethereum-pool/www

npm install
bower install

Correct domain entries on .. 
vi config/environment.js


sudo vi  /etc/nginx/sites-available/default


upstream api {
    server 127.0.0.1:8080;
} 


and add this setting after location /:

location /api {
    proxy_pass http://api;
}


sudo cp -R /home/ubuntu/open-ethereum-pool/www/dist/* /usr/share/nginx/html/.


start all 


screen -dmS geth geth --rpcaddr 127.0.0.1 --rpcport 8545 --rpc --cache=1024 --jitvm  --mine --minerthreads=2 --etherbase '0xBCEf79A3572c36062e201A0e831852c57EBAAF72' --fast --autodag
screen -x geth 
     
cd /home/ubuntu/open-ethereum-pool
screen -dmS pool ./build/bin/open-ethereum-pool config.json

screen -x geth

**Comment by sammy007** [comment]
Resolved? Cool.

**Comment by GatekeeperZA** [comment]
how was this resolved

**Comment by douglashipocreme** [comment]
follow the above steps

**Comment by GatekeeperZA** [comment]
readme says : I highly recommend to use Ubuntu 16.04 LTS.
I cant seem to get the pool going on 16.04 LTS.
