### ISSUE TITLE
set Block reward from 5 to 313

### ISSUE THREAD

**Issue by sthanh0512** [sammy007/open-ethereum-pool#128]
Hi sammy,

I used your pool for mining Musicoin but when it unlock block, reward only 5. So Please guide me how to change reward to 313 as Musicoin block reward.

Thank you!

**Comment by mikeyb** [comment]
edit the source code...

**Comment by sammy007** [comment]
Here https://github.com/sammy007/open-ethereum-pool/blob/master/payouts/unlocker.go#L33

**Comment by Deekor** [comment]
I edited that line to `var constReward = math.MustParseBig256("314000000000000000000")` and it still pays out 5.

Is there something else needed here? Do I need to rebuild?

**Comment by sammy007** [comment]
You must rebuild pool after editing source.

**Comment by Deekor** [comment]
Yup got it. I've been working with interpreted languages too much 😜
