### ISSUE TITLE
Unable to start payouts, failed to retrieve number of peers from node: The method net_peerCount does not exist/is not available

### ISSUE THREAD

**Issue by vupv** [sammy007/open-ethereum-pool#129]
#### System information

Geth version: `geth version` or commit hash if `develop`
Geth
Version: 1.5.9-stable
Git Commit: a07539fb88db7231d18db918ed7a6a4e32f97450
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/root/go

Redis version: `redis-server --version`

Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

OS & Version: Linux/OSX
 Ubuntu 16.04 LTS (GNU/Linux 4.4.0-21-generic x86_64)

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````

**Comment by mikeyb** [comment]
That is from an rpc command failure.  This tells me your geth client is either not running, or rpc server is configured incorrectly in it.  Nothing to do with open-ethereum-pool

**Comment by vupv** [comment]
Dear 
Afler run geth with command /usr/bin/geth  --rpc my pool auto tranfer eth to wallet 0x5879387a2F3A22eD7213F47778Ee6110d91b542a 

I don't know how they do it

**Comment by sammy007** [comment]
Me neither. Make sure you didn't expose RPC to the wild.

**Comment by vupv** [comment]
Hi sammy,
My RPC  listen only on localhost and only me can be ssh to server.

**Comment by sammy007** [comment]
Could be reply attack (ETC) or something different, I have no clue, this is admin's problem, not an error in a pool code.

**Comment by mikeyb** [comment]
On your server run the below command and paste the output.  You either exposed RPC or like sammy said, got replay attacked

`ps aux|grep LIST`

**Comment by vupv** [comment]
Hi Mikeyb,

ethereum@srv15:~$ ps aux|grep LIST
ethereum 16848  0.0  0.0  14228  1012 pts/2    S+   11:10   0:00 grep --color=auto LIST
ethereum@srv15:~$
