### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by eut** [sammy007/open-ethereum-pool#13]
Console show error:

2016/05/13 02:04:48 Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2016/05/13 02:04:48 Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by sammy007** [comment]
Pool just can't perform http request to geth. Check geth, network, settings.

**Comment by d57heinz** [comment]
try putting ip of the computer in there.. like this.. 192.168.1.1  or whatever..
