### ISSUE TITLE
Broadcasting Jobs are sent only to stratum miners

### ISSUE THREAD

**Issue by douglashipocreme** [sammy007/open-ethereum-pool#130]
If some miner use ethminer directly to pool, he was never notified about new jobs.

is it by design ?

**Comment by sammy007** [comment]
Get a clue already, seriously.

**Comment by mikeyb** [comment]
@douglashipocreme what sammy means is:

1.  He hates answering ignorant questions.
2.  If you want to run a stratum based pool, you need to understand the difference between stratum and getwork

At that point you will understand why your getwork client gets no work from a stratum server.

**Comment by douglashipocreme** [comment]
thanks mikeyb ... but he shows an example using ethminer directly and this dont work !

**Comment by sammy007** [comment]
Ethminer works only via http, poll only. Stratum ports are 2 way. Http ports considered legacy and should not be used.
