### ISSUE TITLE
Error on build Docker image:  cannot find package "github.com/ethereum/go-ethereum/pow"

### ISSUE THREAD

**Issue by drrest** [sammy007/open-ethereum-pool#131]
Help me please!

While building Docker raise error:

```
package github.com/ethereum/go-ethereum/pow: cannot find package "github.com/ethereum/go-ethereum/pow" in any of:
	/usr/lib/go-1.6/src/github.com/ethereum/go-ethereum/pow (from $GOROOT)
	/open-ethereum-pool/build/_workspace/src/github.com/ethereum/go-ethereum/pow (from $GOPATH)
```
When i look inside of folder " _workspace/src/github.com/ethereum/go-ethereum/ " i have no see folder pow.

I trying to switch branches and in "poc8" branch of go-ethereum folder "poc8" found, but this is not work.

I trying to add
`go get github.com/ethereum/go-ethereum/pow`

Help please!!!

**Comment by etherninja** [comment]
It not just docker. They broke the dependency in go-ethereum by removing pow.

**Comment by sammy007** [comment]
Go spam this instead https://github.com/ethereum/ethash/issues/94

I am not getting paid from anyone so I am not going to maintain my own versions of their broken packages, they either fix their shit or I am out. My proposal is in related issue.

**Comment by mikeyb** [comment]
`go get github.com/ethereumproject/ethash`
`go get github.com/ethereumproject/go-ethereum/pow`
etc..

Should work for you long term as classic chain will stay PoW/ethash for the foreseeable future.

**Comment by karalabe** [comment]
This upstream PR should solve the issue https://github.com/ethereum/ethash/pull/95 . Note that the ethereum/ethash repository is based on the C++ code, which has a lot of shortcomings and is incompatible with big endian systems. That was the reason for reimplementing ethash in Go https://godoc.org/github.com/ethereum/go-ethereum/consensus/ethash. I'd suggest switching over to that package.

PS: And I strongly suggest vendoring dependencies, as none of this would happen if open pool used proper Go development methodology.

**Comment by sammy007** [comment]
I didn't expect that you are going to grind whole go-ethereum repo so hard, ethash was okay for a year, I will consider switching indeed, but time is limited, at first look I have no idea what is the replacement for `Verify`.

**Comment by karalabe** [comment]
I'll try to fix up the old ethash. You are right in that it shouldn't break. The PR I mentioned vendores (or should) everything it that it used so it shouldn't ever break again. I'll see if I can get it merged in and Ill try to build open pool to see if it fixes the issue.

**Comment by sammy007** [comment]
Yeah please fix, I will switch to vendoring indeed since it's now fashionable, when this repo was born we had tons of crutches for deps so I totally ignored all of them.

**Comment by karalabe** [comment]
Btw, I suggest `govendor`. We've went through a ton of different ones, all having some weird cornercases. govendor was the only one that actually manages to "properly" handle out repo. It still needs a few special "clauses" due to c++ crypto, but that's the last non-go thing.

**Comment by sammy007** [comment]
Okay thx for suggestion.

**Comment by karalabe** [comment]
Is there a docker image for open pool I can try to build to verify that my fix works?

**Comment by sammy007** [comment]
I don't use docker, so there is no Dockerfile.

I need to make some fixes on my side also:

```
proxy/miner.go:44: cannot use share (type Block) as type ethash.Block in argument to hasher.Light.Verify:
	Block does not implement ethash.Block (wrong type for HashNoNonce method)
		have HashNoNonce() "github.com/ethereum/go-ethereum/common".Hash
		want HashNoNonce() "github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/common".Hash
proxy/miner.go:48: cannot use block (type Block) as type ethash.Block in argument to hasher.Light.Verify:
	Block does not implement ethash.Block (wrong type for HashNoNonce method)
		have HashNoNonce() "github.com/ethereum/go-ethereum/common".Hash
		want HashNoNonce() "github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/common".Hash
make: *** [all] Error 2
```

**Comment by sammy007** [comment]
Installation is dead simple, clone repo and run `make`.

**Comment by karalabe** [comment]
No, that's still my error. You can't have vendored types in the API (since they will be different). Will push a second fix in a moment.

**Comment by karalabe** [comment]
Ok, so I will not vendor in `common` since that's part of the API. This is a bit ugly but there's not much to do, it was a bad design decision whoever made it way back.

**Comment by sammy007** [comment]
Cool, it works now, much appreciated!
