### ISSUE TITLE
Uncle block don't show on pool?

### ISSUE THREAD

**Issue by seenagape** [sammy007/open-ethereum-pool#132]
Hi sammy,
I've just deploy a new pool some days.
I mined over 16 blocks & get one uncle, but uncle block didn't showed on pool for payment.
What's wrong with it?

Regards,

**Comment by sammy007** [comment]
No clue.

**Comment by seenagape** [comment]
Hi sammy,

I don't see what you mean?
That is my wallet pool.
As you see on etherscan.io, Mined:  	16 blocks and 1 uncle, 
But on pool, there are no uncle block, but ether's uncle still come on the wallet.

**Comment by sammy007** [comment]
As I said I have no clue, I have no details, you should do all investigation yourself, log analysis, etc.

**Comment by seenagape** [comment]
Thanks sammy.
I'll investigate it.

**Comment by sammy007** [comment]
FYI, unlocking code is not 100% reliable but I did my best to make it perfect, it's due to poor eth rpc functionality and the moment when I wrote it, nothing changed so far AFAIK. It's near impossible to miss uncle, it tested hard and a lot of installations using this pool without any complains so far. Are you sure you didn't mine block to this address without pool?

**Comment by seenagape** [comment]
Here is the block uncle.
It was mined by my pool, (0x005c8...) and ether had come to pool wallet.
https://etherscan.io/uncle/0x3d7f1c8344dd7f01849dcbb0c2ecdd22edc42af9b90a30a1d37776d12b8cba0e

Is there any way to create block uncle manual & show it on pool?

**Comment by sammy007** [comment]
Only by hands in redis and this is very advanced. I bet it was redis outage becaus ethere is no false orphan or incorrectly unlocked block for this uncle.

You can ask someone whi is running a pool for help. If you have share records for this round you can insert a row into `eth:block:candidates` ZSET matching round height for this uncle (not always the same as in explorer), for row example you can inspect this ZSET when new block will be found.

**Comment by seenagape** [comment]
Thanks sammy.
