### ISSUE TITLE
api address giving 404?

### ISSUE THREAD

**Issue by Deekor** [sammy007/open-ethereum-pool#133]
Starting API on 45.55.22.26:8080

When navigating there I get a 404 error. Same thing happened on development.

**Comment by mikeyb** [comment]
That is how it works.  an API is **NOT** a web page

**Comment by Deekor** [comment]
I understand that - I was expecting to see a JSON API at that location, is this not the case?

**Comment by Deekor** [comment]
Figured it out. There is no index for the api - need to go directly to and endpoint such as `/api/accounts/`
