### ISSUE TITLE
Unable to set rig name

### ISSUE THREAD

**Issue by Deekor** [sammy007/open-ethereum-pool#134]
I was having issues on http://musicminers.org/ where I couldn't connect to their pool if i set a rig name i.e `myaddress.rigname`. I downloaded and installed open-ethereum-pool to play around with it a bit and still cannot connect to my local pool when I add a rig name.

**Comment by sammy007** [comment]
Rig name must be 8 characters (A-Za-z0-9_).

**Comment by Deekor** [comment]
Can that length be adjusted?

**Comment by sammy007** [comment]
Yes, by pool owner.

**Comment by Deekor** [comment]
Where in the code is it adjusted?

**Comment by sammy007** [comment]
https://github.com/sammy007/open-ethereum-pool/blob/master/proxy/handlers.go#L15

WARN: never allow `:` or `.`.

**Comment by sony87** [comment]
Most probably you are using Claymore so just use "-eworker" parameter and it's working fine without code modifications.

**Comment by mbunal** [comment]
hi
lolminer doesnt have any worker parameter. how can i use wal.rigname?
