### ISSUE TITLE
Configure nginx

### ISSUE THREAD

**Issue by phuocanh421994** [sammy007/open-ethereum-pool#136]
> Configure nginx to serve API on /api subdirectory. Configure nginx to serve www/dist as static website.
> 
> Serving API using nginx
> 
> Create an upstream for API:
> 
> upstream api {
>     server 127.0.0.1:8080;
> }
> and add this setting after location /:
> 
> location /api {
>     proxy_pass http://api;
> }
> Customization
> 
> You can customize the layout using built-in web server with live reload:
> 
> ember server --port 8082 --environment development
> 

I just recently used VPS, please guide me at this step, and share me a document.

**Comment by sammy007** [comment]
https://university.nginx.com/
