### ISSUE TITLE
 what's the maximum of miners can be connected to the pool simultaneously

### ISSUE THREAD

**Issue by hgbing** [sammy007/open-ethereum-pool#137]
Hi Sammy,
I setup an ether pool according to your instructions, it's working pretty well, thanks for your great job.
I'm curious about what's the maximum of miners can be connected to the pool simultaneously? 
my server configuration as below:
OS:ubuntu 16.04 LTS
Memory:16G
CPU: intel Core i7-6700 cpu@3.40GHz*8
GPU: intel HD Graphics 530
OS: 64 bit
Disk: 2TB

**Comment by sammy007** [comment]
Usually more than you can attract.
