### ISSUE TITLE
Fees not paying out?

### ISSUE THREAD

**Issue by Deekor** [sammy007/open-ethereum-pool#138]
I see in the logs 

    IMMATURE 342350:0xacd184f8427f5d76c0108726cab19aedc4da6c7384e4d888d972914591d29a70: revenue 314.00210000, miners profit 310.86207900, pool profit: 3.14002100

But I never actually see that pool profit hit my wallet. If my miners are mining to the same wallet does it combine the reward and pool profit?

**Comment by mikeyb** [comment]
You cannot pay out immature tokens...

**Comment by Deekor** [comment]
I know that. After they mature and payout i never see the pool profit transaction. I was just showing that line because it states there will be a pool profit.

Dee

**Comment by Deekor** [comment]
I was using a bittrex address for the fee - once I moved a client address it started working.
