### ISSUE TITLE
poolFeeAddress on config.json 

### ISSUE THREAD

**Issue by vupv** [sammy007/open-ethereum-pool#139]
Dear
Pls help me, Can i use address create from https://poloniex.com for poolFeeAddress on config.json 

Thank

**Comment by vupv** [comment]
Have any body help

**Comment by sammy007** [comment]
Yes, you can.

**Comment by vupv** [comment]
thank sammy but my pool was found two block and was pay for miner but we could not recived any eth in poolFeeAddress while we set pool fee is 1%

**Comment by mikeyb** [comment]
and you rebuilt the code and restarted after making the change?

**Comment by vupv** [comment]
mikeyb: I don't understood . We do't change any code

**Comment by vupv** [comment]
Hi sammy,
How long time for New Bock move Block. Can iI config for fast time ?  Pls help

**Comment by sammy007** [comment]
Please try using better translation software.
