### ISSUE TITLE
unable to make

### ISSUE THREAD

**Issue by tealsteam** [sammy007/open-ethereum-pool#141]
#### System information

Geth version: `geth version` or commit hash if `develop`
       1.6.0-stable-facc47cb

Redis version: `redis-server --version`
      N/A

OS & Version: Linux/OSX
      Ubuntu 16.04 Server

Commit branch and hash: (`master`, `ba60e1c`)
   ????

#### Expected behaviour
make successful.

#### Actual behaviour
username@servername:~/open-ethereum-pool$ make
build/env.sh go get -v ./...
build/env.sh: 32: exec: go: not found
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 127

#### Backtrace

````
[backtrace]
````

**Comment by sammy007** [comment]
go: not found.

**Comment by mikeyb** [comment]
Your github issues oddly enough intrigue me with so much rage I can't stay away from being subscribed to them.

**Comment by tealsteam** [comment]
Thanks sammy, that should have been obvious, just needed a fresh set of eyes.
