### ISSUE TITLE
ethminer won't connect to pool

### ISSUE THREAD

**Issue by tealsteam** [sammy007/open-ethereum-pool#142]
#### System information

Geth version: `geth version` or commit hash if `develop`
Version: 1.6.0-stable

Redis version: `redis-server --version`
Redis server v=3.2.8 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=23080308ff99c5db

node --version
v4.2.6

OS & Version: Linux/OSX
Ubuntu 16.04 LTS Server

Commit branch and hash: (`master`, `ba60e1c`)
master

#### Expected behaviour
As all steps completed without incident, Pool Webpage shows, API online,.
expected ethminer to start mining,

#### Actual behaviour
Connecting to GETH on: ethminer.exe -G -F 192.168.1.47:8545 --farm-recheck 200  - ALL OK.

Connecting to GETH on: pool looks OK and displays the following:
 2017/04/24 13:12:51 Stats collection finished 443.509µs
2017/04/24 13:12:55 Policy state refresh complete
2017/04/24 13:12:56 Stats collection finished 464.628µs
2017/04/24 13:13:00 New block to mine on main at height 3592125 / 0xde4e305d
2017/04/24 13:13:00 Broadcasting new job to 0 stratum miners
2017/04/24 13:13:00 Jobs broadcast finished 31.909µs
2017/04/24 13:13:01 Stats collection finished 416.024µs
2017/04/24 13:13:06 Stats collection finished 515.07µs
2017/04/24 13:13:08 New block to mine on main at height 3592126 / 0xa1eb85ea
2017/04/24 13:13:08 Broadcasting new job to 0 stratum miners
2017/04/24 13:13:08 Jobs broadcast finished 26.595µs
2017/04/24 13:13:11 Stats collection finished 571.359µs

Connecting to Pool on: ethminer.exe -G -F 192.168.1.47:8008/0xe36d5012f5cc6d1c9de699fddad497e288f274d5/tealsteam42 --farm-recheck 200

Pool displays: 
2017/04/24 13:06:51 Malformed stratum request from 192.168.1.19: invalid character 'P' looking for beginning of value

Miner shows:
Found suitable OpenCL device [Tahiti ] with 3221225472 bytes of GPU memory
  m  13:14:21|main  Getting work package...
  X  13:14:21|main  Failed to submit hashrate.
  X  13:14:21|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 52

JSON-RPC problem. Probably couldn't connect. Retrying in 1...

I've tried to include as much information as I can, I have checked configs, restarted services, disabled ufw.
#### Backtrace

````
[backtrace]
````

**Comment by tealsteam** [comment]
Not sure if you wan't to this closed,

however, I tried claymore miner, and that connects properly, just seem to have this issue with ethminer.

**Comment by coinnodenl** [comment]
You should split ip/wallet different

like -F ip+port -O address.user:password this will fix it

**Comment by tealsteam** [comment]
I already tried that, maybe I should have said,

ethminer.exe -G -F 192.168.1.47:8008 -O 0xe36d5012f5cc6d1c9de699fddad497e288f274d5.tealsteam12:pass
ethminer.exe -G -F 192.168.1.47:8008 -O 0xe36d5012f5cc6d1c9de699fddad497e288f274d5.tealsteam12
ethminer.exe -G -F 192.168.1.47:8008 -O 0xe36d5012f5cc6d1c9de699fddad497e288f274d5/tealsteam12

each show this error

Found suitable OpenCL device [Tahiti ] with 3221225472 bytes of GPU memory
  m  17:00:05|main  Getting work package...
  X  17:00:05|main  Failed to submit hashrate.
  X  17:00:05|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 52

**Comment by bmatthewshea** [comment]
Seeing same thing in logs. (Not my IP, though). Thought I would comment since I saw this (yes, I know its closed/old):

You/OP are trying to FARM (HTTP GetWork) (-F) on a STRATUM (-S) broadcast port. 
Try `-S` **not** `-F` 

And what's with the '/' forward slash? Have you looked at `ethminer --help` ? It certainly doesn't mention to use a slash. Do what it says re: user and password use below. Arbitrarily changing things that are not shown in help is not going make it work. ETHMINER works fine IF you use the correct settings/flags.
```
Work farming mode:
    -F,--farm <url>  Put into mining farm mode with the work server at URL (default: http://127.0.0.1:8545)
    -S, --stratum <host:port>  Put into stratum mode with the stratum server at host:port
    -O, --userpass <username.workername:password> Stratum login credentials
```
