### ISSUE TITLE
Ask about payout ?

### ISSUE THREAD

**Issue by liamhoang** [sammy007/open-ethereum-pool#147]
sorry I'm new with this and very bad at all. 
this is my config.json

> 
> "unlocker": {
> 		"enabled": true,
> 		"poolFee": 1.0,
> 		"poolFeeAddress": "0x50115d3f7c84e7227c9987df2bb2dd3fe71207ff",
> 		"donate": false,
> 		"depth": 120,
> 		"immatureDepth": 20,
> 		"keepTxFees": false,
> 		"interval": "10m",
> 		"daemon": "http://127.0.0.1:8545",
> 		"timeout": "10s"
> 	},
> 
> 	"payouts": {
> 		"enabled": true,
> 		"requirePeers": 25,
> 		"interval": "120m",
> 		"daemon": "http://127.0.0.1:8545",
> 		"timeout": "10s",
> 		"address": "0x50115d3f7c84e7227c9987df2bb2dd3fe71207ff",
> 		"gas": "21000",
> 		"gasPrice": "50000000000",
> 		"autoGas": true,
> 		"threshold": 1000000000,
> 		"bgsave": false
> 	},

1, I need the pool automatic payment to miners address, so the address field in that config.json is a address when I run geth account new or I can use any address like btc-e, poloniex? What different between payout address and unlocker address? Can I use a same address? 
2, geth --rpcaddr 127.0.0.1 --rpcport 8545 --rpc --cache=1024 
do i need add --unlock [address when run geth account new] for automatic payment ? or what is the best command at this point?

Thank you very much !

**Comment by sammy007** [comment]
Address in payout section must match address with pool's block rewards. Keep some dust in this address for miner fees to process payouts. Periodically send something like 5 USD worth of ETH back from poolFeeAddress.
