### ISSUE TITLE
 Current Payment:

### ISSUE THREAD

**Issue by vupv** [sammy007/open-ethereum-pool#148]
Deam Sammy,
Pls help how to clear  Current Payment . I had manual pay one payment but i can not clear Current Payment

**Comment by sammy007** [comment]
I don't understand question. Read payment resolution manual.
https://github.com/sammy007/open-ethereum-pool/blob/master/docs/PAYOUTS.md

Perhaps you need this https://github.com/sammy007/open-ethereum-pool/blob/master/docs/PAYOUTS.md#delete-erroneous-payment-entry
