### ISSUE TITLE
Reported miner speed is lower than actual

### ISSUE THREAD

**Issue by sony87** [sammy007/open-ethereum-pool#149]
Hi, sorry if it's asked question but i was not able to trace it.
Is there a server option in the pool that can help optimize the reported speed because i have difference in the miner reported and pool : miner 170 pool 160, miner 120 pool 100

Blocks, payments and everything is ok but this is driving me crazy. Any ideas ?

edit: those are not only short but long average also, never can reach the actual speed even with weeks of uptime in the miner.

**Comment by sammy007** [comment]
Pool calculates hashrate from shares submitted, this is effective hashrate. I bet some og your shares are stale or invalid, this is why hashrate is lower. Try rising estimation windows to minimum 30-60 minutes and mine stable for precise numbers.

**Comment by sony87** [comment]
Hey @sammy007 , yes I know it depends on the stale/invalid shares but i mostly don't have rejects, maybe 1 on 2000 shares, stales none to minimum. I have rised the long estimate to 6hrs and i can't reach the actual hashing speed with such stats and not outages. That's my concern.

**Comment by sammy007** [comment]
Could be miner's devfees also.

**Comment by mikeyb** [comment]
The pool literally gives 0 fucks about hash rates. it only cares about shares submitted.  Most likely your difficulty is bad and you arent submitting shares at a difficulty in line with your hash rate.  But I really fail to see how this warrants a issue on the pool software.  It just calculates shares submitted over a certain time frame, it has nothing to do with your hash rates.

**Comment by sony87** [comment]
"how this warrants a issue on the pool software"

I have never said it's pool issue, i'm just asking for advise, sorry if you take me wrong. What difficulty you advise to use on regular 170mh miner ?

**Comment by LeChuckDE** [comment]
Maybe also a problem with the blocktime, if it isn't set correctly the calculation didn't work correctly

**Comment by wizzfile** [comment]
ok

2017-05-29 11:29 GMT+03:00 Mark <notifications@github.com>:
