### ISSUE TITLE
Second Diff port

### ISSUE THREAD

**Issue by wiico** [sammy007/open-ethereum-pool#150]
#### System information

Geth / Redis version:3.0 / ubuntu 16.04 / Commit branch and hash: (`master`, `ba60e1c`)

Hi Sammy,

Thanks for you're work.  

How can add a new stratum port for nicehash with bigger diff ? 

8008 2000000000
8009 10000000000

Best regard.

````
[backtrace]
````

**Comment by sammy007** [comment]
Launch another stratum process.
