### ISSUE TITLE
Make finish with error

### ISSUE THREAD

**Issue by alptolga** [sammy007/open-ethereum-pool#152]
Ubuntu 16.04 lts
Geth version:
1.6.3-stable-99cba96f
 make process finished with errors. Can you  help me?

~/open-ethereum-pool$ make
build/env.sh go get -v ./...
github.com/gorilla/mux (download)
github.com/gorilla/context (download)
github.com/ethereum/go-ethereum (download)
Fetching https://gopkg.in/redis.v3?go-get=1
Parsing meta tags from https://gopkg.in/redis.v3?go-get=1 (status code 200)
get "gopkg.in/redis.v3": found meta tag main.metaImport{Prefix:"gopkg.in/redis.v3", VCS:"git", RepoRoot:"https://gopkg.in/redis.v3"} at https://gopkg.in/redis.v3?go-get=1
gopkg.in/redis.v3 (download)
Fetching https://gopkg.in/bsm/ratelimit.v1?go-get=1
Parsing meta tags from https://gopkg.in/bsm/ratelimit.v1?go-get=1 (status code 200)
get "gopkg.in/bsm/ratelimit.v1": found meta tag main.metaImport{Prefix:"gopkg.in/bsm/ratelimit.v1", VCS:"git", RepoRoot:"https://gopkg.in/bsm/ratelimit.v1"} at https://gopkg.in/bsm/ratelimit.v1?go-get=1
gopkg.in/bsm/ratelimit.v1 (download)
github.com/ethereum/ethash (download)
github.com/go-stack/stack (download)
github.com/yvasiyarov/gorelic (download)
github.com/yvasiyarov/go-metrics (download)
github.com/yvasiyarov/newrelic_platform_go (download)
github.com/ethereum/go-ethereum/common/hexutil
github.com/gorilla/context
github.com/ethereum/go-ethereum/common/math
gopkg.in/redis.v3/internal
gopkg.in/redis.v3/internal/consistenthash
gopkg.in/redis.v3/internal/hashtag
gopkg.in/bsm/ratelimit.v1
gopkg.in/redis.v3/internal/pool
github.com/ethereum/go-ethereum/crypto/secp256k1
github.com/gorilla/mux
github.com/ethereum/go-ethereum/common
gopkg.in/redis.v3
github.com/sammy007/open-ethereum-pool/util
github.com/ethereum/go-ethereum/crypto/sha3
github.com/sammy007/open-ethereum-pool/rpc
github.com/ethereum/go-ethereum/rlp
github.com/go-stack/stack
github.com/ethereum/go-ethereum/log
github.com/yvasiyarov/go-metrics
github.com/yvasiyarov/newrelic_platform_go
github.com/yvasiyarov/gorelic
github.com/sammy007/open-ethereum-pool/storage
github.com/sammy007/open-ethereum-pool/payouts
github.com/sammy007/open-ethereum-pool/api
github.com/sammy007/open-ethereum-pool/policy
github.com/ethereum/go-ethereum/crypto
github.com/ethereum/ethash
# github.com/ethereum/ethash
../../ethereum/ethash/ethash.go:436: undefined: "github.com/ethereum/go-ethereum/crypto".Sha3Hash
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sammy007** [comment]
Works for me.

**Comment by alptolga** [comment]
Thanks for your detailed explanation.

**Comment by crypto11** [comment]
Even i am facing same problem. Just curious if you found a solution to it.

**Comment by sammy007** [comment]
`make clean && make` or do a fresh clone.

**Comment by alptolga** [comment]
Reinstall go with these steps.
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04
