### ISSUE TITLE
getting this error after giving command make

### ISSUE THREAD

**Issue by aburaza** [sammy007/open-ethereum-pool#153]
build/env.sh go get -v ./...
/usr/local/go/src/net/http/h2_bundle.go:45:2: cannot find package "golang_org/x/net/http2/hpack" in any of:
	/usr/local/go/src/golang_org/x/net/http2/hpack (from $GOROOT)
	/root/open-ethereum-pool/build/_workspace/src/golang_org/x/net/http2/hpack (from $GOPATH)
/usr/local/go/src/net/http/h2_bundle.go:46:2: cannot find package "golang_org/x/net/lex/httplex" in any of:
	/usr/local/go/src/golang_org/x/net/lex/httplex (from $GOROOT)
	/root/open-ethereum-pool/build/_workspace/src/golang_org/x/net/lex/httplex (from $GOPATH)
import cycle not allowed
package github.com/sammy007/open-ethereum-pool
	imports encoding/json
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports runtime
make: *** [all] Error 1

**Comment by alptolga** [comment]
Use this installation method for go 1.5
curl -O https://storage.googleapis.com/golang/go1.5.linux-amd64.tar.gz
tar xvf go1.5.linux-amd64.tar.gz
sudo chown -R root:root ./go
sudo mv go /usr/local
sudo nano ~/.profile
At the end of the file, add this line:
export GOPATH=$HOME/work
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
source ~/.profile

**Comment by bdangel1984** [comment]
you need GO1.7 at least
