### ISSUE TITLE
Pool with geth on Ropsten Testnet not showing ethminer clients

### ISSUE THREAD

**Issue by naqvijafar91** [sammy007/open-ethereum-pool#154]
#### System information
Server Ubuntu 16.04 on which the pool and geth are running
Digital Ocean Server Ubuntu 16.04 2 GB RAM, Dual Core running ethminer

Geth version: `geth version` or commit hash if `develop`
1.6.x
Redis version: `redis-server --version`
3.29
OS & Version: Linux/OSX
Ubuntu 16.04
Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
Pool should show the miner as connected and Testnet Ropsten ethers should be mined on the address associated with ethminer

#### Actual behaviour
Ethminer shows connected and mining:
Mining on PoWhash #5054f08e… : 54035 H/s = 30800 hashes / 0.57 s

But nothing is displayed on the pool's frontend as well as no miners connected from the stats collection api and no etheres are mined

#### Steps to reproduce the behaviour
I installed ethminer on Ubuntu 16.04 by following this link:
https://www.meebey.net/posts/ethereum_gpu_mining_on_linux_howto/

#### Backtrace

````
[backtrace]
````

Also, may be the ethminer is not functioning well, but i do not think thats an actual case, but it would be great if anybody could also provide some documentation about installing ethminer or any other compaitable miner on Ubuntu

**Comment by alptolga** [comment]
I think the problem is redis or redis configuration. Use this link for redis.
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-redis-on-ubuntu-16-04
