### ISSUE TITLE
Network Hash Rate

### ISSUE THREAD

**Issue by DrHyperKALICH** [sammy007/open-ethereum-pool#155]
Hello Sammy!

Network Hash Rate at home page footer showing wrong. Actually about 7 times more then actual now.

All other metrics like Network Difficulty, Blockchain Height, Pool Hash Rate are OK.

The only thing I am changed is shares difficulty. 10 times lower then default.

How make it correct?

PS pool mining ubiq with last version of gubiq.

**Comment by KosinusKC** [comment]
have solved this? have the same problem
