### ISSUE TITLE
Unlocking suspended due to last critical error: invalid argument 0: invalid hex

### ISSUE THREAD

**Issue by naqvijafar91** [sammy007/open-ethereum-pool#156]
I am using a Geth instance running Ropsten Testnet blockchain
#### System information

Geth version: `geth version` or commit hash if `develop`
1.6.x

Redis version: `redis-server --version`
3.29

OS & Version: Linux/OSX
Ubuntu 16.04

Commit branch and hash: (`master`, `ba60e1c`)
master

#### Config.json
{
	"threads": 2,
	"coin": "eth",
	"name": "main",

	"proxy": {
		"enabled": true,
		"listen": "0.0.0.0:8888",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 2000000000,
		"hashrateExpiration": "3h",

		"healthCheck": true,
		"maxFails": 100,

		"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8008",
			"timeout": "120s",
			"maxConn": 8192
		},

		"policy": {
			"workers": 8,
			"resetInterval": "60m",
			"refreshInterval": "1m",

			"banning": {
				"enabled": false,
				"ipset": "blacklist",
				"timeout": 1800,
				"invalidPercent": 30,
				"checkThreshold": 30,
				"malformedLimit": 5
			},
			"limits": {
				"enabled": false,
				"limit": 30,
				"grace": "5m",
				"limitJump": 10
			}
		}
	},

	"api": {
		"enabled": true,
		"purgeOnly": false,
		"purgeInterval": "10m",
		"listen": "0.0.0.0:8080",
		"statsCollectInterval": "5s",
		"hashrateWindow": "30m",
		"hashrateLargeWindow": "3h",
		"luckWindow": [64, 128, 256],
		"payments": 30,
		"blocks": 50
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://127.0.0.1:8545",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://127.0.0.2:8545",
			"timeout": "10s"
		}
	],

	"redis": {
		"endpoint": "127.0.0.1:6379",
		"poolSize": 10,
		"database": 0,
		"password": ""
	},

	"unlocker": {
		"enabled": true,
		"poolFee": 1.0,
		"poolFeeAddress": "",
		"donate": true,
		"depth": 35,
		"immatureDepth": 17,
		"keepTxFees": false,
		"interval": "1m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s"
	},

	"payouts": {
		"enabled": true,
		"requirePeers": 5,
		"interval": "2m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s",
		"address": "0x0c53d4a0c32e13988127911eac4e794dcd2f01d1",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500,
		"bgsave": false
	},

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}

#### Expected behaviour
Payouts should happen after unlocking

#### Actual behaviour
i get this message in logs:
Unlocking suspended due to last critical error: invalid argument 0: invalid hex

#### Steps to reproduce the behaviour
just run the pool

#### Backtrace

````
[backtrace]
2017/06/06 10:48:57 Policy state refresh complete
2017/06/06 10:48:57 Set policy stats reset every 1h0m0s
2017/06/06 10:48:57 Set policy state refresh every 1m0s
2017/06/06 10:48:57 Running with 8 policy workers
2017/06/06 10:48:57 Upstream: main => http://127.0.0.1:8545
2017/06/06 10:48:57 Upstream: backup => http://127.0.0.2:8545
2017/06/06 10:48:57 Default upstream: main => http://127.0.0.1:8545
2017/06/06 10:48:57 Starting API on 0.0.0.0:8080
2017/06/06 10:48:57 Set stats collect interval to 5s
2017/06/06 10:48:57 Set purge interval to 10m0s
2017/06/06 10:48:57 Starting block unlocker
2017/06/06 10:48:57 Set block unlock interval to 1m0s
2017/06/06 10:48:57 Stratum listening on 0.0.0.0:8008
2017/06/06 10:48:57 Purged stale stats from backend, 0 shares affected, elapsed time 2.209183ms
2017/06/06 10:48:57 Stats collection finished 1.035231ms
2017/06/06 10:48:57 Error while retrieving block -15 from node: invalid argument 0: invalid hex
2017/06/06 10:48:57 Failed to unlock blocks: invalid argument 0: invalid hex
2017/06/06 10:48:57 Unlocking suspended due to last critical error: invalid argument 0: invalid hex
2017/06/06 10:48:57 New block to mine on main at height 1066771 / 0xda076634
````

**Comment by bdangel1984** [comment]
clear all the datas in redis database

**Comment by naqvijafar91** [comment]
@bdangel1984 are you sure there is no issue with my config.json

**Comment by bdangel1984** [comment]
i dont check that , but first you'd better clear the database. i had same problem once

**Comment by sammy007** [comment]
By design. Talk in gitter if you wanna talk.
