### ISSUE TITLE
Is there any way to set up different difficult

### ISSUE THREAD

**Issue by liuhongjiang** [sammy007/open-ethereum-pool#157]
We have used open-ethereum-pool to set up our own mining pool, and it works amazingly.

Now we have set up several pool and save data into one redis.

Can we setup different difficult for different pool process, when save all data including shares into one redis?

if it's possible, should we only change configuration, or need we change some code?

**Comment by hogze94** [comment]
What is the difficulty for? I see default is 20GH.

**Comment by wizzfile** [comment]
Yes

На 14.06.2017 г. 7:43 "hogze94" <notifications@github.com> написа:

**Comment by sammy007** [comment]
https://github.com/sammy007/open-ethereum-pool/issues/10
