### ISSUE TITLE
Worker stats for multiple workers on same account don't seem to be showing all workers

### ISSUE THREAD

**Issue by alterdev** [sammy007/open-ethereum-pool#158]
I might have not set up something correctly. But here we go. 

#### System information
version Parity/v1.6.5-beta-987390f-20170328/x86_64-linux-gnu/rustc1.16.0
Redis server v=3.2.8

OS & Version: Linux/OSX
Ubuntu 16.04.2 LTS

Commit branch and hash: (`master`, `ba60e1c`)
master

#### Expected behavior
When i go to api/accounts/account i would like to see workers stats info correctly for multiple workers on same account. If i have 2 workers with different names on same account i expect in workers to see 0 and 1. Also workersOnline should be 2.

#### Actual behavior
In workers i get 
"workers":{"0":{"lastBeat":1497286071,"hr":722222222,"offline":false,"hr2":747555638}},"workersOffline":0,"workersOnline":1,"workersTotal":1}

#### Steps to reproduce the behavior
Try to connect two miners on same account with different names on the pool. 
Check api/accounts/account.

#### Config file
"api": {
                "enabled": true,
                "purgeOnly": false,
                "purgeInterval": "10m",
                "listen": "0.0.0.0:8080",
                "statsCollectInterval": "5s",
                "hashrateWindow": "30m",
                "hashrateLargeWindow": "3h",
                "luckWindow": [64, 128, 256],
                "payments": 30,
                "blocks": 50
        }

**Comment by Serpent6877** [comment]
Same problem here. Connected to another pool shows users correctly:

![openeth](https://user-images.githubusercontent.com/2003960/29739347-98fd2a0e-89f0-11e7-93a3-f385c2d8b27b.jpg)

But here it combined that user and displays them as what appears the first letter:

![openeth-2](https://user-images.githubusercontent.com/2003960/29739348-9c537974-89f0-11e7-9c36-da51ea1b6686.jpg)

**Comment by Serpent6877** [comment]
Did more research. This is not a www issue but an API issue when it stores the worker name into redis. I can see in the redis DB that the username is 0.

**Comment by Serpent6877** [comment]
I have pinned this down to workers with names longer than 8 characters.  This is set here:

proxy.go: 
func (s *ProxyServer) Start() {
        log.Printf("Starting proxy on %v", s.config.Proxy.Listen)
        r := mux.NewRouter()
        r.Handle("/{login:0x[0-9a-fA-F]{40}}/{id:[0-9a-zA-Z-_]{1,8}}", s)

First with the proxy server. 1,8. Then:

handlers.go:
var workerPattern = regexp.MustCompile("^[0-9a-zA-Z-_]{1,8}$")


Which then when this function is ran:

func (s *ProxyServer) handleSubmitRPC(cs *Session, login, id string, params []string) (bool, *ErrorReply) {
        if !workerPattern.MatchString(id) {
                id = "0"
        }

Sets the id to 0 (zero) because the pattern does not match due to the above shortening the name to 8 characters.

**Comment by Serpent6877** [comment]
Fixed by changing the above to 1,32 and recompiled.
