### ISSUE TITLE
Cannot run the pool module

### ISSUE THREAD

**Issue by lazybtc** [sammy007/open-ethereum-pool#159]
So I have my geth node working on a putty prompt, I open another putty and run the following to get the pool working,
./build/bin/open-ethereum-pool config.json
but it fails to start, can someone tell me what am I doing wrong?, I have replaced all the 0.0.0.0 and 127.0.0.1 and http://ip.ip.ip.ip with the numeric ip of my server
Also when they say to run three instances (mining, payments, API) does he means to make three separate configs like mining.json payments.json and api.json and run each one with 
./build/bin/open-ethereum-pool mining.json 
./build/bin/open-ethereum-pool payments.json 
./build/bin/open-ethereum-pool api.json????????????????????
Please find below the results of running ./build/bin/open-ethereum-pool config.json

2017/06/14 00:25:17 Loading config: /root/open-ethereum-pool/config.json
2017/06/14 00:25:17 Running with 1 threads
2017/06/14 00:25:17 Can't establish connection to backend: dial tcp XXXX:6379: getsockopt: connection refused
2017/06/14 00:25:17 Starting payouts
2017/06/14 00:25:17 Set payouts interval to 2h0m0s
2017/06/14 00:25:17 Starting API on XXXXX:8080
2017/06/14 00:25:17 Set stats collect interval to 5s
2017/06/14 00:25:17 Set purge interval to 10m0s
2017/06/14 00:25:17 Unable to start payouts: dial tcp XXXX:6379: getsockopt: connection refused
2017/06/14 00:25:17 Failed to purge stale data from backend: dial tcp XXX:6379: getsockopt: connection refused
2017/06/14 00:25:17 Failed to get blacklist from backend: dial tcp XXXX:6379: getsockopt: connection refused
2017/06/14 00:25:17 Failed to get whitelist from backend: dial tcp XXX:6379: getsockopt: connection refused
2017/06/14 00:25:17 Policy state refresh complete
2017/06/14 00:25:17 Set policy stats reset every 1h0m0s
2017/06/14 00:25:17 Set policy state refresh every 1m0s
2017/06/14 00:25:17 Running with 8 policy workers
2017/06/14 00:25:17 Upstream: main => XXXX:8545
2017/06/14 00:25:17 Upstream: backup => XXXX:8545
2017/06/14 00:25:17 Default upstream: main => XXXX:8545
2017/06/14 00:25:17 Error while refreshing pending block on main: Post XXXX:8545: unsupported protocol scheme ""
2017/06/14 00:25:17 Error while refreshing pending block on main: Post XXX:8545: unsupported protocol scheme ""
2017/06/14 00:25:17 Set block refresh every 120ms
2017/06/14 00:25:17 Starting proxy on XXXX:8888
2017/06/14 00:25:17 Stratum listening on XXXX:8008
2017/06/14 00:25:17 Failed to fetch stats from backend: dial tcp XXXX:6379: getsockopt: connection refused

**Comment by bdangel1984** [comment]
you need to run geth first, with rpc options

**Comment by lazybtc** [comment]
I did that using geth  --fast --cache=512 console --rpcaddr 127.0.0.1 --rpcport 8545 --rpc 
Geth opens without problems
and when i run the ./build/bin/open-ethereum-pool config.json  on another putty console I get
2017/06/15 03:35:32 Loading config: /root/open-ethereum-pool/config.json
2017/06/15 03:35:32 Running with 1 threads
2017/06/15 03:35:32 Can't establish connection to backend: dial tcp 127.0.0.1:6379: getsockopt: connection refused
2017/06/15 03:35:32 Starting payouts
2017/06/15 03:35:32 Set payouts interval to 2h0m0s
2017/06/15 03:35:32 Starting API on 127.0.0.1:8080
2017/06/15 03:35:32 Set stats collect interval to 5s
2017/06/15 03:35:32 Set purge interval to 10m0s
2017/06/15 03:35:32 Failed to purge stale data from backend: dial tcp 127.0.0.1:6379: getsockopt: connection refused
2017/06/15 03:35:32 Failed to get blacklist from backend: dial tcp 127.0.0.1:6379: getsockopt: connection refused
2017/06/15 03:35:32 Failed to get whitelist from backend: dial tcp 127.0.0.1:6379: getsockopt: connection refused
2017/06/15 03:35:32 Policy state refresh complete
2017/06/15 03:35:32 Set policy stats reset every 1h0m0s
2017/06/15 03:35:32 Set policy state refresh every 1m0s
2017/06/15 03:35:32 Running with 8 policy workers
2017/06/15 03:35:32 Upstream: main => 127.0.0.1:8545
2017/06/15 03:35:32 Upstream: backup => http://127.0.0.2:8545
2017/06/15 03:35:32 Default upstream: main => 127.0.0.1:8545
2017/06/15 03:35:32 Error while refreshing pending block on main: Post 127.0.0.1:8545: unsupported protocol scheme ""
2017/06/15 03:35:32 Error while refreshing pending block on main: Post 127.0.0.1:8545: unsupported protocol scheme ""
2017/06/15 03:35:32 Set block refresh every 120ms
2017/06/15 03:35:32 Starting proxy on 127.0.0.1:8888
2017/06/15 03:35:32 Failed to fetch stats from backend: dial tcp 127.0.0.1:6379: getsockopt: connection refused
2017/06/15 03:35:32 Unable to start payouts: dial tcp 127.0.0.1:6379: getsockopt: connection refused
2017/06/15 03:35:32 Stratum listening on 127.0.0.1:8008
2017/06/15 03:35:32 Error while refreshing pending block on main: Post 127.0.0.1:8545: unsupported protocol scheme ""
2017/06/15 03:35:32 Error while refreshing pending block on main: Post 127.0.0.1:8545: unsupported protocol scheme ""
2017/06/15 03:35:32 Error while refreshing pending block on main: Post 127.0.0.1:8545: unsupported protocol scheme ""

Im really sorry to ask those things because they seem to be so simple that I'm the only one stupid enough to be  asking those, googling my issues doesnt return many stuff because it seems that nobody has issues with this thing

**Comment by bdangel1984** [comment]
where is the 6379 from ?  check your config

i used this for geth , and run it at background
geth --rpcaddr "127.0.0.1" --rpcport "8545"   --rpc --rpccorsdomain "*" console --extradata "OpenEthereumPool/WHATEVER" --etherbase 0x...

**Comment by bdangel1984** [comment]
do you have the right version installed ? for both geth and pool

**Comment by lazybtc** [comment]
Geth/v1.6.5-stable-cf87713d/linux-amd64/go1.8.1
The open pool is the one you get from cloning https://github.com/sammy007/open-ethereum-pool.git
I believe is set by default on config for redis  which version is Redis 3.0.6 
Right now what i do to trying to open the pool is
Putty console #1 
geth  --fast --cache=512 console --rpcaddr 45.76.164.212 --rpcport 8983 --rpc --unlock COINBASEADRESS
when that is running 

Putty console #2  I run 
./build/bin/open-ethereum-pool config.json
and get
2017/06/15 03:49:04 Loading config: /root/open-ethereum-pool/config.json
2017/06/15 03:49:04 Running with 1 threads
2017/06/15 03:49:04 Can't establish connection to backend: dial tcp 45.76.164.212:6379: getsockopt: connection refused
2017/06/15 03:49:04 Starting payouts
2017/06/15 03:49:04 Set payouts interval to 2h0m0s
2017/06/15 03:49:04 Starting API on 45.76.164.212:8080
2017/06/15 03:49:04 Set stats collect interval to 5s
2017/06/15 03:49:04 Set purge interval to 10m0s
2017/06/15 03:49:04 Failed to purge stale data from backend: dial tcp 45.76.164.212:6379: getsockopt: connection refused
2017/06/15 03:49:04 Failed to get blacklist from backend: dial tcp 45.76.164.212:6379: getsockopt: connection refused
2017/06/15 03:49:04 Unable to start payouts: dial tcp 45.76.164.212:6379: getsockopt: connection refused
2017/06/15 03:49:04 Failed to get whitelist from backend: dial tcp 45.76.164.212:6379: getsockopt: connection refused
2017/06/15 03:49:04 Policy state refresh complete
2017/06/15 03:49:04 Set policy stats reset every 1h0m0s
2017/06/15 03:49:04 Set policy state refresh every 1m0s
2017/06/15 03:49:04 Running with 8 policy workers
2017/06/15 03:49:04 Upstream: main => 45.76.164.212:8545
2017/06/15 03:49:04 Upstream: backup => http://127.0.0.2:8545
2017/06/15 03:49:04 Default upstream: main => 45.76.164.212:8545
2017/06/15 03:49:04 Error while refreshing pending block on main: Post 45.76.164.212:8545: unsupported protocol scheme ""
2017/06/15 03:49:04 Error while refreshing pending block on main: Post 45.76.164.212:8545: unsupported protocol scheme ""
2017/06/15 03:49:04 Set block refresh every 120ms
2017/06/15 03:49:04 Starting proxy on 45.76.164.212:8888
2017/06/15 03:49:04 Stratum listening on 45.76.164.212:8008
2017/06/15 03:49:04 Failed to fetch stats from backend: dial tcp 45.76.164.212:6379: getsockopt: connection refused
2017/06/15 03:49:04 Error while refreshing pending block on main: Post 45.76.164.212:8545: unsupported protocol scheme ""

I tried intializing geth as you did without --extradata and get the same results
If you could write me on gmail that will be amazing dude and i'm so sorry to bother you but you have my deepest thanks for helping me set this up . Use zeratul600 for that

**Comment by bdangel1984** [comment]
your redis not running at port 6379

**Comment by bdangel1984** [comment]
check it out , after that we will check next problem

**Comment by lazybtc** [comment]
I put on the bash

redis-server

and get the following

Redis 3.0.6 (00000000/0) 64 bit
Running in standalone mode
Port: 6379
PID: 16266

also to make sure of all my listening ports i write on the prompt

sudo netstat -pan | grep LIST

Which gives me

tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1069/redis-server 1
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1085/nginx -g daemo
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1030/sshd
tcp        0      0 127.0.0.1:8545          0.0.0.0:*               LISTEN      16319/geth
tcp6       0      0 :::6379                 :::*                    LISTEN      16511/redis-server
tcp6       0      0 :::80                   :::*                    LISTEN      1085/nginx -g daemo
tcp6       0      0 :::22                   :::*                    LISTEN      1030/sshd
tcp6       0      0 :::30303                :::*                    LISTEN      16319/geth
unix  2      [ ACC ]     STREAM     LISTENING     232401   15050/systemd       /run/user/0/systemd/private
unix  2      [ ACC ]     SEQPACKET  LISTENING     10154    1/init              /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     9788     1/init              /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     9792     1/init              /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     9793     1/init              /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     9804     1/init              /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     10099    1/init              /run/systemd/fsck.progress
unix  2      [ ACC ]     STREAM     LISTENING     12218    1/init              /var/lib/lxd/unix.socket
unix  2      [ ACC ]     STREAM     LISTENING     12226    1/init              /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     12230    1/init              /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     12231    1/init              /run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     12232    1/init              /run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     LISTENING     12238    1/init              /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     14409    1054/iscsid         @ISCSIADM_ABSTRACT_NAMESPACE
unix  2      [ ACC ]     STREAM     LISTENING     257841   16319/geth          /root/.ethereum/geth.ipc

**Comment by bdangel1984** [comment]
try ip 127.0.0.1

**Comment by lazybtc** [comment]
Im running in several putty consoles this
redis-server
geth --rpcaddr "127.0.0.1" --rpcport "8545" --rpc --rpccorsdomain "*" -unlock COINBASEADDRESS console
./build/bin/open-ethereum-pool config.json

this is the content of  my config.json file
{
        "threads": 1,
        "coin": "eth",
        "name": "main",

        "proxy": {
                "enabled": true,
                "listen": "127.0.0.1:8888",
                "limitHeadersSize": 1024,
                "limitBodySize": 256,
                "behindReverseProxy": false,
                "blockRefreshInterval": "120ms",
                "stateUpdateInterval": "3s",
                "difficulty": 2000000000,
                "hashrateExpiration": "3h",

                "healthCheck": true,
                "maxFails": 100,

                "stratum": {
                        "enabled": true,
                        "listen": "127.0.0.1:8008",
                        "timeout": "120s",
                        "maxConn": 8192
                },

                "policy": {
                        "workers": 8,
                        "resetInterval": "60m",
                        "refreshInterval": "1m",

                        "banning": {
                                "enabled": false,
                                "ipset": "blacklist",
                                "timeout": 1800,
                                "invalidPercent": 30,
                                "checkThreshold": 30,
                                "malformedLimit": 5
                        },
                        "limits": {
                                "enabled": false,
 "listen": "127.0.0.1:8008",
                        "timeout": "120s",
                        "maxConn": 8192
                },

                "policy": {
                        "workers": 8,
                        "resetInterval": "60m",
                        "refreshInterval": "1m",

                        "banning": {
                                "enabled": false,
                                "ipset": "blacklist",
                                "timeout": 1800,
                                "invalidPercent": 30,
                                "checkThreshold": 30,
                                "malformedLimit": 5
                        },
                        "limits": {
                                "enabled": false,
                                "limit": 30,
                                "grace": "5m",
                                "limitJump": 10
                        }
                }
        },

        "api": {
                "enabled": true,
                "purgeOnly": false,
                "purgeInterval": "10m",
                "listen": "127.0.0.1:8080",
                "statsCollectInterval": "5s",
                "hashrateWindow": "30m",
                "hashrateLargeWindow": "3h",
                "luckWindow": [64, 128, 256],
                "payments": 30,
                "blocks": 50
        },

        "upstreamCheckInterval": "5s",
"upstream": [
                {
                        "name": "main",
                        "url": "127.0.0.1:8545",
                        "timeout": "10s"
                },
                {
                        "name": "backup",
                        "url": "http://127.0.0.2:8545",
                        "timeout": "10s"
                }
        ],

        "redis": {
                "endpoint": "127.0.0.1:6379",
                "poolSize": 10,
                "database": 0,
                "password": ""
        },

        "unlocker": {
  {
                        "name": "main",
                        "url": "127.0.0.1:8545",
                        "timeout": "10s"
                },
                {
                        "name": "backup",
                        "url": "http://127.0.0.2:8545",
                        "timeout": "10s"
                }
        ],

        "redis": {
                "endpoint": "127.0.0.1:6379",
                "poolSize": 10,
                "database": 0,
                "password": ""
        },

        "unlocker": {
                "enabled": false,
                "poolFee": 1.0,
                "poolFeeAddress": "0xDe4109A7dbA3b5F595268978f10e6DA79E022Bf8",
                "donate": true,
                "depth": 120,
                "immatureDepth": 20,
                "keepTxFees": false,
                "interval": "10m",
                "daemon": "127.0.0.1:8545",
                "timeout": "10s"
        },

        "payouts": {
                "enabled": true,
                "requirePeers": 25,
                "interval": "120m",
                "daemon": "127.0.0.1:8545",
                "timeout": "10s",
                "address": "0x0",
                "gas": "21000",
                "gasPrice": "50000000000",
"autoGas": true,
                "threshold": 100000000,
                "bgsave": false
        },

        "newrelicEnabled": false,
        "newrelicName": "MyEtherProxy",
        "newrelicKey": "SECRET_KEY",
        "newrelicVerbose": false
}

this is what i get when i run ./build/bin/open-ethereum-pool config.json

root@EPS:~/open-ethereum-pool# ./build/bin/open-ethereum-pool config.json
2017/06/15 04:31:52 Loading config: /root/open-ethereum-pool/config.json
2017/06/15 04:31:52 Running with 1 threads
2017/06/15 04:31:52 Backend check reply: PONG
2017/06/15 04:31:52 Starting payouts
2017/06/15 04:31:52 Set payouts interval to 2h0m0s
2017/06/15 04:31:52 Starting API on 127.0.0.1:8080
2017/06/15 04:31:52 Set stats collect interval to 5s
2017/06/15 04:31:52 Set purge interval to 10m0s
2017/06/15 04:31:52 No payees that have reached payout threshold
2017/06/15 04:31:52 Purged stale stats from backend, 0 shares affected, elapsed time 4.134199ms
2017/06/15 04:31:52 Policy state refresh complete
2017/06/15 04:31:52 Set policy stats reset every 1h0m0s
2017/06/15 04:31:52 Set policy state refresh every 1m0s
2017/06/15 04:31:52 Running with 8 policy workers
2017/06/15 04:31:52 Upstream: main => 127.0.0.1:8545
2017/06/15 04:31:52 Upstream: backup => http://127.0.0.2:8545
2017/06/15 04:31:52 Default upstream: main => 127.0.0.1:8545
2017/06/15 04:31:52 Error while refreshing pending block on main: Post 127.0.0.1:8545: unsupported protocol scheme ""
2017/06/15 04:31:52 Error while refreshing pending block on main: Post 127.0.0.1:8545: unsupported protocol scheme ""
2017/06/15 04:31:52 Set block refresh every 120ms
2017/06/15 04:31:52 Starting proxy on 127.0.0.1:8888
2017/06/15 04:31:52 Stats collection finished 7.547688ms
2017/06/15 04:31:52 Stratum listening on 127.0.0.1:8008
2017/06/15 04:31:52 Error while refreshing pending block on main: Post 127.0.0.1:8545: unsupported protocol scheme ""

**Comment by bdangel1984** [comment]
i dont know , maybe you should use go1.7 to compile the pool again

**Comment by bdangel1984** [comment]
you should not to set poolFeeAddress , it will make the coinbase not have enough money to pay after some pays

**Comment by bdangel1984** [comment]
you must set the address for payouts, it's used to pay the miners

**Comment by lazybtc** [comment]
Ok ill try that but can you tell me which exactly commands you use to run the pool?
you connect to your VPS login and then what? please edit any privacy concern info, but i believe that maybe my problem is that im not running the required commands or in the appropiate order

**Comment by bdangel1984** [comment]
use command "screen" for background running

./build/bin/open-ethereum-pool main.json
./build/bin/open-ethereum-pool unlocker.json
./build/bin/open-ethereum-pool payouts.json

**Comment by sammy007** [comment]
This issue tracker is not to teach you. Join gitter if you need assistance.
