### ISSUE TITLE
Price on exchange

### ISSUE THREAD

**Issue by ExEric3** [sammy007/open-ethereum-pool#16]
Is possible add support for latest price on exchnage?

Just example for Ethereum: https://bittrex.com/api/v1.1/public/getticker?market=BTC-ETH

Docs: https://bittrex.com/Home/Api

Others forks should also works.

**Comment by sammy007** [comment]
Maybe later, as an ember service which will use some average price provider.

**Comment by sammy007** [comment]
I will leave it as is for now as a place for competitive add-ons on pool side which can make pool special and attractive.
