### ISSUE TITLE
Can you tell are this settings right? Not seeing any payouts !

### ISSUE THREAD

**Issue by Vangel0v** [sammy007/open-ethereum-pool#161]
#### System information
ethminer.exe -F 52.165.128.189:8888/0xed74609fbb7127b8e6f1920d90731bc6e9f28784/Voltron -G --farm-recheck 200

I see that a payout is send but I didnt receive anything

Your Latest Payouts
Time 	Tx ID 	Amount
16.06.2017 г., 4:12:46 	0x79727692af7968930240e5ceb705c0c031a014b76cb58f49d445f5bd094cf1c2 	0.53704351

There is no trace of that

https://etherscan.io/tx/0x79727692af7968930240e5ceb705c0c031a014b76cb58f49d445f5bd094cf1c2

Etherscan says no record found

Using Jaxx wallet

What am I'm mining ETH or expanse?
My Jaxx wallet is ETH

**Comment by bdangel1984** [comment]
make sure you donot use the test-net

**Comment by Vangel0v** [comment]
This is a test net?
ethminer.exe -F 52.165.128.189:8888

**Comment by alterdev** [comment]
You have give us a lot of data if you ask for help. Specify as the issue format requests: server specs, geth parity client version, CHAIN name that you are mining on. If you are mining ETH on Ropsten chain, or ETC you should not look over etherscan to check transactions. I can tell you that your transaction was maid if you see it in the logs and Redis but you have to check it in the right place.

**Comment by sammy007** [comment]
Find another hobby.
