### ISSUE TITLE
Can't change pool fee

### ISSUE THREAD

**Issue by apollygon** [sammy007/open-ethereum-pool#162]
#### System information

Geth version: 1.6.6-unstable-80f7c6c2

Redis version: Redis server v=3.2.9

OS & Version: Ubuntu 16.04 LTS

#### Expected behaviour
Changing pool fee in config.json is expected to reflect the pool fee on the website. 

#### Actual behaviour
the pool fee is stuck at 1% whatever I change the config file value to.

#### Steps to reproduce the behaviour
Build pool with 3.0 as pool fee in config.json

I have a feeling this is redis related, not my strong suite.

**Comment by sammy007** [comment]
Not expected. Adjust in both places.

**Comment by apollygon** [comment]
Shouldn't {{config.PoolFee}} in index.hbs reflect the pool fee in config? Where else do I change it?

**Comment by sammy007** [comment]
`www/config/environment.js` then build again.

**Comment by apollygon** [comment]
Thanks so much Sammy007
