### ISSUE TITLE
Faster Showing Balance for Miners

### ISSUE THREAD

**Issue by Marow** [sammy007/open-ethereum-pool#164]
My full System works and i can mine.

But i see, that the Balance dont show anything for long time.
Can i make it faster, to show the Balance? And how long does it need to show my balance?

I'm mining now 2 Hours and nothing showing on my miner

**Comment by Marow** [comment]
Dont show anything...  in my Balance on my Server... http://134.255.233.144/#/account/0x785473d9add6dc985c1b4a84a379b6c1792c7107

**Comment by Smit1237** [comment]
[sarcasm]Maybe it's because you din't find anything?[sarcasm]

**Comment by bermudezjuanry** [comment]
@Marow can you help me? i can't run the frontend app, im using kubuntu 16.04
