### ISSUE TITLE
friend

### ISSUE THREAD

**Issue by ping7758** [sammy007/open-ethereum-pool#165]
ETC POOL  Can I use this program, too?  
Is there anything that needs to be modified?
Thank you

**Comment by alterdev** [comment]
At the moment it seems that after the last Ethereum classic geth update 
https://github.com/ethereumproject/go-ethereum/releases 
you can use this pool also for ETC as the RPC of ETC seems closer to ETH. Just change in config eth to have the key clear in Redis. 
It is possible to be affected of 
https://github.com/sammy007/open-ethereum-pool/issues/175
Just have a look also there from time to time, maybe you will encounter same issue. If not you are lucky.
