### ISSUE TITLE
No payments (account is locked)

### ISSUE THREAD

**Issue by jeeweevee** [sammy007/open-ethereum-pool#17]
Hi, 

After I setup the software I found a block but in the separate payment process I see this:

```
2016/05/17 08:47:49 Failed to send payment: account is locked
2016/05/17 08:47:49 Paid total 0 Shannon to 0 of 1 payees
2016/05/17 10:47:49 Payments suspended due to last critical error: account is locked
```

The unlocker also runs in a separate process without errors...how to unlock the account so payments will be send?

**Comment by ExEric3** [comment]
Unlock your coinbase https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts

**Comment by sammy007** [comment]
> how to unlock the account so payments will be send?

Account can be unlocked after reading geth documentation.
