### ISSUE TITLE
Regarding possible ETH mining reward reduction on 8/25

### ISSUE THREAD

**Issue by sammy007** [sammy007/open-ethereum-pool#174]
I suddenly found on reddit that ethereum block reward is reducing tomorrow by 18.5%. I have no idea if it is true or false because communication with ethereum teams was always broken, I see no announcement.

In case it is true you all must adjust block reward in `unlocker.go` https://github.com/sammy007/open-ethereum-pool/blob/master/payouts/unlocker.go#L33

There is further code modification required for smooth transition which takes into account what block height is, but it's also ok to just modify a constant with block reward and restart pool in time right when this transition takes effect. I dont't know if uncle reward formula also changes.

Reminder: I no longer support development of this pool due to lack of funding and donations for more than a year.

**Comment by coinnodenl** [comment]
Thanks for the notification!

**Comment by VeNoMZiTo** [comment]
Thanks!

**Comment by zhoujianwei** [comment]
great job!

**Comment by zhoujianwei** [comment]
maybe is average block time  block raise 18.5% cause  reward reduction

**Comment by sammy007** [comment]
I have no idea, as a pool op you have to follow changes in ETH. Now if there will be reward reduction or increase you know where to make changes.

**Comment by Cu4rach4** [comment]
Hi, and what happens? we need to change on unlock.go?

**Comment by trustfarm-dev** [comment]
Thanks @sammy007 It's great job!

**Comment by sammy007** [comment]
https://github.com/sammy007/open-ethereum-pool/issues/207
