### ISSUE TITLE
Confusing Documentation re: nginx, etc.

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#177]
This is an issue regarding the documentation.  I will post the text and then ask questions. 

```
Configure nginx to serve API on /api subdirectory. Configure nginx to serve www/dist as static website.
Serving API using nginx

Create an upstream for API:

upstream api {
    server 127.0.0.1:8080;
}

and add this setting after location /:

location /api {
    proxy_pass http://api;
}
```

First, it is not clear if the code ("upstream api" and such) is supposed to be for nginx.  Is it?  If so, what file does it go into?  Not everyone is an nginx expert, and also nginx has many ways to configure it.  If the code is not for nginx, where is it for?

Second, please put an explanation in the doc about the difference between the static website and the API.  What do each of them do?

Is there a specific reason to run nginx?  Could an apache2 reverse proxy work instead?

Are you saying that there should be two websites?  one at "domain.com" and one at "domain.com/api" or what?

Lastly, what should be viewable when using the build-in webserver?  When I run it, I only see one page (not one static page and one api page) that says: 
```
Stats API Temporarily Down

Usually it's just a temporal issue and mining is not affected.
```

Thank you for making this more clear.

**Comment by mvilera** [comment]
Normally nginx conf goes on /etc/nginx/sites-available/... there you create or edit an existing file, and create a symlink to ../sites-enabled, the upstream snippet should go outside of the server block, it would be like:

```
upstream api {
    ...
}

server {
    ...
    location /api {
        proxy_pass http://api/;
    }
}
```
I'm pretty sure you can use any kind of reverse proxy for this purpose as it suits your needs.

**Comment by sony87** [comment]
How to create a 2nd pool frontend page - like if i want to host 2 pools on one server, What should be the config in the nginx ?

**Comment by LeChuckDE** [comment]
not a chat plattform !

**Comment by wizzfile** [comment]
to be at github.com you should know.

**Comment by stone212** [comment]
@mvilera thank you but I was not looking for nginx help.  I was looking to understand the documentation.  Documentation should not be specific to nginx.  Instead if we need to set up proxies, the generic instructions should be to serve x and y at points A and B.

Also I do not understand how to run the .go file?  I am just looking for documentation on this project.  I will use apache, not nginx.  I can set up a reverse proxy but I need to know what I must proxy.
