### ISSUE TITLE
I'm getting "Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt:connection refused" error

### ISSUE THREAD

**Issue by emanbayani** [sammy007/open-ethereum-pool#178]
#### System information

Geth version: 1.7.0-unstable

Redis version: 4.0.1

OS & Version: Linux

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````

**Comment by wizzfile** [comment]
[backtrace]

**Comment by LeChuckDE** [comment]
Read the fuc king GETH Manual how to connect by RPC
Not an issue !

**Comment by emanbayani** [comment]
Damn!   Eman Bayani , CSWA, CSWP, CSWPA-DTSr. Mechanical/Design/FEA SolidWorks Engineer
PHONE: (702)538-3430Email: emanbayani@yahoo.comLinkedin: http://www.linkedin.com/pub/eman-bayani/b/613/758

DISCLAIMER: This e-mail contains proprietary information some of which may be legally privileged. It is for the intended recipient only. If an addressing or transmission error has misdirected this e-mail, please notify the author by replying to it. If you are not the intended recipient you may not use, disclose, distribute, copy, print or rely on this e-mail.  Unauthorized disclosure and/or use of information contained or related in this email may result in civil and criminal liability.  Any documents or attachments are proprietary information.  Any signatures on any documents are to be used for the purpose of the attached document only.  Any signed documents, if found unfair, biased, or deceptive will be void and will result in civil and criminal liability.  Any signatures on any attached documents can not be duplicated, used, or copied in any way for any reason and will result in civil and criminal liability.  Any information within attached documents are proprietary.

**Comment by emanbayani** [comment]
Hello,
Anyways, I can't get this work!  I have tried everything!  All I get is:
"Stats API Temporarily DownUsually it's just a temporal issue and mining is not affected."
I like to know what I need to do to get the pool up!?  I dont know if its ember or what but the API will not stream to get miner stats!  Please let me know how to get this to work.
Sincerely,
eman

**Comment by Coinizy1** [comment]
Hi @emanbayani 
run geth by 
geth --rpc

**Comment by Qurmo** [comment]
as @Coinizy1 says run geth
I used ./geth --rpc &
the & at the end makes it run in the background witch does is nice :).
