### ISSUE TITLE
Nicehash connect

### ISSUE THREAD

**Issue by DeadMan993** [sammy007/open-ethereum-pool#179]
When adding a pool to nicehash, an error is generated (Unknown request method mining.subscribe)
Help me fix, I want to buy capacities for my pool

**Comment by DeadMan993** [comment]
When adding a pool to nicehash, an error is generated (Unknown request method mining.subscribe)
Help me fix, I want to buy capacities for my pool

**Comment by LeChuckDE** [comment]
not an issue ...

**Comment by trustfarm-dev** [comment]
refer http://mc.trustfarm.io/

---

 NiceHash  Examples 

stratum+tcp://mc.trustfarm.io:38008 
Username and Password : 0x8dfxxxxxx(Your Wallet Address):# ⇐ Should be use '#' is compatible with open-ethereum pool 

------------

**Comment by sammy007** [comment]
Pool does not support NH stratum.
