### ISSUE TITLE
Run geth

### ISSUE THREAD

**Issue by HelixiR** [sammy007/open-ethereum-pool#18]
hi, 
any other parametrs need to run geth (start node) ?
Currently run like this:
screen -dmS geth geth --rpc --rpcaddr "localhost" --rpcport "8545"

**Comment by eut** [comment]
geth --rpc --unlock <wallet address>  --cache 1024

**Comment by HelixiR** [comment]
If i currently dont use "--unlock [wallet address" what happends? :(

**Comment by Ethash95** [comment]
geth --rpcaddr 127.0.0.1 --rpcport 8545 --rpc --unlock <wallet address>

THEN you have to type the passprhase (the password you set when you have created your coinbase address on the server with geth) 

if you want to automate the unlock process use 

geth --rpcaddr 127.0.0.1 --rpcport 8545 --rpc --unlock <wallet address> --password passwordfile 

where passwordfile is a text file containing the password you set when you have created your coinbase address on the server with geth.

**Comment by HelixiR** [comment]
I create new account in geth.After i sync all blockchain, and now its running without "--unlock [wallet address]" - it's not good? :(

**Comment by Ethash95** [comment]
without unlocking the wallet address the system is not able to process payments

**Comment by HelixiR** [comment]
at this moment i mining on pool 20 hours, so i need restert now with this options? or what i need to do?

**Comment by Ethash95** [comment]
stop geth and restart with correct options

**Comment by HelixiR** [comment]
it somehow affect what has already miners worked 20 hours?

**Comment by Ethash95** [comment]
i dont' think

**Comment by HelixiR** [comment]
Okay, i try, thx.

**Comment by taczc64** [comment]
@Ethash95 can i use console to unlock the address like:personal.unlockAccount(_)

**Comment by Ethash95** [comment]
you must run geth using the following syntax : 
geth --rpcaddr 127.0.0.1 --rpcport 8545 --rpc --unlock [wallet address]

THEN you have to type the passprhase (the password you set when you have created your coinbase address on the server with geth)

if you want to automate the unlock process (to avoid password typing) use

geth --rpcaddr 127.0.0.1 --rpcport 8545 --rpc --unlock [wallet address] --password passwordfile

where passwordfile is a text file containing the password you set when you have created your coinbase address on the server with geth.

**Comment by mikeyb** [comment]
If you use a password file, keep in mind anyone that hacks the server will have the wallet password and can drain funds with ease.

**Comment by taczc64** [comment]
@mikeyb @Ethash95 thank you very much,if i don't use pwd file,  run geth like: geth --rpc --unlock [wallet address], it will print:
Unlocking account 0xxxxxxxxxxx | Attempt 1/3, and still cannot unlock finally, what wrong?

**Comment by Ethash95** [comment]
type the password and press enter :)
