### ISSUE TITLE
Ethereum stratum mining protocol v1.0.0

### ISSUE THREAD

**Issue by jjziets** [sammy007/open-ethereum-pool#181]
I am course to know if there is any plan on implementing Nicehash Ethereum stratum mining protocol v1.0.0
https://github.com/nicehash/Specifications/blob/master/EthereumStratum_NiceHash_v1.0.0.txt

**Comment by Serpent6877** [comment]
https://github.com/bulktrade/open-ethereum-pool

**Comment by sammy007** [comment]
No plans.
