### ISSUE TITLE
parity 1.7.0. with pool

### ISSUE THREAD

**Issue by axelxod** [sammy007/open-ethereum-pool#183]
hi, say please how run parity. What commands i need?
use new parity 1.7.0
try --pruning fast  --author "0x20xxxxxx" --jsonrpc-hosts all --jsonrpc-interface all 
but pool not connected
Error while refreshing pending block on main: Post http://x.x.x.x:8545: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by mikeyb** [comment]
you are in over your head. see https://github.com/sammy007/open-ethereum-pool/issues/87#issuecomment-252503302

You likely wont find any further help beyond this https://github.com/sammy007/open-ethereum-pool/issues/60

**Comment by sammy007** [comment]
Run:

```
parity --warp --author "0x..." --jsonrpc-hosts all
```

Test:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getWork","params":[],"id":1}' http://127.0.0.1:8545
```
