### ISSUE TITLE
Options with GETH

### ISSUE THREAD

**Issue by baocontact** [sammy007/open-ethereum-pool#187]
#### System information

Geth version: `geth version` or commit hash if `develop`
Version: 1.7.0-unstable

Redis version: `redis-server --version`
Redis server v=3.2.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=826601c992442478

OS & Version: Linux/OSX
Debian 9 (Stretch)

#### Expected installation

It's an awesome project, very simple to use. But I have just on stupid question : 
You don't need to launch GETH with "--mine" option to use with open ethereum pool, do you ?

Many thanks for your time,
B.

**Comment by Coinizy1** [comment]
@baocontact  HEy, I am new Did you manage to run and test mining yourself? Because i am not able to submit hash rate from my computer to my open eth pool 
http://35.164.15.22/#/
thanks

**Comment by sammy007** [comment]
Find another hobby.
