### ISSUE TITLE
Receiving wrong stats on Website Current block 1. I use geth with --datadir

### ISSUE THREAD

**Issue by Coinizy1** [sammy007/open-ethereum-pool#189]
Hi, I am receiving this stats on website Frontend.

Network Difficulty: 17.171 G
Network Hash Rate: 1.19 GH
Blockchain Height: 1
Current Round Variance: 0%

Although I am receiving this after running pool command and geth in the background.:

New block to mine at 4709070
Job collection finished etc.

means job collection is working fine I have geth like this:

geth --fast --cache 1024 --maxpeers 40 --mine --minerthreads 2 --rpc --datadir "/chaindata" --etherbase 0x78f5ef9037c158df16980b9e2c155961b215ecb1 --port 30303 --nat any --metrics
please help nobody reply me at gitter.im.
thanks

**Comment by vinhWater** [comment]
I got same issue:
 Network Difficulty: 17.171 G
 Network Hash Rate: 1.19 GH
 Blockchain Height: 1
 Current Round Variance: 0%
@Coinizy1 : Please help me, what solution you closed this issue?

**Comment by ceojazzy** [comment]
Hi let the geth run when it is finished it will be solved automatically.
