### ISSUE TITLE
Anonymous miners

### ISSUE THREAD

**Issue by HelixiR** [sammy007/open-ethereum-pool#19]
I create pool, on my subdomain adress, and closed bot indexing (robot.txt), and only five people know about this pool (link). But alltime i see new workers (miners) on Miners (not my or my friends). Where this people found this pool ? oO

**Comment by mmitech** [comment]
Could be that you or one of your friends is using Claymore miner, is it one of the bellow accounts ? 
- 0x34faaa028162c4d4e92db6abfa236a8e90ff2fc3
- 0x3509f7bd9557f8a9b793759b3e3bfa2cd505ae31
- 0xb9cf2da90bdff1bc014720cc84f5ab99d7974eba
- 0xc1c427cd8e6b7ee3b5f30c2e1d3f3c5536ec16f5
- 0x7fb21ac4cd75d9de3e1c5d11d87bb904c01880fc
- 0xc6f31a79526c641de4e432cb22a88bb577a67eac
- 0xe19ffb70e148a76d26698036a9ffd22057967d1b

**Comment by HelixiR** [comment]
Oh... yup i use Claymore miner. So this new "miners" (adresses) its Claymore dev-donate wallets?
I recheck ur acc list with my.

**Comment by mmitech** [comment]
if it is one of the above accounts then yes it is.
