### ISSUE TITLE
How long for Blocks to move from New Blocks to Immature? 

### ISSUE THREAD

**Issue by Leadspie** [sammy007/open-ethereum-pool#191]
We found 2 Blocks within 30 minutes! with only 5 GH mining  :)
How long for Blocks to move from New Blocks to Immature?

**Comment by mikeyb** [comment]
https://github.com/sammy007/open-ethereum-pool/blob/3ccd90ca1aaeb22a1679434eefc772aa8dce9124/www/app/templates/blocks.hbs#L5

**Comment by Leadspie** [comment]
Thanks Mike, they still there after 8 hours or more. also trying to run ./ether-pool ./unlocker.json
But not there.
Ethereum:~/open-ethereum-pool$ ./ether-pool ./unlocker.json
-bash: ./ether-pool: No such file or directory

**Comment by Coinizy1** [comment]
@mikeyb  Man please just clear my one issue. 
 Miners Online: 1
 Pool Hash Rate: 562.39 MH
 Pool Fee: 0.9%
I have very good Hash Rate. its been running for 6 hours now. I still can't see any money in Current balance why?
thanks

**Comment by mikeyb** [comment]
You set it up wrong.   I didnt write this software, nor do you pay me.  Don't demand things from me.  I would assume if you are having issues running the unlocker like you put in https://github.com/sammy007/open-ethereum-pool/issues/192 then it likely wont pay out.

**Comment by Coinizy1** [comment]
@mikeyb  Any simple help for me will be appreciated.
does i need to found a block to see my current balance?
thanks

**Comment by Leadspie** [comment]
no balance in the front end unless you contributed to finding a block and got paid.

**Comment by Coinizy1** [comment]
Okay once any of my miner did that part all balanced will show or the only
miner which took part in it.
Thanks you sooooo much Man :*

**Comment by Leadspie** [comment]
Yes, look at our pool so that you can see how it will look. https://ethepool.com

**Comment by Coinizy1** [comment]
Thank you sooo much for the link that was all I needed to learn many things.
can you please tell me one more thing who get the reward of finding a block? pool or miner?
thanks @Leadspie

**Comment by Coinizy1** [comment]
What what is your current difficulty in 
proxy": {
		"enabled": true,
		"listen": "127.0.0.1:8888",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 2000000000,
		"hashrateExpiration": "3h",

**Comment by Leadspie** [comment]
I would leave it as default. Someone else may have a better answer.

**Comment by Leadspie** [comment]
you set the reward on the config file. pools gets it and gets distributed. ohhh man, you are in for some  pool learning, it took me a long time to get mine running. I have a friend that  can set it up for you if you need help.

**Comment by Coinizy1** [comment]
For free or paid?
thanks

**Comment by Coinizy1** [comment]
where is reward? i don't see it in config.json
thanks

**Comment by Leadspie** [comment]
open-ethereum-pool/config.example.json  line 85

**Comment by Leadspie** [comment]
nothing in life is free

**Comment by Coinizy1** [comment]
How much for full setup.
thanks

**Comment by Leadspie** [comment]
not sure, you can reach out to him at the pop up chat in https://ethepool.com/ 
his name is JC
