### ISSUE TITLE
Stats API Temporarily Down

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#196]
#### System information

Geth version: Parity 1.9

Redis version: Redis server v=3.2.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=826601c992442478

OS & Version: Debian 9

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
When I visit http://127.0.0.1:8082, I should see some statistics I guess?

#### Actual behaviour

I see this:

```
Stats API Temporarily Down

Usually it's just a temporal issue and mining is not affected.
```

#### Steps to reproduce the behaviour

Install package, run a dev web server for the API, point a miner to the pool, and visit localhost:8082

I can debug this if you can provide some debugging steps?

**Comment by Serpent6877** [comment]
Your nginx config is incorrect somewhere.

**Comment by stone212** [comment]
I am not using nginx.  Only using the development server invoked as:

`ember server --port 8082 --environment development`

After I see this working I will work with a reverse proxy.  (Probably not nginx but anyway.......)

**Comment by Serpent6877** [comment]
User:

ember server --port 8082 --environment production

I had issues when using it in development mode.

**Comment by stone212** [comment]
> ember server --port 8082 --environment production

Two replies:

1) The documentation says to use "ember server --port 8082 --environment development" and that is also true on your fork: https://github.com/Serpent6877/open-ethereum-pool.

2) I tried this and the result is the same.  No change on the web page.  There is a change on the CLI status page.  It gives me a different list of "Slowest Nodes" but I still do not understand this so am not thinking about it.

Maybe if there was some information on how to configure the environment.js?  The comments/documentation is VERY unclear.  I don't know if I do it correct.

**Comment by stone212** [comment]
Does it help to add that when I run an Apache2 reverse proxy, the .go file shows up as a file listing, not an API?  And the other page shows me the footer but nothing in the body of the page.  I do not know if this is helpful information.

**Comment by stone212** [comment]
Is it correct that the "api" section of the config file reads:

```
"api": {
 50                 "enabled": true,
 51                 "purgeOnly": false,
 52                 "purgeInterval": "10m",
 53                 "listen": "127.0.0.1:8080",

```

Line 53 specifically. The use of the localhost is correct I assume? 

Also the environment file:

```
APP: {
      // API host and port
ApiUrl: '//example.net/',
```

How do I specify the port?  I assume I do:

> ApiURL: '//mydomain.net:8080/',

Is that correct?

**Comment by coinnodenl** [comment]
If localhost does not work make it your ip:8080

Your APIurl is correct

**Comment by coinnodenl** [comment]
> Maybe if there was some information on how to configure the environment.js? The comments/documentation is VERY unclear. I don't know if I do it correct.

Just nano the file, then rebuild voila

**Comment by stone212** [comment]
> Just nano the file, then rebuild voila

What do you mean by rebuild?  Do you mean something other than:

`ember server --port 8082 --environment production`

Anyway using nano isn't the problem.  The problem is understanding what all of the variables mean.  The comments are not clear and I wonder if there is some documentation.

> If localhost does not work make it your ip:8080

But that should not matter if I am using "ember server --port 8082 --environment production" correct?

**Comment by Cu4rach4** [comment]
I have the same question...this is the api: http://eth-cl1.apertati.cl/api/stats

Works, but still do not have conection to frontend...i used:

` ApiUrl: 'http://eth-cl1.apertati.cl/api'`

Thanks for your help!

**Comment by Cu4rach4** [comment]
use...just domain, not port!

**Comment by stone212** [comment]
@Cu4rach4 said:

> use...just domain, not port!

Where?  What file?  What line?  We were discussing many possibilities.

**Comment by stone212** [comment]
@coinnodenl 

> Just nano the file, then rebuild voila

Um, no.  I still do not know what to change in the file to make it work.  Also, when you use a word like "rebuild" please be specific.  Do you suggest I do:

> ember server --port 8082 --environment production

Because when the values I have in my files, when I run that command I get the error I opened the Issue for.  

You also said:

> If localhost does not work make it your ip:8080

Where?  On line 53 of config.json, I tried both 127.0.0.1:8080 and <IP>:8080 and the result is the same.

> Your APIurl is correct

**Comment by mikeyb** [comment]
@stone212 you are in over your head. see https://github.com/sammy007/open-ethereum-pool/issues/87#issuecomment-252503302

You likely wont find any further help beyond this https://github.com/sammy007/open-ethereum-pool/issues/60

**Comment by Cu4rach4** [comment]
@stone212...

> Is it correct that the "api" section of the config file reads:
> 
> "api": {
>  50                 "enabled": true,
>  51                 "purgeOnly": false,
>  52                 "purgeInterval": "10m",
>  53                 "listen": "127.0.0.1:8080",
> 
> Line 53 specifically. The use of the localhost is correct I assume?
> 
> Also the environment file:
> 
> APP: {
>       // API host and port
> ApiUrl: '//example.net/',
> 
> How do I specify the port? I assume I do:
> 
>     ApiURL: '//mydomain.net:8080/',
> 
> Is that correct?

Just use the domain, not the port, you redirect internally with nginx.

**Comment by stone212** [comment]
@Cu4rach4  

> Just use the domain, not the port, you redirect internally with nginx.

That is what I was doing before I switched to the dev server, and now I am using the built-in development web server at the moment because I want to eliminate the possibility that the problem is with the reverse proxy.  Clearly it is not because I get the error anyway, using an SSH tunnel and using the local development server.

**Comment by Raja4Shekar** [comment]
Try changing some file in the folder `www/app/templates` and do a build in the `www/` folder i.e run `./build.sh` in `www/` folder.
If you have configured [nginx config](https://github.com/sammy007/open-ethereum-pool/blob/master/misc/nginx-default.conf) file appropriately, together with api module running, then you will get the webpage with required statistics.

**Comment by stone212** [comment]
@Raja4Shekar 

Thank you for replying.

The pool is running, and the reverse proxy has never been a problem.  I am currently not using one because I am testing with "ember server --port 8082 --environment development".

I think this might be the issue:  "together with api module running"

What do you mean by "running" the api module?  I see nothing in the doc about this.  Is there something I should do to make this "run"?

**Comment by Raja4Shekar** [comment]
check this post [#61](https://github.com/sammy007/open-ethereum-pool/issues/61). 
You need to run different instances / module as discussed in the post. 
api module is the one which collects stats to display in the webpage.

**Comment by stone212** [comment]
@Raja4Shekar

I got it working.  I will write it up.  @sammy007 if you want me to update the wiki, please give me access.  If not, that's OK.  I will submit it to you as text.

**Comment by mikeyb** [comment]
Probably best to pull request a new markdown doc called INSTALL.md into https://github.com/sammy007/open-ethereum-pool/tree/master/docs or similar

**Comment by ctapkom** [comment]
@stone212

i have same problem, what you did to fix it?

**Comment by stone212** [comment]
@ctapkom 

Many things, but for this specific issue the most important was to forward port 8080 in addition to the web UI port.  Here was my port forwarding command:

`$ ssh -N -L 8082:localhost:8082 -L 8080:localhost:8080 -L 49152:localhost:49152 username@hostname`

**Comment by stone212** [comment]
I now have a full write-up of how to configure the front-end for private/localhost viewing as well as public web viewing using Apache2 and also using nginx.  I am going to take @mikeb 's suggestion and issue a pull request for a new markdown doc FRONTEND.md.  Closing this issue.

**Comment by honorkeles** [comment]
@stone212 , did you write the document to solve this issue? I checked in docs but couldn’t see it
