### ISSUE TITLE
What are Babel and Concat?

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#197]
#### System information

Geth version: `geth version` or commit hash if `develop`
Parity 1.6

Redis version: `redis-server --version`
Redis server v=3.2.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=826601c992442478

OS & Version: Linux/OSX
Debian 9

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
The Text under "Slowest Nodes" should show me nodes that are connected to my mining pool.

#### Actual behaviour
I do not see any rigs that are connected to the pool.  Instead, I see this when I am running in developement mode:

```
$ ember server --port 8082 --environment development

Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (20)                                    | 1414ms (70 ms)
Concat (8)                                    | 1236ms (154 ms)
```

And I see this when I run in production:

```
$ ember server --port 8082 --environment production

Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
UglifyWriter (1)                              | 29695ms
```

#### Steps to reproduce the behaviour
Fire up ember as follows:

> $ ember server --port 8082 --environment development

**Comment by mikeyb** [comment]
fund in https://github.com/sammy007/open-ethereum-pool/blob/b8a04e1086a9e204f4dbf32a72633e90dfda5210/www/package.json

https://github.com/babel/ember-cli-babel
https://github.com/sir-dunxalot/ember-cli-concat

**Comment by stone212** [comment]
@mikeyb Thank you but this does not answer my question.  I do see that these words are mentioned but I don't know the meaning and I don't see why they are called "Slowest Nodes"

**Comment by mikeyb** [comment]
Those are NOT part of open-ethereum-pool.  They are components ember is running.  Honestly if you are not sure of what the development messages mean when you run that, this is likely way way over your head and you will have even more questions and problems down the road.  This project is not for new or weak hearted.  You will want to understand how to run web applications before trying to run web applications.
