### ISSUE TITLE
Help me Receied unknow response

### ISSUE THREAD

**Issue by vtnplus** [sammy007/open-ethereum-pool#198]
#### System information

Geth version: Parity 1.7

Redis server v=4.0.2 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=59c50c8a2351b110

OS & Version: Ubuntu 16.04 TLS

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````
Hi master. I have problem with mining. report is "Receied unknow response: {”id” : null, “ ”method” : “minning.notifu”, “param” : “.....”",
Where i can fix it

**Comment by sammy007** [comment]
You are using not compatible miner.
