### ISSUE TITLE
go build -o ether-pool main.go gives me this error stat main.go: no such file or directory

### ISSUE THREAD

**Issue by omjanu** [sammy007/open-ethereum-pool#2]
hi i get this error stat main.go: no such file or directory when i type in the command go build -o ether-pool main.go in ubuntu 14.04 so please help to fix this problem 

thank you

**Comment by sammy007** [comment]
mkdir ~/go
    export GOPATH=$HOME/go

**Comment by scorpio18** [comment]
you need to  run that command on open-ethereum-pool folder , the error state that go can't find the file main.go because you run the command on the wrong folder

**Comment by sammy007** [comment]
Thanks @scorpio18, tbh I googled a lot and found only an issue with GOPATH.

**Comment by scorpio18** [comment]
You dont need to set gopath to run that command , you need to set it just when you need to run those commands 
go get github.com/ethereum/ethash
go get github.com/ethereum/go-ethereum/common
go get github.com/gorilla/mux
go get gopkg.in/redis.v3
go get github.com/yvasiyarov/gorelic

By the way thanks for this nice soft , i just made a pool with it ;)

**Comment by sammy007** [comment]
https://github.com/sammy007/open-ethereum-pool/commit/3386a4bf74873eec09049741b5cacd31dbaa097e

**Comment by omjanu** [comment]
The link for go get github.com/ethereum/go-ethereum/common 

Says page not found so what should i do

**Comment by sammy007** [comment]
<code>go get github.com/ethereum/go-ethereum/common</code> works for me.

**Comment by omjanu** [comment]
Try to go to the page it is not working

**Comment by sammy007** [comment]
You should not go to the page, this is command you must execute <code>go get ...</code>.

**Comment by omjanu** [comment]
Type in the url and it give me page not found but when i go to try other links i see the github page

**Comment by omjanu** [comment]
I did and then when i do the go build -o ether-pool main.go it gives me this error stat main.go: no such file or directory

**Comment by scorpio18** [comment]
You need to run this command go build -o ether-pool main.go on open-ethereum-pool folder

**Comment by omjanu** [comment]
Can you tell me how do i go to the folder

**Comment by scorpio18** [comment]
after you git clone https://github.com/sammy007/open-ethereum-pool.git  , cd open-ethereum-pool  and run the command

**Comment by omjanu** [comment]
Ok thanks

**Comment by omjanu** [comment]
Ok so i got that done but now when i type in ./ether-pool config.json it give me the error that
-bash: ./ether-pool: No such file or directo
ry

**Comment by omjanu** [comment]
So what should i do
