### ISSUE TITLE
Stats API Temporarily Down

### ISSUE THREAD

**Issue by sdabbs** [sammy007/open-ethereum-pool#20]
Stats API Temporarily Down when using a samsung mobile phone .
then when i go back to the website it has crashed. 
Livereload server on http://localhost:49152
Serving on http://localhost:81/

Build successful - 3945ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 459ms
SourceMapConcat: Concat: Vendor /assets/ve... | 259ms
JSHint app- QUnit                             | 227ms
BroccoliMergeTrees: ember-cli-qunit: treeF... | 222ms
Babel                                         | 212ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (18)                                    | 1615ms (89 ms)
TemplateCompiler (2)                          | 280ms (140 ms)
SourceMapConcat: Concat: Vendor /asset... (1) | 259ms
JSHint app- QUnit (1)                         | 227ms
BroccoliMergeTrees: ember-cli-qunit: t... (1) | 222ms

**Comment by sammy007** [comment]
Check how to configure `www/config/environment.js` in README. Livereload is for development only. Build static website for production gigs. Ask for help in gitter, not in issue tracker.
