### ISSUE TITLE
Pool at Current Round Variance: 203% with 10.5 GH

### ISSUE THREAD

**Issue by neurans** [sammy007/open-ethereum-pool#200]
Is it normal that a Pool at Current Round Variance: 203% with 10.5 GH has not found a block in 10 days?

**Comment by indiealexh** [comment]
Mining is a lottery, Ive gotten up to 600% Variance on occasion.
Higher hash-rate increases your chances to find a block, but doesn't guarantee it.

**Comment by etherninja** [comment]
My record is 1300% Variance is a btch
