### ISSUE TITLE
Payouts with Parity?

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#202]
#### System information

Parity 1.6.10

Redis version: Redis server v=3.2.6

OS & Version: Debian 9

Commit branch and hash: ? (used git clone https://github.com/sammy007/open-ethereum-pool.git)

#### Expected behaviour

When a miner specifies an address to recive payment at, this address should be rewarded.

#### Actual behaviour

Only the *author* address specified by the Parity instance on the server running open-ethereum pool is credited.

#### Steps to reproduce the behaviour

Run this thing on Parity.

I read the Wiki that says payouts may not work.  Has anyone had success with this?  Is this something we can all work on fixing together?

**Comment by sammy007** [comment]
Payout node must be unlocked. Mining node can be another node with only `author`.

**Comment by stone212** [comment]
@sammy007 I do not understand what you are saying. 

> Payout node must be unlocked.

There is no "payout node" but I created a new node, and I added the key to this node.  So I have a miner that has a local.conf file that lists a key.  A node is running that has this key.  When I invoke Parity on the node, I invoke with "--author <key>".  Is this what you mean?

> Mining node can be another node with only author.

What do you mean by "mining node" here?  What is this term?

**Comment by stone212** [comment]
> Payout node must be unlocked. Mining node can be another node with only author.

If I understand these statements, then I have this configuration.  Payouts are not working.  I'm not sure why the issue is closed as the problem is still there.

**Comment by sammy007** [comment]
Because it works for everyone but you and you can't post logs where we can see errors.

**Comment by sammy007** [comment]
And config indeed.

**Comment by stone212** [comment]
@sammy007 

>  you can't post logs where we can see errors.

Why do you say this?  I can post whatever you ask for.

> And config indeed.

What does this statement mean?

**Comment by sammy007** [comment]
Need payout logs and a config of your pool. It's strange that I have to explain it to devops. You said it does not work for you, so give me materials for evidence.

**Comment by mikeyb** [comment]
OMFG!  Ask a developer.  This is for ISSUES with the code.  Not ISSUES for your inability to use software.

I have said it and Sammy has said it.  This stuff is all kindergarten material.  If you don't understand any of your problems, you need to go google these skills.  We are not here to teach you about software, read the docs, read the source code, but stop complaining about the same shit.  You obviously dont understand web development, so move on.  Nobody wants to use a pool where the owner has no clue how to run it.  Running a pool is not something you do for fun, it is a serious job and requires serious skills.

**Comment by mikeyb** [comment]
So it is assumed you are setting this up for a token you are trying to launch.  This is scary for a few reasons.

You are launching a token network https://bitcoingarden.org/forum/index.php?topic=21165.0

So not only are you unable to run a pool, you are trying to run a token network (with a 12% premine, jeezus is this 2014 again? scam).  

You are already issuing tokens and you dont even have a whitepaper.  You "launch" in 8 days even with no software ready for users.  You make it blatantly obvious you guys are just trying to do a quick dump of premine tokens on exchanges.

Go Away!

**Comment by stone212** [comment]
@mikeyb Do you think that I am associated with the link you sent?  You continue to jump to incorrect conclusions.  I thought it was only related to me, but it is apparently how your mind works.  I am responding to be on record as saying that the link you sent is the first time I have heard of that thing and I am not associated with it.

**Comment by stone212** [comment]
@mikeyb 

> This is for ISSUES with the code.

That is only partially correct.  This is for issues with the *project* and that includes documentation, correct terminology, etc.

**Comment by stone212** [comment]
@sammy007 

> Need payout logs and a config of your pool.

I am happy to provide these.  Where will I find "payout logs"?  The config is obviously config.json.  Part of the clarity I am attempting to help with.  Instead of saying "And config indeed" which means nothing in English, it could work to say "please post config.json file".  No confusion!

**Comment by mikeyb** [comment]
Dude I have been watching this project for a long time.  You are the only person who does not get it in that time.  Just stop.  If by some fucking miracle you get this software to run, I highly fear anyone use it because you have no idea what you are doing in software development.

You simply don't get it.  IT IS ONLY YOU THAT DOESNT GET IT!!!  Stop bugging a developer for your lack of knowledge, sammy is not here to hold your incompetent hand while running financial services.  Grow up

**Comment by mikeyb** [comment]
Simply ridiculous

![image](https://user-images.githubusercontent.com/36461/31998900-4d8f3078-b946-11e7-9ebd-84255fd213d4.png)

**Comment by mikeyb** [comment]
For the record and perspective.

In 18 months of issues for this repo, you have created 4% of the issues in 30 days.  That is a problem.  Especially considering all issues you have created are end user issues and not a single thing to do with this repo.

**Comment by stone212** [comment]
@mikeyb 

You have an interesting perspective.  I'm quite proud of the screenshot you posted, and the fact that I am creating issues is hardly something I consider a proboem.  I call it a contribution, especially since most of the issues are related to documentation and I am creating and offering corrected versions as I find the problems.  

But let's stop wasting this thread on back and forth and try to keep the discussion to the Issue.  Do you have a contribution to make to the Issue/ticket?

**Comment by mikeyb** [comment]
I just wish I could block your emails from coming in.  Cheers
