### ISSUE TITLE
music coin pool block reward not showign 314 after change alos

### ISSUE THREAD

**Issue by bapparabi** [sammy007/open-ethereum-pool#204]
hi sir i am running music coin pool http://drowningpool.net/ but the block value is not showing as 314 and also miner not getting correct share . as right now its showing 5 but it suppose to show 314 . i have already modified in payouts/unlocker.go as .

and then i use ./build

but still its not showing in pool front ends and also miner not getting correct share and it work as 5 value not 314

Can any one provide solution

Original:

var constReward = math.MustParseBig256(“5000000000000000000”)
var uncleReward = new(big.Int).Div(constReward, new(big.Int).SetInt64(32))

// Donate 10% from pool fees to developers
const donationFee = 10.0
const donationAccount = “0xb85150eb365e7df0941f0cf08235f987ba91506a”

Changed file:

var constReward = math.MustParseBig256(“314000000000000000000”)
var uncleReward = new(big.Int).Div(constReward, new(big.Int).SetInt64(32))

// Donate 10% from pool fees to developers
const donationFee = 0.0
const donationAccount = “”

**Comment by sammy007** [comment]
Offtopic.
