### ISSUE TITLE
Error while refreshing block template on main: etherbase missing: etherbase address must be explicitly specified

### ISSUE THREAD

**Issue by Qurmo** [sammy007/open-ethereum-pool#205]
Ok I must be looking over it, but I get the error mentioned above.  

But I can't see anywhere in the config.json file a line where they ask me my general account info (wallet adress, pswd).

is their an #IRC channel where we can talk about stuff like this?  This isn't really an "issue" but more a user prob.

Edit: after a good night sleep it came clear to me... I hadn't create a wallet yet.  so ignore this question, I do remain interested on an #IRC chan or anything like that

**Comment by xstalpha** [comment]
same interest in irc chat. im at the same error as you but figured it was needing a geth wallet. soon as geth synchs ill make one and see whats up

**Comment by mikeyb** [comment]
There is a gitter for chatting with other users

**Comment by xstalpha** [comment]
oh man just looked it up that's sweet. 

https://gitter.im/ethereum-mining/ethminer
