### ISSUE TITLE
Parity Payouts?

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#209]
I have to re-open this issue because it was closed before it was resolved.  I have added some details to make it useful:

#### System information

Parity 1.6.10

Redis version: Redis server v=3.2.6

OS & Version: Debian 9

Commit branch and hash: ? (used git clone https://github.com/sammy007/open-ethereum-pool.git)

#### Expected behaviour

When an EthOS miner specifies an address to receive payment at in the local.conf file, the address should be rewarded for the miner's efforts.

#### Actual behaviour

The only address that receives any ether is the one that is unlocked on the Parity node that is on the same computer that the mining pool is on.  The miner and the node it works with do not receive the ether.

#### Steps to reproduce the behaviour

1. Run this thing on Parity, unlocking an account.

2. Run another node, unlocking the account you want the ether to go to.

3. Run an EthOS mining rig, and specify the account from #2 in the local.conf file.

**Comment by mikeyb** [comment]
see https://github.com/sammy007/open-ethereum-pool/issues/196#issuecomment-335018515

**Comment by sammy007** [comment]
Lack of understanding how system works is not an issue, the gitter (link in readme) is more appropriate place where you can ask people to teach you.

**Comment by stone212** [comment]
@sammy007 I think you misunderstand, maybe because of the English?  I am not asking anyone to teach me.  If we're being honest, I probably have more experience than you and @mikeyb combined.  What I am looking to do is to collaborate with you to fix the many code and documentation errors in this project - as any project has.  You don't seem open to collaboration, so I wonder why you post your project on GitHub?  @mikeyb in particular seems to get very nervous and defensive.  I actually wanted to hire one of you to work on my mining project, but you seemed to be done with this code, and I'm not sure he's old enough to work.  (Is he?  Seems like he might be too young?)

Anyway, you made a suggestion so I searched this page for the phrase "gitter": https://github.com/sammy007/open-ethereum-pool/blob/master/README.md

It does not have the word "gitter" in it.  If there is a link you think is worth sharing, please send it.

**Comment by sammy007** [comment]
You must have a node with a private key for the wallet with block rewards. This address must be unlocked in order to process payouts by pool https://github.com/sammy007/open-ethereum-pool/wiki/Ethcore's-Parity. You must NEVER expose node to the wild because attackers can drain your wallet. All I can say.

**Comment by stone212** [comment]
@sammy007 thank you for replying but as I state in my original ticket, I already have those things.

I have one node running parity on a private network with an unlocked account.  This node has your mining pool software running on it as well.

I have an EthOS miner pointed to the open ethereum pool.  when the EthOS miner is configured to send payouts to the same address that is unlocked on the original node, the address receives the payouts.  But this is not useful because many miners must be able to connect, each owned by a different person, each with a different account.

The doc you sent (https://github.com/sammy007/open-ethereum-pool/wiki/Ethcore's-Parity) is very useful in the first situation, but that situation everything is working fine already.  I had that working within five minutes.  But that was weeks ago, and I still do not know how to allow multiple miners to be paid out to multiple addresses.

That is what I mean by "Payout" but maybe I am using the word incorrectly?

**Comment by sammy007** [comment]
Every miner will be paid in a loop after reaching configured balance threshold.

**Comment by stone212** [comment]
Interesting.  Can you tell me what "configured balance threshold" means?  Is this a parameter in one of the config files?  Because I have had the miner running for more than a week and it has not paid out.

**Comment by sammy007** [comment]
There is a threshold option in payouts section of the config file https://github.com/sammy007/open-ethereum-pool/blob/master/config.example.json#L106

**Comment by stone212** [comment]
@sammy007  I have changed the limit to 50 (for testing only) and it works!  Thank you!

This is fantastic.  I would not have guessed this is what "threshold" refers to in a long time of trying.  If you decide that you are interested in this project again in the future, I would be willing to help you write some more doc.  For example, every parameter in the config deserves a plain explanation.  Just for an example of what I mean:
http://www.postfix.org/postconf.5.html

It would certainly save you a lot of time, replying to questions that seem very basic to you. :)

**Comment by stone212** [comment]
@sammy007 

> You must NEVER expose node to the wild because attackers can drain your wallet. All I can say.

Thank you for this warning.  I would never do that.  But I mention it here so other people who are not admins do not make this mistake.  In fact, it is not necessary to have '"--jsonrpc-hosts="all"' in the command line for payouts to work.  I have this working and do not expose the RPC publicly.

**Comment by stone212** [comment]
@sammy007  I have changed the limit to 50 (for testing only) and briefly I thought it was working, but that was my mistake.  The "author" account and the account to send payouts to looked similar that I mistakenly thought the correct one was being paid.

I have lots of specifics here and I hope that is helpful.

I have the exact configuration I describe in the ticket, and "threshold" is set to 50 in config.json.  The node that the pool is on is connected to the node that the payee address is on.  The EthOS miner is using the payee address.  In fact, I get messages like this when the pool is running:

```
2017/10/18 08:05:59 Broadcasting new job to 1 stratum miners
2017/10/18 08:05:59 Jobs broadcast finished 21.47µs
2017/10/18 08:05:59 Inserted block 328 to backend
2017/10/18 08:05:59 Block found by miner 0x00c8208328857b4d82fcfc365bf8c2cc3442ce92@63.142.222.128 at height 328
2017/10/18 08:05:59 Valid share from 0x00c8208328857b4d82fcfc365bf8c2cc3442ce92@63.142.222.128
2017/10/18 08:06:04 Stats collection finished 26.688165ms
2017/10/18 08:06:09 Stats collection finished 34.708201ms

```

This seems great, right?  But all of the payouts go to the *author* wallet that is on the mining pool node.

0x00c8208328857b4d82fcfc365bf8c2cc3442ce92 (shown above) is absolutely the correct *payee* account, and there is another node on the network that *can* communicate with the node that the mining pool is on.  That node is running with the *payee* account in "unlock" mode.

I have successfully done a manual transfer of 100(fake)ETH from the *author* account on the pool node to the *payee* account on the other node.

Here are some things that might help get to the root of the problem:

* I know I said earlier (but below) that jsonrpc-hosts="all" is not necessary.  Was I incorrect about that?  Do payouts happen using the RPC port?  That cannot be correct?  Anyway I am testing this now with "--jsonrpc-hosts=all" but it is still not happening.  And that is good!  Because RPC cannot be open publicly.  the transfer must happen by writing to the blockchain?

* On this page (https://github.com/sammy007/open-ethereum-pool/wiki/Ethcore's-Parity) you say "The --no-signer option is mandatory" but "--no-signer" is not a Parity config option.  (Reference: https://github.com/paritytech/parity/wiki/Configuring-Parity)

* There does not need to be any direct connection between the *payee* wallet and the pool I assume?  Only through the blockchain, correct?

**Comment by stone212** [comment]
@sammy007 BTW - check your ETH balance. :)
