### ISSUE TITLE
ethminer-genoil

### ISSUE THREAD

**Issue by jeeweevee** [sammy007/open-ethereum-pool#21]
Hi there, 

Some miners want to use [ethminer-genoil](https://github.com/Genoil/cpp-ethereum) stratum software. However they get the following:

Command: `ethminer -G -S 192.168.2.3:3334 -O 0xdb0d361cd4972510168ef0f67eca0d32d6bb129d:x`

> =====================================================================
> Genoil's ethminer 0.9.41-genoil-1.1
> =====================================================================
> Found suitable OpenCL device [Tahiti ] with 3221225472 bytes of GPU memory
>   i  19:24:52|main  Connecting to stratum server 192.168.2.3:3334
>   i  19:24:52|stratum  Connected to stratum server 192.168.2.3 : 3334
>   i  19:24:52|stratum  Starting farm
>   i  19:24:52|stratum  Subscribed to stratum server
>   i  19:24:52|stratum  Worker not authorized: 0xdb0d361cd4972510168ef0f67eca0d32d6bb129d
>   i  19:24:52|stratum  Disconnecting
>   i  19:24:52|stratum  Stopping farm
> 
>   
>   
> =====================================================================
> open-ethereum-pool
> =====================================================================
> 2016/05/26 00:24:52 Unknown RPC method: &{0xc8202d01c0 mining.subscribe 0xc8202d01e0 }
> 2016/05/26 00:24:52 Unknown RPC method: &{0xc820494760 mining.authorize 0xc820494780 }

Is it possible to edit the open-ethereum-pool software to support these kind of RPC calls?

**Comment by sammy007** [comment]
Not yet, maybe never. I am not a big fan of stratums fragmentation.

**Comment by Genoil** [comment]
Me neither, that's why I implemented the stratum client following the specification (https://docs.google.com/document/d/17zHy1SUlhgtCMbypO8cHgpWH73V5iUQKk_0rWvMqSNs/edit?hl=en_US). 

What you did looks like Dwarfpool's stratum implementation, right? (Dwarfum ;-)

**Comment by clintar** [comment]
Does that doc really explain what was implemented? Isn't that just a generic stratum doc?

**Comment by sammy007** [comment]
@clintar There is no such thing as stratum spec, all coins are different. Before ETH stratum rush there were several stratum implementations, sgminer, cpuminer, etc. Several stratums from Bitcoin ASICS manufacturers. Stratum is JSON-RPC over TCP and since all stratum implementations for now is just a eth_getWork over TCP and the difference is just a different messages. Initial dwarf's dialect looking good for me so i took it. The rest of pools just tried to lock several miner forks to their own pools.

**Comment by clintar** [comment]
Right, that's what I understood. Just wondered why he posted that doc?

**Comment by davembg** [comment]
@sammy007 @clintar 
It started here: https://slushpool.com/help/#!/manual/stratum-protocol
It makes a pretty good case for some effort to be made for consistency with all ETH pools.
But, none of them can agree, it seems.

**Comment by clintar** [comment]
I've already got an implementation that works for every miner, works on testnet fine, but when I tried to go live with it, my variance went to like 630% so I disabled that code. I have a testnet version running at [http://eth-testnet.cncoin.farm/](eth-testnet.cncoin.farm) for testing, and it works fine, but I don't know enough about this to know if there could be some issue with live net.

**Comment by sammy007** [comment]
Well, `docs/STRATUM.md` is published more than week ago and another impl. does not make sense so far. If someone need a miner to work with it, there is more than enough reading.

**Comment by davembg** [comment]
@sammy007 You make my point exactly - nobody can agree who's "right" or will support a standard for ETH. Instead, you have to use different miners and/or proxies for each pool. Personally, I support Genoil.
Claymore has a good miner, but, not open-source.

**Comment by clintar** [comment]
Genoil support this stratum version now, FYI

**Comment by Genoil** [comment]
Yeah after nicehash chipped in with a third spec, I decided to stop being anal about it and made a total mess out of my stratum clients. But now it supports all three strata. If that's the correct plural.

**Comment by sammy007** [comment]
@Genoil thanks that you did it in correct way, I believe that miners should support stratum protos, not pools.

**Comment by stone212** [comment]
@sammy007 In 2016 you said `Not yet, maybe never. I am not a big fan of stratums fragmentation.` about supporting the mining.subscribe method for Stratum.

I think EthOS version 1.3.3 just released defaults to mining.subscribe for ethminer.  I don't know if that changes your opinion.
