### ISSUE TITLE
Small question about how to see how much my pool will get (1.5%) from all miners

### ISSUE THREAD

**Issue by Coinizy1** [sammy007/open-ethereum-pool#210]
I want to see my total profit at 1.5% from all miners (total earnings from all miners).
What i want to do is, i want to see how much fee (earnings) my pool is making with each miner. something like
All.model.stats.balance x 1.5 (fee) / 100 = Pool profit. ( This is just an example i want to know how can i get this done just guide me to direction thanks)
Thanks

**Comment by mikeyb** [comment]
this is not an issue, this is a feature request.  The code is open source you can add what you need.  If you don't know how you should look at hiring someone who does, check Upwork

**Comment by Coinizy1** [comment]
Mano people dont even know what type of code is this.  Many people are
asking too much for this and more then 2 already scammed me and destroyed
my server.  I am ready to pay Sir please tell me how much is needed for
this i know you can do this because you are good in this i read all the
issues and you answered many of them
Thanks

**Comment by Coinizy1** [comment]
I just want to see how much my will pool will get if there are 10 miners at the moment and total speed of my pool is 10 gh/s or th/s whatever the common one is.
Can you give me some hint which type of developer is needed for this job and where he will code (file name)
Thanks

**Comment by sammy007** [comment]
You can use mining calculator and check your `feeAddress` on a pool also. This is enough, if you need more you are wrong.
