### ISSUE TITLE
Mining client error

### ISSUE THREAD

**Issue by oliverfiendson** [sammy007/open-ethereum-pool#214]
#### System information
Geth version: 1.7.2
Redis version: 3.0.6
Go version:1.7.3
Node version:4.2.6
Other:Tutorial settings
OS & Version: ubuntu 16.04 LTS
=========================================================
claymore 9.7  warning...
"miner detected that you use local pool or local stratum proxy
this mode is not currently supported and will cause more stale shares"

**Comment by oliverfiendson** [comment]
open-ethereum-pool process prompts:
Valid share form 0xXXXXXXXXXXXXXXXXXXXXXXX@XXX.XXX.XXX.XXX

**Comment by sammy007** [comment]
It's a bullshit to attract dumbasses to mine on public pools where dev of the miner getting shares.

**Comment by oliverfiendson** [comment]
How can i correct this error? Now share is invalid

**Comment by Raja4Shekar** [comment]
It is not an error, it is an information which just says that the pool that you are connect is not generally used pool (as it is privately hosted by you).

**Comment by oliverfiendson** [comment]
How can i allow my server to support stratum? Thank you

**Comment by Raja4Shekar** [comment]
Try with the additional option 
-allpools 1
example:
ethdcrminer64 -epool ethereum.miningcryptopools.com:8008 -ewal 0x42aC84E310C6e9cA9eD968597FD0d023d9CA19f3 -eworker myfarm -allpools 1

**Comment by oliverfiendson** [comment]
I think this should be the problem of pool, your pool is not such a problem?

**Comment by Raja4Shekar** [comment]
No, its not the problem with the pool, it is due to the client that you are using. Try [https://github.com/ethereum-mining/ethminer](url). Use the stable version.

**Comment by Raja4Shekar** [comment]
No, its not the problem with the pool, it is due to the client that you are using. Try [https://github.com/ethereum-mining/ethminer](url). Use the stable version.

**Comment by oliverfiendson** [comment]
Thank you my friend, I will try it.
