### ISSUE TITLE
Running Pool

### ISSUE THREAD

**Issue by kee4834** [sammy007/open-ethereum-pool#215]
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````
Hi,All,how do I setup running pool,thanks in advance

Running Pool
./build/bin/open-ethereum-pool config.json
You can use Ubuntu upstart – check for sample config in upstart.conf.

**Comment by sammy007** [comment]
https://github.com/sammy007/open-ethereum-pool/blob/master/misc/upstart.conf
