### ISSUE TITLE
Duplicate payments to the same address twice

### ISSUE THREAD

**Issue by SeekWorld** [sammy007/open-ethereum-pool#216]
#### System information

Geth version: geth  1.7.3

Redis version: 3.0.6 

OS & Version: Ubuntu 16.04.2 LTS

Commit branch and hash: (`master`, `ba60e1c`)
master
When the Payout node show the error massage：
`Failed to send payment to 0x899ee5a2474966b39dd83eed6435ef4802821233, 397447848 Shannon: Post http://10.0.12.18:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Check outgoing tx for 0x899ee5a2474966b39dd83eed6435ef4802821233 in block explorer and docs/PAYOUTS.md`

I press CTRL+C and run` RESOLVE_PAYOUT=1 ./build/bin/open-ethereum-pool config.json`
then show this massage:
```
   Running with env RESOLVE_PAYOUT=1, now trying to resolve locked payouts
2017/10/19 08:57:22 Will credit back following balances:
        Address: 0x899ee5a2474966b39dd83eed6435ef4802821233, Amount: 397447848 Shannon, 2017-10-19 08:52:14 +0800 CST
2017/10/19 08:57:22 Credited 397447848 Shannon back to 0x899ee5a2474966b39dd83eed6435ef4802821233
2017/10/19 08:57:22 Payouts unlocked
2017/10/19 08:57:22 Now you have to restart payouts module with RESOLVE_PAYOUT=0 for normal run
```
I press CTRL+C and run `RESOLVE_PAYOUT=0 ./build/bin/open-ethereum-pool config.json `

It looks normal, but not ! that address's still have same Pending Balance, and the payouts node will pay for it again !

**Comment by SeekWorld** [comment]
My Payouts Node  server is running independently，ip:10.0.12.12, only install and run the open-ethereum-pool, payouts module:

`{
        "threads": 2,
        "coin": "eth",
        "name": "payouts",

        "proxy": {
                "enabled": false,
                "listen": "0.0.0.0:8888",
                "limitHeadersSize": 1024,
                "limitBodySize": 256,
                "behindReverseProxy": false,
                "blockRefreshInterval": "120ms",
                "stateUpdateInterval": "3s",
                "difficulty": 2000000000,
                "hashrateExpiration": "3h",

                "healthCheck": true,
                "maxFails": 100,

                "stratum": {
                        "enabled": true,
                        "listen": "0.0.0.0:8008",
                        "timeout": "120s",
                        "maxConn": 8192
                },

                "policy": {
                        "workers": 8,
                        "resetInterval": "60m",
                        "refreshInterval": "1m",

                        "banning": {
                                "enabled": false,
                                "ipset": "blacklist",
                                "timeout": 1800,
                                "invalidPercent": 30,
                                "checkThreshold": 30,
                                "malformedLimit": 5
                        },
                        "limits": {
                                "enabled": false,
                                "limit": 30,
                                "grace": "5m",
                                "limitJump": 10
                        }
                }
        },

        "api": {
                "enabled": false,
                "purgeOnly": false,
                "purgeInterval": "10m",
                "listen": "0.0.0.0:8080",
                "statsCollectInterval": "5s",
                "hashrateWindow": "30m",
                "hashrateLargeWindow": "3h",
                "luckWindow": [64, 128, 256],
                "payments": 30,
                "blocks": 50
        },

        "upstreamCheckInterval": "5s",
        "upstream": [
                {
                        "name": "main",
                        "url": "http://10.0.12.18:8545",
                        "timeout": "10s"
                }
        ],

        "redis": {
                    "endpoint": "10.0.12.4:6379",
                   "poolSize": 10,
                   "database": 0,
                   "password": ""

        },

        "unlocker": {
                "enabled": false,
                "poolFee": 1.0,
                "poolFeeAddress": "",
                "donate": false,
                "depth": 120,
                "immatureDepth": 20,
                "keepTxFees": false,
                "interval": "10m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s"
        },

        "payouts": {
                "enabled": true,
                "requirePeers": 3,
                "interval": "4h",
                "daemon": "http://10.0.12.18:8545",
                "timeout": "30s",
                "address": "0xo9cF7b0cA665AB4u91DA0aaa7bb3b0686F32abcde",
                "gas": "21000",
                "gasPrice": "50000000000",
                "autoGas": true,
                "threshold": 50000000,
                "bgsave": false
        },

        "newrelicEnabled": false,
        "newrelicName": "MyEtherProxy",
        "newrelicKey": "SECRET_KEY",
        "newrelicVerbose": false
}`

**Comment by sammy007** [comment]
Hint:

```
Failed to send payment to 0x899ee5a2474966b39dd83eed6435ef4802821233, 397447848 Shannon: Post http://10.0.12.18:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers). Check outgoing tx for 0x899ee5a2474966b39dd83eed6435ef4802821233 in block explorer and docs/PAYOUTS.md
```

i suppose you have no clue what you are doing, please consider shitting down your service.

**Comment by SeekWorld** [comment]
OMG now I know what did I do ! thank you sammy007 !
