### ISSUE TITLE
Donation Address

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#217]
<deleted>

**Comment by sammy007** [comment]
I will only patch pool for upcoming hard forks, no new features. Also can't teach people, this pool really requires 15 minutes to install, people need to dig for missing knowledges. There is a chat with people https://gitter.im/sammy007/open-ethereum-pool if needed. And yes, address is still good.

**Comment by stone212** [comment]
@sammy007 Glad that the address was the correct one.  And if you change your mind and want to earn some more, you can contact me and I can arrange that.  It's easier than paying someone to fork and document the project, and I am too busy to learn to read go code.
