### ISSUE TITLE
"Don't use built-in web server in production."

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#218]
On the wiki, it says:

> Don't use built-in web server in production.

Does this mean that ember should not be used at all, or only that it should be invoked with the "production" flag and not "development"?  In that case, it might be changed to read:

> Don't use web server in development more on a production site.  Use the production flag and a properly configured reverse proxy instead.

I assume that ember must be invoked, even for a production version of the website.  There are so many config options in www/config/environment.js, and you mention reverse proxies.  So there must be the ember server running in order to proxy something.

**Comment by sammy007** [comment]
Ember is a framework it generates static website and internal web server is only for development. If you follow readme you will end up with a static website in `www/dist` directory. You must serve it via web server of your choice and also proxy api so this website will be able to talk to it. I am not going to cover every aspect of system deployment here, it's a software and admins with basic knowledges must be able to run it, and they do.

**Comment by stone212** [comment]
@sammy007 Yes, this makes sense thank you.  The build.sh builds the site from the production variables, and then you server that separately.  This is another thing that could go in the doc.  I will add it to mine, and share when it is complete if you choose to use it.
