### ISSUE TITLE
Inquire about default settings

### ISSUE THREAD

**Issue by mvilera** [sammy007/open-ethereum-pool#219]
Hey there, this is my first time working with cryptocurrencies, i have been reading as much as possible since a couple weeks about how does they work and how to possibly setup a 'public' pool for clients which our company sells rigs to.

But i have come with a couple question which I don't really understand about the default settings on your app, first, the default settings are 'ready to go' to function as a public pool working on ETH?, I understand that as it uses geth/parity to gather and submit data to the network it should be working on the default geth network which is ETH, but i'm not entirely sure if this is ready for public usage for settings like difficulty, which is what my second question is about, by default it has a 20000000000 difficulty but as I understand this is set by the network and not the pool itself, is this setting only available for private uses like private coins, or in the case that it affects the ETH network performance it should be update whenever the network tuneup this number?

Hope anyone can help me out, thanks in advance.

**Comment by sammy007** [comment]
> first time working with cryptocurrencies
> setup a 'public' pool for clients which our company sells rigs to

Hire a consultant. It's not a training agency, it's an issue tracker.
