### ISSUE TITLE
Stratum Port not working 

### ISSUE THREAD

**Issue by Coryvmcs1** [sammy007/open-ethereum-pool#22]
When we setup the pool and trying to test the stratum port 8008 I see the following error in ethproxy window.

 Unknown RPC method: &{0xc8203aaf40 eth_login 0xc8203aaf80 }

Any help would be great.

**Comment by sammy007** [comment]
Stratum is compatible only with https://github.com/Atrides/eth-proxy and EthDcrMiner64 with `-esm 0`.

**Comment by Coryvmcs1** [comment]
Hi do you have an example of how to set it up with the pool? I am new to this pool and any help would be appreciated. I can donate for your help.

**Comment by sammy007** [comment]
I suggest to read proxy manual. Example config is:

eth-proxy.conf

```
COIN = "ETH"

# Host and port for your workers
HOST = "0.0.0.0"
PORT = 7777

# Coin address where money goes
WALLET = "0xb85150eb365e7df0941f0cf08235f987ba91506a"

# It's useful for individually monitoring and statistic
ENABLE_WORKER_ID = True

MONITORING = False
MONITORING_EMAIL = "mail@example.com"

# Main pool
POOL_HOST = "localhost"
POOL_PORT = 8547

# Failover pool
POOL_FAILOVER_ENABLE = False

POOL_HOST_FAILOVER1 = "demo.eurohash.net"
POOL_PORT_FAILOVER1 = 8547

# Logging
LOG_TO_FILE = True

# Enable debug
DEBUG = False
```

Run: `python eth-proxy.py`

**Comment by Coryvmcs1** [comment]
So is it just using the local wallet address that I create with geth ?

**Comment by Coryvmcs1** [comment]
Hey M8 would you be interested in getting this installed for me for a fee?

On Fri, May 27, 2016 at 2:00 PM, Sammy Libre <notifications@github.com>
wrote:

> I suggest to read proxy manual. Example config is:
>
> eth-proxy.conf
>
> COIN = "ETH"
>
> # Host and port for your workers
> HOST = "0.0.0.0"
> PORT = 7777
>
> # Coin address where money goes
> WALLET = "0xb85150eb365e7df0941f0cf08235f987ba91506a"
>
> # It's useful for individually monitoring and statistic
> ENABLE_WORKER_ID = True
>
> MONITORING = False
> MONITORING_EMAIL = "mail@example.com"
>
> # Main pool
> POOL_HOST = "localhost"
> POOL_PORT = 8547
>
> # Failover pool
> POOL_FAILOVER_ENABLE = False
>
> POOL_HOST_FAILOVER1 = "demo.eurohash.net"
> POOL_PORT_FAILOVER1 = 8547
>
> # Logging
> LOG_TO_FILE = True
>
> # Enable debug
> DEBUG = False
>
> Run: python eth-proxy.py
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sammy007/open-ethereum-pool/issues/22#issuecomment-222227752>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANDN260kTLNADIULvGfxIERNiSQ_akBVks5qFz9YgaJpZM4Iom81>
> .
>



-- 
Sincerely,
Cory Tselikis

**Comment by sammy007** [comment]
I think someone from gitter can help you.

**Comment by Coryvmcs1** [comment]
?? Not familiar with it.

**Comment by sammy007** [comment]
here is a gitter badge in README click on it, join chat and ask for help. Requires 1 minute of thinking. No one is nanny here.
