### ISSUE TITLE
RPC call fails

### ISSUE THREAD

**Issue by coin777** [sammy007/open-ethereum-pool#221]
#### System information

Redis version: `Redis server v=3.0.6`

OS & Version: Linux ubuntu 16.04

Commit branch and hash: `master`

#### Actual behaviour

I make a pool for etp coins based on Open Ethereum Pool.
https://github.com/sammy007/open-ethereum-pool
But when I try to connect to rpc(127.0.0.1:8820), 
I receive error messages:
`2017/10/25 11:25:47 Error while refreshing pending block on main: invalid character 'N' looking for beginning of value`

**mvsd version:**
`mvsd:           0.6.0
mvs-server:     0.6.0
mvs-protocol:   0.6.0
mvs-node:       0.6.0
mvs-blockchain: 0.6.0
mvs-base:       0.7.1`

**mvsd start command:**
`/usr/local/bin/mvsd -D /root/.metaverse -c /root/.metaverse/mvs.conf`

**mvsd config:**

[network]
threads = 10
protocol = 70012
identifier = 0x6d73766d
inbound_port = 5251
inbound_connections = 32
outbound_connections = 8
manual_attempt_limit = 0
connect_batch_size = 5
connect_timeout_seconds = 5
channel_handshake_seconds = 30
channel_heartbeat_minutes = 5
channel_inactivity_minutes = 30
channel_expiration_minutes = 1440
channel_germination_seconds = 30
host_pool_capacity = 1000
relay_transactions = true
hosts_file = hosts.cache
debug_file = debug.log 
error_file = error.log
self = 127.0.0.1:0
seed = main-europe.metaverse.live:5251
seed = main-europe.mvs.live:5251
[database]
history_start_height = 0
stealth_start_height = 350000
directory = mainnet

[blockchain]
block_pool_capacity = 5000 
transaction_pool_capacity = 2000
transaction_pool_consistency = false
use_testnet_rules = false

[node]
block_timeout_seconds = 5
download_connections = 8
transaction_pool_refresh = true

[server]
query_workers = 1
heartbeat_interval_seconds = 5
subscription_expiration_minutes = 10
subscription_limit = 100000000
mongoose_listen_port = 0.0.0.0:8820
log_requests = true
secure_only = false
query_service_enabled = true
heartbeat_service_enabled = false
block_service_enabled = false
transaction_service_enabled = false
public_query_endpoint = tcp://*:9091
public_heartbeat_endpoint = tcp://*:9002
public_block_endpoint = tcp://*:9003
public_transaction_endpoint = tcp://*:9004
secure_query_endpoint = tcp://*:9081
secure_heartbeat_endpoint = tcp://*:9082
secure_block_endpoint = tcp://*:9083
secure_transaction_endpoint = tcp://*:9084

**Open Ethereum Pool config:**

`{

        "threads": 2,
        "coin": "metaverse-prop",
        "name": "main",
        "proxy": {
                "enabled": true,
                "listen": "0.0.0.0:6558",
                "limitHeadersSize": 1024,
                "limitBodySize": 256,
                "behindReverseProxy": false,
                "blockRefreshInterval": "120ms",
                "stateUpdateInterval": "3s",
                "difficulty": 2000000000,
                "hashrateExpiration": "3h",

                "healthCheck": true,
                "maxFails": 100,

                "stratum": {
                        "enabled": true,
                        "listen": "0.0.0.0:6585",
                        "timeout": "120s",
                        "maxConn": 8192
                },

                "policy": {
                        "workers": 8,
                        "resetInterval": "60m",
                        "refreshInterval": "1m",

                        "banning": {
                                "enabled": false,
                                "ipset": "blacklist",
                                "timeout": 1800,
                                "invalidPercent": 30,
                                "checkThreshold": 30,
                                "malformedLimit": 5
                        },
                        "limits": {
                                "enabled": false,
                                "limit": 30,
                                "grace": "5m",
                                "limitJump": 10
                        }
                }
        },

        "api": {
                "enabled": true,
                "purgeOnly": false,
                "purgeInterval": "10m",
                "listen": "0.0.0.0:1050",
                "statsCollectInterval": "5s",
                "hashrateWindow": "30m",
                "hashrateLargeWindow": "3h",
                "luckWindow": [64, 128, 256],
                "payments": 30,
                "blocks": 50
        },

        "upstreamCheckInterval": "5s",
        "upstream": [
                {
                        "name": "main",
                        "url": "http://127.0.0.1:8820",
                        "timeout": "10s"
                },
                {
                        "name": "backup",
                        "url": "http://127.0.0.1:8820",
                        "timeout": "10s"
                }
        ],

        "redis": {
                "endpoint": "127.0.0.1:6379",
                "poolSize": 10,
                "database": 1,
                "password": ""
        },

        "unlocker": {
                "enabled": true,
                "poolFee": 0.5,
                "poolFeeAddress": "",
                "donate": false,
                "depth": 32,
                "immatureDepth": 16,
                "keepTxFees": true,
                "interval": "1m",
                "daemon": "http://127.0.0.1:8820",
                "timeout": "10s"
        },

        "payouts": {
                "enabled": true,
                "requirePeers": 1,
                "interval": "1m",
                "daemon": "http://127.0.0.1:8820",
                "timeout": "10s",
                "address": "",
                "gas": "21000",
                "gasPrice": "50000000000",
                "autoGas": true,
                "threshold": 5000000000,
                "bgsave": true
        },

        "newrelicEnabled": false,
        "newrelicName": "MyEtherProxy",
        "newrelicKey": "SECRET_KEY",
        "newrelicVerbose": false
}
`

Where can be the problem?
How to fix it?

**Comment by sammy007** [comment]
This is not a metaverse pool. Metaverse can pay me 25 BTC from ICO funds if they need one.
