### ISSUE TITLE
How to check stratum step by step?

### ISSUE THREAD

**Issue by AndreyNag** [sammy007/open-ethereum-pool#223]
#### System information

Geth version: `Gdbix
Version: 1.5.3-fluxdbix
Git Commit: f6911ea5eef13694420ab80fecb4139a8e45840e
Protocol Versions: [63 62]
Network Id: 7995
Go Version: go1.8.3
OS: linux
GOPATH=
GOROOT=/usr/local/go
`

Redis version: `Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42`

OS & Version: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-97-generic x86_64)

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
want stratum to work properly.

#### Actual behaviour
dont work from nicehash, claymore, ethminer etc. 

#### Backtrace

````
Please give us perfect scenario to step by step revision pool and whole server configuration.
Thank you very much!

From the first glance the [pool](http://sunlife.mine.nu/) is working fine.
````

**Comment by SpectrumQT** [comment]
Ethminer and Claymore etc. are working fine with Sammy007's stratum implementation. If you want Nicehash support than you need to add it by yourself. You can use wfr's fork as example and/or find a programmer.

**Comment by AndreyNag** [comment]
SpectrumQT, can you tell me what i have to tune to get nicehash support? At least in thesis.
Thnx.

**Comment by SpectrumQT** [comment]
Here goes 5 steps that allowed me to mine some hundreds of private network blocks with NH orders.
1. Merge your pool code with /util/ and /proxy/ .go files from the [wfr's fork](https://github.com/wfr/open-ethereum-pool-nh)
2. Look through said files and fix "FIX ME" errors.
3. Consider about doing something with wrong NiceHash miner's hashrate calculations. At least don't let the processShareNH function to write the result of float diff conversion as it is.
4. Add "DifficultyNiceHash" float (for example, 0.93130836 equals 4000000000 int diff) and "stratum_nice_hash" into the "proxy" block of your config files.
5. Run default and nicehash stratums as separate processes with different ports or rewrite the code to support both withing the same instance.

**Comment by sammy007** [comment]
Private testnet. Claymore must work with `-sm 0`. Nicehash not supported, check out forks for stratum mods.
