### ISSUE TITLE
Parity gives different heades for the same block ??

### ISSUE THREAD

**Issue by kiwina** [sammy007/open-ethereum-pool#226]
New block to mine on main at height 4556560 / 0x9b978d2b
New block to mine on main at height 4556560 / 0x387aa3bd

not sure what to make of this with geth i didnt have the problem but parity returns different headers??
should they not be the same for the block??
Unless a bad peer give out different info?

**Comment by sammy007** [comment]
It could be 4556561 height, there are 2 separate rpc calls so not always correct. or same block height after reorganize.
