### ISSUE TITLE
"make: does not make 

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#229]
#### System information

Geth version: N/A

Redis version: N/A

OS & Version: Ubuntu 16.04

Commit branch and hash: master, bcfc0eb0e683993ad0c51bacad8d4b354e769393

#### Expected behaviour

Typing the following should produce open-ethereum-pool/build/bin directory and files under it

```
git config --global http.https://gopkg.in.followRedirects true
git clone https://github.com/sammy007/open-ethereum-pool.git
cd open-ethereum-pool
make

```

#### Actual behaviour

After doing the above, the following command does not exist:

`./build/bin/open-ethereum-pool `

Instead, the open-ethereum-pool/build directory listing looks like this:
```

drwxrwxr-x  3 openethereumpool openethereumpool 4096 Nov 17 08:33 .
drwxrwxr-x 15 openethereumpool openethereumpool 4096 Nov 17 08:32 ..
-rwxrwxr-x  1 openethereumpool openethereumpool  770 Nov 17 08:32 env.sh
drwxrwxr-x  4 openethereumpool openethereumpool 4096 Nov 17 08:39 _workspace

```

**Comment by BaikalMine** [comment]
Update golang

**Comment by stone212** [comment]
@DeadMan993 I just installed it so should be the most current stable version for Ubuntu 16.04.  Do I need something newer than that?

**Comment by sammy007** [comment]
Must use golang 1.9.x.

**Comment by stone212** [comment]
Confirmed.  Thank you.
