### ISSUE TITLE
Apache instead of Nginx

### ISSUE THREAD

**Issue by vazha** [sammy007/open-ethereum-pool#230]
#### System information
OS & Version: Linux Ubuntu 14.04

Dear sammy007, could You pls explain how to use Apache web server instead on Nginx?
I do not understand which directives should I use in mysite.cond in Apache, instead of:
 upstream psapi {
    server 127.0.0.1:8591;
}
I'm already activated proxy mode in Apache using: a2enmod proxy
Short example please. Thanx!

**Comment by sammy007** [comment]
Short example is in apache/nginx docs. Configuring reverse proxies is out of scope of this issue tracker.

**Comment by bmatthewshea** [comment]
@vazha 
This works for me:

```
<VirtualHost:*:80>

    DocumentRoot "/someplace/open-ethereum-pool/www/dist"
    ServerName   mypool.local
    ServerAlias  *.mypool.local
    ErrorLog     "${APACHE_LOG_DIR}/mypool.local-error_log"
    CustomLog    "${APACHE_LOG_DIR}/mypool.local-access_log" common

<Directory />
    Require all Granted
</Directory>

<Location "/api">
    ProxyPass             http://127.0.0.1:8080/api
    ProxyPassReverse      http://127.0.0.1:8080/api
</Location>

</VirtualHost>
```

**Comment by vazha** [comment]
@bmatthewshea 
Thanks a lot!
I've tried so many different configurations with no results, and your solution is so simple and works
