### ISSUE TITLE
/build/bin/open-ethereum-pool

### ISSUE THREAD

**Issue by bapparabi** [sammy007/open-ethereum-pool#231]
hi i have done
 cd open-ethereum-pool
make

but i can see it not creating build folder and open-ethereum-pool file .. do you know what is reason ..

this out come of the make command 

`root@localhost:/home/pooladmin/open-ethereum-pool# make
build/env.sh go get -v ./...
github.com/gorilla/mux (download)
github.com/ethereum/go-ethereum (download)
Fetching https://gopkg.in/redis.v3?go-get=1
Parsing meta tags from https://gopkg.in/redis.v3?go-get=1 (status code 200)
get "gopkg.in/redis.v3": found meta tag main.metaImport{Prefix:"gopkg.in/redis.v3", VCS:"git", RepoRoot:"https://gopkg.in/redis.v3"} at https://gopkg.in/redis.v3?go-get=1
gopkg.in/redis.v3 (download)
Fetching https://gopkg.in/bsm/ratelimit.v1?go-get=1
Parsing meta tags from https://gopkg.in/bsm/ratelimit.v1?go-get=1 (status code 200)
get "gopkg.in/bsm/ratelimit.v1": found meta tag main.metaImport{Prefix:"gopkg.in/bsm/ratelimit.v1", VCS:"git", RepoRoot:"https://gopkg.in/bsm/ratelimit.v1"} at https://gopkg.in/bsm/ratelimit.v1?go-get=1
gopkg.in/bsm/ratelimit.v1 (download)
github.com/ethereum/ethash (download)
github.com/gorilla/mux
github.com/ethereum/go-ethereum/common/hexutil
github.com/ethereum/go-ethereum/crypto/sha3
github.com/ethereum/go-ethereum/common/math
gopkg.in/redis.v3/internal
gopkg.in/redis.v3/internal/consistenthash
gopkg.in/redis.v3/internal/hashtag
gopkg.in/bsm/ratelimit.v1
github.com/ethereum/go-ethereum/common
gopkg.in/redis.v3/internal/pool
gopkg.in/redis.v3
github.com/sammy007/open-ethereum-pool/util
github.com/sammy007/open-ethereum-pool/rpc
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1
github.com/sammy007/open-ethereum-pool/storage
github.com/sammy007/open-ethereum-pool/api
github.com/sammy007/open-ethereum-pool/payouts
github.com/sammy007/open-ethereum-pool/policy
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto/sha3
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/rlp
github.com/ethereum/ethash/vendor/github.com/go-stack/stack
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/log
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto
github.com/ethereum/ethash
github.com/sammy007/open-ethereum-pool/proxy
root@localhost:/home/pooladmin/open-ethereum-pool#
`

**Comment by sammy007** [comment]
> README.md

go >= 1.9

**Comment by leejy016** [comment]
--- PASS: TestWritePayment (0.00s)
=== RUN   TestGetPendingPayments
--- PASS: TestGetPendingPayments (0.00s)
=== RUN   TestCollectLuckStats
--- PASS: TestCollectLuckStats (0.00s)
PASS
ok      github.com/sammy007/open-ethereum-pool/storage  0.119s
?       github.com/sammy007/open-ethereum-pool/util     [no test files]
root@182183:~/open-ethereum-pool# go version
go version go1.9.2 linux/amd64
root@182183:~/open-ethereum-pool#

ㅠㅠ
