### ISSUE TITLE
Payouts "module"?

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#233]
This doc (https://github.com/sammy007/open-ethereum-pool/blob/master/docs/PAYOUTS.md) references a "payouts module" but it is not mentioned anywhere else.

Is this related to payouts/payouts.go?  What is needed to run this?

If you try:

`go run payer.go you get this error`

> go run: cannot run non-main package

I notice that there is also a "main.go" file in the root directory that is not mentioned anywhere in the doc (that I have seen).  Is this something that needs to be run?  I do see that it references payouts, so possibly this is the missing piece why payouts have not been functioning for me?

Is it necessary to start the pool using "go run main.go" instead of using "./build/bin/open-ethereum-pool config.json"?  Will that trigger payouts?

The doc linked above also says Payouts should be run as a separate process.  What is the recommended method for doing this?

**Comment by weldstech** [comment]
payouts in referance to the payouts within the json file.  within the json files are the modules hence the true or false to turn the on or off.  to run payouts all other modules within that instance of the json file your about to run should be turned off.  Example create another config.json but call it payments.json and only enable the payments module within it and then run that as an instance.

**Comment by stone212** [comment]
@weldstech This is extremely helpful.  I would not have guessed this in one hundred years of trying.

Do you know what the "address" parameter refers to in the "payouts" module?  Is that the same as the "author" address that is unlocked on the node that the miner is running on?  If not, I can't imagine what it could be, as the individual destination wallets are determined by the individual mining rigs.

**Comment by weldstech** [comment]
Payouts address can be any wallet that you chose to pay from just as long as it has enough coins to do so.  Hence most leave it as the author wallet.

**Comment by stone212** [comment]
@weldstech okay thank you this is what I did.  But payouts are still not working.  I have the author account specified as "--author" on the command line.   I also have that account unlocked on the same command line.  I specified a low time interval and a low ETH threshold but payouts are still not working.  (The author account collects everything and the payout console says "No payees that have reached payout threshold".

I also have one (only one) of the payee accounts unlocked (of course this unlocking is on a different node/computer).

Can you think of anything else I am not thinking of that I should try?

**Comment by stone212** [comment]
@weldstech I don't know if this information helps:

This is the output of running the pool:

```
2017/11/25 01:21:47 Loading config: /home/openethereumpool/open-ethereum-pool/payouts.json
2017/11/25 01:21:47 Running with 2 threads
2017/11/25 01:21:47 Backend check reply: PONG
2017/11/25 01:21:47 Starting payouts
2017/11/25 01:21:47 Set payouts interval to 10m0s
2017/11/25 01:21:47 No payees that have reached payout threshold
```

This is my payouts section:
```

       "payouts": {
                "enabled": true,
                "requirePeers": 1,
                "interval": "10m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s",
                "address": "0x00abbC34d5506C4397B3B920Ea9F2Bb210104799",
                "gas": "21000",
                "gasPrice": "50000000000",
                "autoGas": true,
                "threshold": 50,
                "bgsave": false
        },
```

Do you notice anything that would cause the problem?

**Comment by stone212** [comment]
Closing this issue because the actual issue was answered by @weldstech 3 days ago.

**Comment by stone212** [comment]
@weldstech I opened a new Issue if you have any time to help. 

https://github.com/sammy007/open-ethereum-pool/issues/234
