### ISSUE TITLE
System Requirements (poll)

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#236]
Just wondering what the minimum systems are that people have been running this on successfully.  I am running happily on 4GB ram 2 Core 2.6Ghz.  However I only have two miners attached.

If anyone is running on less, please share and we will get a sense of what is required.

**Comment by Castafers** [comment]
That's perfectly enough RAM for about 5 miners. I run on 2.3GB RAM and 250GB SSD and I am running on 13 miners. Your fine dude, but always better to be safe than sorry.

**Comment by stone212** [comment]
@ShadowPauler 
You said 4GB is good for 5 miners but you're running 2GB RAM with 13 miners?  Am I reading that right?

**Comment by sammy007** [comment]
tl;dr: you need at least 32-64 GB of RAM. Not a help desk. Joib chat on gitter if needed.

**Comment by stone212** [comment]
> you need at least 32-64 GB of RAM

You must be joking.  I doubt that anyone is using a machine with 32GB of ram to run your pool.

> Joib chat on gitter if needed.

No thank you.  This would be a better venue for such a question, here in Issues of github.  Because it's static and searchable.  I can just open another one if you prefer.

**Comment by sammy007** [comment]
So you seems never tried to launch a node and validate transactions and execute contracts especially under current spam load.
