### ISSUE TITLE
ERROR[12-01|08:38:08] write tcp 127.0.0.1:8545->127.0.0.1:57762: write: broken pipe

### ISSUE THREAD

**Issue by minitzi** [sammy007/open-ethereum-pool#239]
Hello. 
Im using geth 17.3 , on ubuntu 16.04 
im getting this error  🔢 

INFO [12-01|08:38:37] Imported new chain segment               blocks=1 txs=227  mgas=6.652  elapsed=2.529s    mgasps=2.630   number=4656403 hash=4c4ea7▒80273e
INFO [12-01|08:38:43] Imported new chain segment               blocks=1 txs=5    mgas=0.138  elapsed=418.967ms mgasps=0.330   number=4656404 hash=6cd4a5▒0edb25
INFO [12-01|08:38:47] Commit new mining work                   number=4656404 txs=276  uncles=0 elapsed=9.334s
INFO [12-01|08:38:49] Commit new mining work                   number=4656405 txs=265  uncles=0 elapsed=2.383s
ERROR[12-01|08:38:49] write tcp 127.0.0.1:8545->127.0.0.1:58352: write: broken pipe

INFO [12-01|08:38:56] Imported new chain segment               blocks=1 txs=10   mgas=0.362  elapsed=34.990ms  mgasps=10.339  number=4656405 hash=9b91d5▒c2aea6
INFO [12-01|08:39:00] Commit new mining work                   number=4656406 txs=211  uncles=0 elapsed=3.935s

Do you have any idee where did i mistake ? 
And block sincronisations it delays about 30 seconds.
Can anybody help 
Im new to this :)
Thanks

**Comment by mikeyb** [comment]
This is not support.  This is for bug tracking.  Running a financial pool is not easy, if you are new, find something easier.

**Comment by sammy007** [comment]
it looks like rpc client disconnected, could be wrong. I see only geth log, this is not a geth support channel.
