### ISSUE TITLE
New blocks

### ISSUE THREAD

**Issue by HelixiR** [sammy007/open-ethereum-pool#24]
Hi again)))
After some time mining from pool start, pool find a block, and this block showing in stats "New blocks" (Recently Found Blocks). What happens with block next?) Why is not in immature tab or block tab? oO

UP:
https://etherscan.io/block/1617995

Why : Mined By:	0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5 (Nanopool) in 0 secs

**Comment by 9600-** [comment]
I have the same symptom, only I've created it on purpose by disabling the unlocker and payout modules in the config. Redis data is not written to the DB this way and you'll end up with only what's stored in NGINX.

**Comment by HelixiR** [comment]
I have enabled unlocker and reward module. But what with this block? is orphaned? :(

**Comment by 9600-** [comment]
Oh I'm sorry, I didn't look at your post in its entirety. We're not supposed to have orphans in Ethereum, only Uncles. Are you sure you've pasted the proper block height? What is the etherbase address of the pool daemon?

**Comment by HelixiR** [comment]
Pool adress:
https://etherscan.io/address/0x308b9bffb317c76f15037b4e70253f5938ca0ef9

This block height showing on frontend of pool in New Block tab.:
https://etherscan.io/block/1617995

**Comment by HelixiR** [comment]
Maybe i do something wrong at start pool?
In config.json - payout and unlocker module are enabled.
I start geth, after i start pool, after i start frontend.

Maybe i need start some modules manual? like unlocker and payouts?

**Comment by 9600-** [comment]
Nope you're good! You just mined an Uncle block!

Check out the "mined uncles" tab in from your etherscan.io link. 

Block	Age	UncleNumber	Difficulty	GasUsed	Reward
1617997	5 hrs 54 mins ago	**_1617995_**	43.66 TH	248559	3.75 Ether

**Comment by 9600-** [comment]
Sammy has suggested running payout and unlocker scripts as separate processes and I would suggest you do the same. Are you running redis in a screen? Can you check to make sure you're writing to the redis DB?  If unlocker, payout and Redis are running, you should't have any share logging issues.

**Comment by 9600-** [comment]
> I start geth, after i start pool, after i start frontend.

Are you running Redis?

**Comment by HelixiR** [comment]
amm... no. I dont run any redis manually, redis start auto (maybe).
Can u help me check this?

**Comment by 9600-** [comment]
Can you run the following command and paste the output?

> netstat -atn | grep 6379

**Comment by HelixiR** [comment]
$ netstat -atn | grep 6379
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:33147         127.0.0.1:6379          ESTABLISHED
tcp        0      0 127.0.0.1:33144         127.0.0.1:6379          ESTABLISHED
tcp        0      0 127.0.0.1:6379          127.0.0.1:33145         ESTABLISHED
tcp        0      0 127.0.0.1:6379          127.0.0.1:33144         ESTABLISHED
tcp        0      0 127.0.0.1:6379          127.0.0.1:33147         ESTABLISHED
tcp        0      0 127.0.0.1:33145         127.0.0.1:6379          ESTABLISHED
alice@eth:~/open-ethereum-pool$

**Comment by HelixiR** [comment]
Maybe go to gitter? if u can
https://gitter.im/sammy007/open-ethereum-pool

**Comment by sammy007** [comment]
> I start geth, after i start pool, after i start frontend.

If you run geth after launching pool unlocker is likely suspended.

Also unlocker requires some blocks to determine if mined block was uncle or not. if you unlocker is disabled new blocks will stay as new. After a few blocks mined back new block will became immature and so on.

**Comment by HelixiR** [comment]
No i first start geth. after pool, and after frontend.
I created file payout.conf, disabled all but not payout and unlock modules and start this - statistic and rewards calculated after this normally, and send money to miners. But why is not working all-in-one config?

**Comment by sammy007** [comment]
> But why is not working all-in-one config?

It works. It's not recommended, usually you need to restart payouts and unlocker sometimes and no need to touch mining endpoint during these restarts.

**Comment by HelixiR** [comment]
I dont restart pool core (with dead payout and unlocker), it's no trouble?)))
i start this modules dedicated, and now (maybe in testing) all's fine.

**Comment by sammy007** [comment]
Make sure you are not running 2 instances of unlocker and payout module simultaneously.

**Comment by sammy007** [comment]
And also don't forget to close issues if problem is solved.
