### ISSUE TITLE
different stratum port for difefr dificulty

### ISSUE THREAD

**Issue by bapparabi** [sammy007/open-ethereum-pool#240]
hi sir i am trying to setup differ stratum port for different difficulty as nicehash need high difficulty and otehr need smaller ..

so can you please guide me what need to be done and hoe to do it

**Comment by mikeyb** [comment]
read

**Comment by bapparabi** [comment]
where ??

**Comment by mikeyb** [comment]
maybe try the configuration file, where you generally set this information in all applications.

I can tell you now you will not get this running.  Find another hobby.  Do not open issues for support.

THIS IS FOR BUG ISSUE TRACKING

**Comment by sammy007** [comment]
With different difficulty getwork must be different. I propose different `etherbase` settings for each stratum instance.

**Comment by sammy007** [comment]
Here https://github.com/sammy007/open-ethereum-pool/issues/10
