### ISSUE TITLE
Looking for best practices for fault tolerant, scalable and redundant mining pool

### ISSUE THREAD

**Issue by manipulator01** [sammy007/open-ethereum-pool#242]
Hello all,

I am a seasoned system administrator and I've been asked to build a fault tolerant, scalable and redundant mining pool based on sammy's script. I am going to be using AWS to host my server infrastructure and we aim to have 100% uptime.

I would like to ask some best practice questions here. I read all of the wiki documentation beforehand and I also looked at some of the discussions here as well. 

I currently have one server for each of these guys:

* Stratum and HTTP Proxy
* API & Web Interface
* Unlocker module
* Payout module
* Master Geth server
* Backup Geth server 
* I also have a Redis server running on multiple availability zones with automatic failover. 

All of my server nodes are communicating with it via low latency private network

**Questions:**

1. Can I host multiple Stratum and Http proxy endpoints behind TCP load balancer? My load balancer will direct the traffic to one of these available servers. If one machine dies, I want another one to serve my miners.
2. Can I safely auto-scale my Stratum and HTTP proxy servers when my system is under a load?
3. Can I host multiple API & Web Interface servers and serve them behind load balancer?
4. Should I be using same geth account on my Master and backup geth server?

and any other best practices you can think of.

**Comment by weldstech** [comment]
manipulator01 for a seasoned system admin why would you open this under issues ?

**Comment by LeChuckDE** [comment]
1. Yes, but failover will disconnect clients,  but reconnect will be possible directly after timeout connection
2. Give it a try, but at time i don't think that you will reach a 100% load due stratum or http requests
3. come on this is a shitty question if you are a seasoned sys admin ... 
4. sure

best practices tipp: get the documentation about the protocols first, read read read

**Comment by sammy007** [comment]
If load balancer is a haproxy, put many stratums as backends and connect clients to balancer.
