### ISSUE TITLE
Incorrect rewards amount

### ISSUE THREAD

**Issue by voipcall** [sammy007/open-ethereum-pool#243]
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42
Redis version: `redis-server --version`

Debian 16.04

I am running musicoin mining pool, where is reward from block 250coins.
In unlocker.go i changed:
var homesteadReward = math.MustParseBig256("5000000000000000000")
var byzantiumReward = math.MustParseBig256("3000000000000000000")
to
var constReward = math.MustParseBig256(“250000000000000000000”) 
But system still show reward 5

**Comment by sammy007** [comment]
This pool is for ethereum.
