### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Marow** [sammy007/open-ethereum-pool#244]
getting this error while running config.json for long time...

`panic: runtime error: invalid memory address or nil pointer dereference`

But i dont know what this is... it was running like 1 month and than crashed with this error... restarting helps but what is that

Also, can i autorestart the config, if any crash?

**Comment by sammy007** [comment]
When you create issue there is a template with some fields to fill. Since you ignored to publish required info I am closing this ticket. Feel free to post details and I will check it.

**Comment by stone212** [comment]
@Marow Did you ever solve this problem?
