### ISSUE TITLE
multiple coin instances 

### ISSUE THREAD

**Issue by ghost** [sammy007/open-ethereum-pool#245]
Just curios if anyone knows how to add multiple coins to the open etherum pool on one server. if so how would it be done. i don't think i should have to get new server for every coin i add to the pools am i correct

**Comment by sammy007** [comment]
It's a bug tracker, not a help desk. This question is about deployment. There is gitter chat for that.

**Comment by ghost** [comment]
Send me the link for the chat. Sammy if you will

**Comment by sammy007** [comment]
The badge is in readme FYI.

**Comment by ghost** [comment]
Ok thanks man
