### ISSUE TITLE
Config.json permission denied

### ISSUE THREAD

**Issue by Curifiq** [sammy007/open-ethereum-pool#246]
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````

**Comment by Curifiq** [comment]
./build/bin/open-ethereum-pool config.json
I am having trouble running this.
I have created the config file in /home/ubuntu/open-ethereum-pool with the name of config.json
But when i try to load it I get permission denied. Both with UBUNTU and ROOT user.

geth version
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

redis-server --version
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

**Comment by sammy007** [comment]
It's a bug tracker, not a help desk.
