### ISSUE TITLE
ETC Reward Unlock blocks to 4 etc

### ISSUE THREAD

**Issue by thaigqsoft** [sammy007/open-ethereum-pool#248]
#### System information

Geth version: `geth version` or commit hash if `develop`
Parity/v1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21.0

Redis version:  v=3.0.6

OS & Version: ubuntu 14.04

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
Unlock blocks

#### Actual behaviour
my use pool etc miners
I found that problem after etc update  Reward  block to 4 etc / block
pool unlock to 5 etc.
how to fix it 
to Reward 4 etc pls.

#### Steps to reproduce the behaviour
just run pool and get a block

#### Backtrace

````
[backtrace]
````

**Comment by sammy007** [comment]
As far as I know there is ETC foundation, they receive some payments from users of my pool, ask them for assistance.
