### ISSUE TITLE
Proxy process crashed in some cases

### ISSUE THREAD

**Issue by pastrehe** [sammy007/open-ethereum-pool#249]
#### System information

Geth
Version: 1.7.2-stable
Git Commit: 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

Redis server v=3.2.1 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=8ab9de078b62748e

Linux miningpool 4.9.50-x86_64-linode86 #1 SMP Thu Sep 14 19:28:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

On branch master
commit 73e8c1a21910e2065c77d704df14fe4485ee51e4

#### Expected behaviour
Proxy process works

#### Actual behaviour
Some time proxy process crashed

#### Steps to reproduce the behaviour
Proxy is runnig with stratum enabled.
Some time it's crashed (backtrace below)
Probably, its happening when a new tcp session is started with the same ports as an earlier session
Please, check pcap file attached. This dump was made during the crash.
Look at the frames 10 & 11 - looks
[stratum2_00001_20171212103623.pcap.zip](https://github.com/sammy007/open-ethereum-pool/files/1551514/stratum2_00001_20171212103623.pcap.zip)

 like app crashed right after receiving them.

#### Backtrace

````
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x556abfb5f43b]

goroutine 71 [running]:

panic(0x556abfe76460, 0xc4200160e0) /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1 github.com/sammy007/open-ethereum-pool/proxy.(*Session).handleTCPMessage(0xc42011d400, 0xc420126090, 0xc4202aa270, 0x556abfe42c00, 0xc4202aa270)                                                                                            

/opt/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:126 +0x16b github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).handleTCPClient(0xc420126090, 0xc42011d400, 0x0, 0x556abfadf6f8)                                                                                                              

/opt/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:94 +0x288 github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).ListenTCP.func1(0xc420123280, 0xc420126090, 0xc42011a290, 0xc42015a000, 0xc42011d400)

/opt/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:55 +0x39 created by github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).ListenTCP

/opt/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:61 +0x469
````

**Comment by sammy007** [comment]
I can't find `1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9 ` commit in this repo. You must use latest `master` branch and run latest golang 1.9 as specified in README. I remember some issue with params deserialisation due to breaking change in golang. It's fixed now. This pcap dump is useless, I need to see raw protocol sniff, you can make it with `ngrep`.

**Comment by pastrehe** [comment]
Ok, I'll rebuild pool with latest golang.
This pcap was captured between application start and crash, i.e. I started tshark, started proxy, proxy crashed, tshark stopped. So, we have only this 11 frames with running application.

Frames 1-6 : application not started (OS sends RST on client's SYNs)
Frames 7-17: application running, we see TCP packets to both sides
Frames 18 - xxx : application crashed, OS sends RST responses again.

So, this might be not high-level protocol issue, but tcp-session issue.

P.S. soft was built from "73e8c1a21910e2065c77d704df14fe4485ee51e4" commit, not "1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9"

**Comment by sammy007** [comment]
Commit `73e8c1a21910e2065c77d704df14fe4485ee51e4` is old, you must run latest `master`.

**Comment by pastrehe** [comment]
Update:
In pcap we can find 3 tcp streams, the most interesting is stream 3, client sends message contains  '{"method":"eth_submitWork"}' only.
Application crashed right after receiving message.
So, I'll update soft to latest commit, build with golang 1.9 and check.

![screen shot 2017-12-12 at 19 12 33](https://user-images.githubusercontent.com/12062020/33900949-7de6a1f2-df70-11e7-926b-ba82f4e7553d.png)

**Comment by sammy007** [comment]
Yes it's exactly what I fixed and you must update.
