### ISSUE TITLE
help config stats api

### ISSUE THREAD

**Issue by kangancur** [sammy007/open-ethereum-pool#25]
Stats API Temporarily Down

Usually it's just a temporal issue and mining is not affected.

**Comment by sammy007** [comment]
What is your question?

**Comment by kangancur** [comment]
Stats API Temporarily Down

Usually it's just a temporal issue and mining is not affected.

how to fix?

**Comment by sammy007** [comment]
By reading manual. You need to properly configure `www/config/environment.js` and you can find info how to do that in README.md.

**Comment by kangancur** [comment]
http://server.ancurnet.ga/open-ethereum-pool/www/dist/

**Comment by sammy007** [comment]
Your api is unavailable, make sure it's available under `http://server.ancurnet.ga:8082/api` location.

Url `http://server.ancurnet.ga:8082/api/stats` must return some JSON data.

**Comment by kangancur** [comment]
help

2016/06/07 19:18:23 Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2016/06/07 19:18:23 Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
