### ISSUE TITLE
Not file

### ISSUE THREAD

**Issue by Lvenkin** [sammy007/open-ethereum-pool#250]
ubuntu@ip-172-31-8-144:~/open-ethereum-pool$ ./build/bin/open-ethereum-pool config.json
bash: ./build/bin/open-ethereum-pool: No such file or directory

**Comment by xussr** [comment]
You need to carefully examine the readme

Clone & compile:

git config --global http.https://gopkg.in.followRedirects true
git clone https://github.com/sammy007/open-ethereum-pool.git
cd open-ethereum-pool
make

Running Pool
./build/bin/open-ethereum-pool config.json

**Comment by Juanhu1** [comment]
I have the same problem, there is no "bin" folder within "build". I removed the open-ethereum-pool folder and tried again with same result. And again. I don't see any error in the clone or make.

**Comment by JohnPreston** [comment]
Hi,

I had the same issue. Make sure to have go 1.9, I had the mainstream go from Ubuntu repos and that wasn't building properly. After upgrading to 1.9 the build was there with the binary.

**Comment by mikeyb** [comment]
Make sure you READ

DONE.

DO NOT OPEN SUPPORT TICKETS FOR YOUR INCOMPETENCE.  THIS IS FOR BUG TRACKING.
