### ISSUE TITLE
Uncle Reward ETC

### ISSUE THREAD

**Issue by xussr** [sammy007/open-ethereum-pool#251]
#### System information

version Parity/v1.7.10-stable-3931713-20171211/x86_64-linux-gnu/rustc1.22.1

Redis version: `Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

Pool got uncle block but the payment was not calculated correctly. Miners were paid 3 etc instead of 0.125, I suspect that you need to improve something in unlocker.go but my knowledge is not enough. Please excuse me for my English.

**Comment by robyle** [comment]
Excuse me, are you get the ok?

**Comment by xussr** [comment]
Problem?

**Comment by robyle** [comment]
yes. I want deploy this website by test. But something get error.

**Comment by mikeyb** [comment]
This is NOT a help system.  You are not capbable of running this.  This is financial software services, not noob who wants to get rich quick.

Also this is built for Ethereum, not Ethereum Classic.  This alone tells me you SHOULD NOT BE RUNNING FINANCIAL POOLS!!!!!!!!!!!!!!!!!!!!!!!

But if you must, https://github.com/LeChuckDE/open-ethereumclassic-pool

DO NOT OPEN ISSUES FOR YOUR INCOMPETENCE.  THIS IT NOT SUPPORT.  BYE!

**Comment by xussr** [comment]
Baby Goat! Your nickname hints that there is nothing to talk with you. if there is nothing to write in essence do not litter the ether with your spam. Sammy if it considers it necessary not to answer my question or criticize me for stupid questions, I'll understand this. Create yourself issues and enjoy your sarcasm there.

**Comment by sammy007** [comment]
This pool is for ETH, you must patch unlocker for other coins yourself.

**Comment by robyle** [comment]
I just want to study about this system.

**Comment by mikeyb** [comment]
@xussr you truly are stupid.  What I wrote applied exactly to you.  This is not a help desk.  Nor is this a place where the dumbest people on the internet come to be spoon fed answers they are either too stupid or too lazy to figure out.

YOU are the idiotic problem.

P.S. if you had half a brain, you would have looked at my profile and realized I might know what I am talking about, dipshit

**Comment by mikeyb** [comment]
@cyroby it is open source, study away by READING.  I know, its hard.
