### ISSUE TITLE
Incorrect block reward 

### ISSUE THREAD

**Issue by petoroland** [sammy007/open-ethereum-pool#252]
#### System information

PIRL version: 
Version: 1.0.1-stable
Git Commit: d2b89be6d2f7e995314d3532a046579b70571d6b
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 3125659152
Go Version: go1.8.3
Operating System: linux

Redis version: `redis-server --version`
Redis server v=2.8.17 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=4c1d5710660b9479

OS & Version: Linux/OSX
Linux

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
The full PIRL block reward (10PIRL) should be payed out for miners.

#### Actual behaviour
Only around 5 PIRL per blocks got payed for miners instead of 10. Pool logs also show that amount: revenue 5.15940000, miners profit 5.15424060, pool profit: 0.00464346 as well as the web page.
The missing amount remains on the coinbase address.

I am not sure if it is a pool issue or not. Can you help me please? Do you have any idea?

Thanks in advance!

**Comment by petoroland** [comment]
Hi,

I think I found the solution in one of the closed issues. Sorry for that. Please close this one.

Thansk,
Roland

**Comment by mikeyb** [comment]
This is for Ethereum network, not PIRL.  You would have to make the necessary changes yourself
