### ISSUE TITLE
2 pool in same sererv to show using ngnix

### ISSUE THREAD

**Issue by bapparabi** [sammy007/open-ethereum-pool#253]
hi i have 2 coin in same server using 2 differ user all are working fine but i am ot bale to show 2 coin api to 2 location and 2 sudomain 

i am using in one like this 

upstream api 
{
	server ubiq.drowningpool.net:8080;
}

server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /home/user/open-ethereum-pool/www/dist; # <- This should be the absolute path to the files
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
		
		location /api 
		{
			proxy_pass http://api;
		}
}

so how can another one i can use so that it will show suing differ api port and url and how can i use in ngnix to show 2 different pool state in 2 link

**Comment by sammy007** [comment]
Not a help desk.
