### ISSUE TITLE
github.com/sammy007/open-ethereum-pool/util     [no test files]  help me

### ISSUE THREAD

**Issue by leejy016** [sammy007/open-ethereum-pool#258]
root@182183:~/open-ethereum-pool# make test
build/env.sh go get -v ./...
build/env.sh go test -v ./...
?       github.com/sammy007/open-ethereum-pool  [no test files]
?       github.com/sammy007/open-ethereum-pool/api      [no test files]
=== RUN   TestCalculateRewards
--- PASS: TestCalculateRewards (0.00s)
=== RUN   TestChargeFee
--- PASS: TestChargeFee (0.00s)
=== RUN   TestWeiToShannonInt64
--- PASS: TestWeiToShannonInt64 (0.00s)
=== RUN   TestGetUncleReward
--- PASS: TestGetUncleReward (0.00s)
=== RUN   TestGetByzantiumUncleReward
--- PASS: TestGetByzantiumUncleReward (0.00s)
=== RUN   TestGetRewardForUngle
--- PASS: TestGetRewardForUngle (0.00s)
=== RUN   TestGetByzantiumRewardForUngle
--- PASS: TestGetByzantiumRewardForUngle (0.00s)
=== RUN   TestMatchCandidate
--- PASS: TestMatchCandidate (0.00s)
PASS
ok      github.com/sammy007/open-ethereum-pool/payouts  0.013s
?       github.com/sammy007/open-ethereum-pool/policy   [no test files]
?       github.com/sammy007/open-ethereum-pool/proxy    [no test files]
?       github.com/sammy007/open-ethereum-pool/rpc      [no test files]
=== RUN   TestWriteShareCheckExist
--- PASS: TestWriteShareCheckExist (0.01s)
=== RUN   TestGetPayees
--- PASS: TestGetPayees (0.03s)
=== RUN   TestGetBalance
--- PASS: TestGetBalance (0.04s)
=== RUN   TestLockPayouts
--- PASS: TestLockPayouts (0.00s)
=== RUN   TestUnlockPayouts
--- PASS: TestUnlockPayouts (0.00s)
=== RUN   TestIsPayoutsLocked
--- PASS: TestIsPayoutsLocked (0.00s)
=== RUN   TestUpdateBalance
--- PASS: TestUpdateBalance (0.00s)
=== RUN   TestRollbackBalance
--- PASS: TestRollbackBalance (0.00s)
=== RUN   TestWritePayment
--- PASS: TestWritePayment (0.00s)
=== RUN   TestGetPendingPayments
--- PASS: TestGetPendingPayments (0.00s)
=== RUN   TestCollectLuckStats
--- PASS: TestCollectLuckStats (0.00s)
PASS
ok      github.com/sammy007/open-ethereum-pool/storage  0.111s
?       github.com/sammy007/open-ethereum-pool/util     [no test files]
root@182183:~/open-ethereum-pool# ^C

**Comment by mikeyb** [comment]
lol :joy::joy::joy::joy::joy: where do they come from?
