### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by peterkristel** [sammy007/open-ethereum-pool#259]
http://prntscr.com/hq5gwm

loader.js:247 Uncaught Error: Could not find module `pool/app` imported from `(require)`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at requireModule (loader.js:24)
    at app-boot.js:4

And can't execute ./build/bin/open-ethereum-pool config.json

root@ubuntu-1gb-ams2-01:~# ./build/bin/open-ethereum-pool config.json
bash: ./build/bin/open-ethereum-pool: No such file or directory

**Comment by mikeyb** [comment]
WHAT IN THE LITERAL FUCK!!!

This is so far beyond your skillset, I won't even go into detail...Trying to exectue config files...geezus
