### ISSUE TITLE
Errors on installing packages..

### ISSUE THREAD

**Issue by onecloudmanagement** [sammy007/open-ethereum-pool#26]
Hi Guys, trying to get this running :)

getting this error at this point cant figure it out
```

EtherPool:~$ go get gopkg.in/go-redis/cache.v3
# gopkg.in/redis.v3
go/src/gopkg.in/redis.v3/error.go:70: undefined: strings.LastIndexByte
```

also 

```
EtherPool:~$ cd open-ethereum-pool/
Etharadmin@EtherPool:~/open-ethereum-pool$ go build -o ether-pool main.go
# gopkg.in/redis.v3
../go/src/gopkg.in/redis.v3/error.go:70: undefined: strings.LastIndexByte

```
But I guess the last one must be due to the first error. 

Please help me get up and running.

**Comment by sammy007** [comment]
You need at least golang 1.5 version.

**Comment by sammy007** [comment]
Updated golang req. version to >= 1.5 in README.

**Comment by onecloudmanagement** [comment]
thanks, I installed and added the exports to the profile and rebooted. Getting this now...

go: cannot find GOROOT directory: /usr/local/go

**Comment by sammy007** [comment]
Because it somewhere else prolly.

**Comment by onecloudmanagement** [comment]
i did moved it to local. 

@EtherPool:/usr/local$ ls
bin  etc  games  go  include  lib  man  sbin  share  src
Etharadmin@EtherPool:/usr/local$

sorry, bit confused, being that it is there, do I still run export GOPATH=$HOME/go?

**Comment by sammy007** [comment]
https://golang.org/doc/install/source
