### ISSUE TITLE
Problem with mining 

### ISSUE THREAD

**Issue by aymen1984** [sammy007/open-ethereum-pool#260]
#### System information

Geth version: `geth version` or commit hash if `develop`
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=/root/go
GOROOT=/usr/lib/go-1.9

Redis version: `redis-server --version`
Redis server v=4.0.6 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=24cef40ebd18ad26

OS & Version: Linux/OSX
ubuntu 16.04
Commit branch and hash: (`master`, `ba60e1c`)
master
#### Actual behaviour

Error while refreshing pending block on main: json: cannot unmarshal number into Go value of type rpc.JSONRpcResp
#### Backtrace

````
[backtrace]
````

**Comment by mikeyb** [comment]
Use the search feature...derp
