### ISSUE TITLE
Can't start pool

### ISSUE THREAD

**Issue by Twcd** [sammy007/open-ethereum-pool#261]
Hi, when i try to start the pool i got this :

`ethereum-pool$ ./build/bin/open-ethereum-pool config.json
bash: ./build/bin/open-ethereum-pool: No such file or directory
gael@gael-virtual-machine:/media/gael/1868a3d2-de79-467c-b9da-1d28a90061c8/open-ethereum-pool$ 
`

Can you help me ? Thanks

**Comment by mikeyb** [comment]
1.  You deleted the template for the new issue and decided you were so god damn smart that you didnt need to ask for help with the info the helpers ask for.  GFY

2.  You didnt search this repo for that error, cause I see 9 issues of the same.  GFY

3.  No.  We cannot help you.  You cannot teach programming skills to someone who is unwilling to learn.  GFY

GFY GFY GFY
