### ISSUE TITLE
./build/bin missing

### ISSUE THREAD

**Issue by wildnrg** [sammy007/open-ethereum-pool#266]
#### System information

Geth version: 
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9

Redis version: 
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

OS & Version: Linux
Linux ip-172-31-45-199 4.4.0-1041-aws #50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
./build/bin created with binary

#### Actual behaviour
no directory created, no binary created, errors after make

#### Steps to reproduce the behaviour
ubuntu@ip-172-31-45-199:~/open-ethereum-pool$ make
build/env.sh go get -v ./...
github.com/gorilla/context
github.com/gorilla/mux
github.com/ethereum/go-ethereum/common/hexutil
github.com/ethereum/go-ethereum/crypto/sha3
github.com/ethereum/go-ethereum/common
github.com/ethereum/go-ethereum/common/math
github.com/sammy007/open-ethereum-pool/util
gopkg.in/redis.v3/internal
gopkg.in/redis.v3/internal/consistenthash
gopkg.in/redis.v3/internal/hashtag
gopkg.in/bsm/ratelimit.v1
gopkg.in/redis.v3/internal/pool
gopkg.in/redis.v3
github.com/sammy007/open-ethereum-pool/storage
github.com/sammy007/open-ethereum-pool/api
github.com/sammy007/open-ethereum-pool/rpc
github.com/sammy007/open-ethereum-pool/payouts
github.com/sammy007/open-ethereum-pool/policy
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto/sha3
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/rlp
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto
github.com/ethereum/ethash/vendor/github.com/go-stack/stack
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/log
github.com/ethereum/ethash
github.com/sammy007/open-ethereum-pool/proxy
ubuntu@ip-172-31-45-199:~/open-ethereum-pool$ ls build/
env.sh  _workspace

#### Backtrace

````
[backtrace]
````

**Comment by mikeyb** [comment]
I don't see errors.  Perhaps you might include those if you want help FIXING YOUR ERRORS

**Comment by mikeyb** [comment]
My guess is you are using the ubuntu system nodejs, try using more recent version

**Comment by FRM7** [comment]
Hi Mikey.

It does not create any errors.  I am running v9.3.0. I run make and no binary gets built.

Do you have any suggestions as to what to try?

Kind regards,

Chris

**Comment by pgdaniel** [comment]
@FAIRMANNLTD install a newer version of go...I had the same issue, I'm running `1.9.2` now

**Comment by FRM7** [comment]
Hi Daniel,

Thank you for your assistance, I will try it out.

Kind regards,

Chris

**Comment by wildnrg** [comment]
updated to got 1.9.x has fixed this issue
