### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by ahrcoin** [sammy007/open-ethereum-pool#269]
I have everything up and running and cannot seem to get past one last issue.

I am attempting to serve the /dist folder using nginx but for some reason it does not seem that nginx has access to the root/open-ethereum-pool/www/dist folder.  I keep getting 404 not found even with the index.html file being located in that folder.  I know nginx is working correctly because I have no issue serving the default nginx webpage and have even copied the index.html from the /dist folder to the /usr/share/nginx/html and it worked to serve that file to my website.

I know this is not really a pool question but more of a nginx issue but I cannot seem to find anything searching for it on google or anywhere.

Thank you
Kris

**Comment by Nisefal** [comment]
Have you tried to check /sites-available and /sites-enabled folders? There should be file with configuration(sites-available) and link on this file(sites-enabled). Path to this folders: /etc/nginx/
If this helps, could you help with my issue please?) It's just before yours)

**Comment by ahrcoin** [comment]
That is where I am doing all my editing for the root directory and for some reason if I set the file location anywhere outside of /usr/share/nginx it says 404 not found.

**Comment by Nisefal** [comment]
Could you provide files from /etc/nginx/sites-available and from /etc/nginx/sites-enabled folders? Too few info yet)

**Comment by ahrcoin** [comment]
I figured it out.  It was a permissions issue with the user www-group which is specified in the nginx.conf file.
