### ISSUE TITLE
Not enough balance for payment

### ISSUE THREAD

**Issue by DhivinX** [sammy007/open-ethereum-pool#272]
#### System information

Geth version: Parity 1.7.11

Redis version: 3.0.6

OS & Version: Ubuntu Server 16.04 LTS

Log:
2018/01/08 10:55:06 Payments suspended due to last critical error: Not enough balance for payment, need 3983966320000000000 Wei, pool has 3811766063250276127 Wei

Then I must restart payouts and clear all miners balances in redis.
This happens several times a week.

What's wrong?

**Comment by sammy007** [comment]
Send some to pool in order to pay tx fees.
