### ISSUE TITLE
Invalid block revenue on ETC mining

### ISSUE THREAD

**Issue by LEVA1989** [sammy007/open-ethereum-pool#273]
#### System information

Geth version: v4.1.2

Redis version: Redis server v=4.0.6 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=2ccd058d3c795fdb

OS & Version: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-104-generic x86_64)

Commit branch and hash: (`master`, `bcfc0eb0e683993ad0c51bacad8d4b354e769393`)

#### Actual behaviour
Unlocker gets wrong amount from block.
for example pool found this blocks: http://gastracker.io/block/0xd3df18836a9b5fdcd66f673d3827ed251b416f659f2ed0f6c8bcf0ab1983403e
Miner Reward: 4.0000 Ether
and
http://gastracker.io/block/0xf78d54ad5300dd6714e08620fafb065583448eebc88685ab7e222106c10ae3b8
Miner Reward: 4.0580 Ether

but see unlocker log below:

> 2018/01/10 01:45:14 Mature block 5168929 with 0 tx, hash: 0xd3df1883
> 2018/01/10 01:45:15 Mature block 5171792 with 29 tx, hash: 0xf78d54ad
> 2018/01/10 01:45:15 Immature 2 blocks, 0 uncles, 0 orphans
> 2018/01/10 01:45:15 Inserted 0 orphaned blocks to backend

> 2018/01/10 01:45:15 IMMATURE 5168929:0xd3df18836a9b5fdcd66f673d3827ed251b416f659f2ed0f6c8bcf0ab1983403e: revenue 3.00000000, miners profit 2.97000000, pool profit: 0.03000000

>         REWARD 5168929:0xd3df18836a9b5fdcd66f673d3827ed251b416f659f2ed0f6c8bcf0ab1983403e: 0x2323c90ca1690a94e1541591ecd8e661c228247c: 2970000000 Shannon

> 2018/01/10 01:45:15 IMMATURE 5171792:0xf78d54ad5300dd6714e08620fafb065583448eebc88685ab7e222106c10ae3b8: revenue 3.05798591, miners profit 3.02740605, pool profit: 0.03057986

>         REWARD 5171792:0xf78d54ad5300dd6714e08620fafb065583448eebc88685ab7e222106c10ae3b8: 0x2323c90ca1690a94e1541591ecd8e661c228247c: 3027406051 Shannon

>2018/01/10 01:45:15 IMMATURE SESSION: revenue 6.05798591, miners profit 5.997406                                                                        05, pool profit: 0.06057986

**Comment by mvilera** [comment]
I'm not sure but I think that's happening because the pool has the bizantium fork reward hardcoded, that didn't happen in ETC, so the solution would be to look for the unlocker.go code where the reward is defined and replace using current ETC reward, although i'm not sure if it's as simple as that.

**Comment by sammy007** [comment]
It's because this is ethereum pool.
