### ISSUE TITLE
Docker image for this pool

### ISSUE THREAD

**Issue by vp993** [sammy007/open-ethereum-pool#276]
Hey, during the building of our pool on top of open-ethereum-pool we prepared docker image for this pool. What would you think if I sent PR with Dockerfile and documentation?

**Comment by steve-rodrigue** [comment]
Do you have the Dockerfile with a docker-compose for both the UI and API?  If yes, I'd love to see your files.  I was about to create them for a project of mine :)

Thanks in advance!

**Comment by sammy007** [comment]
I am against this idea.
