### ISSUE TITLE
Hardware sizing

### ISSUE THREAD

**Issue by ghost** [sammy007/open-ethereum-pool#279]
Hi all

What are the recommended specifications of the servers?
- Redis (in memory DB). Minimum memory size & growth per month.
- Geth. Minimum disk size & growth per month. Memory requirements.
- Pool. Minimum disk size & growth per month. Memory requirements.
- HDD or SSD?

I would like to use a redis cloud solution and a google compute engine VM instance to try out this software.

Cheers
-Luca.

**Comment by LeChuckDE** [comment]
Take the software, install it and write down the requirements...
