### ISSUE TITLE
Serve API over SSL not an easy possibility with proxy_pass?

### ISSUE THREAD

**Issue by bejsen** [sammy007/open-ethereum-pool#282]
In the last few days, I've been trying to get the API to serve over SSL.
I do not have problem to install SSL on nginx.

If i enable SSL the API stats aren't available. If disable SSL there is no problem at all.

I belive it's the proxy_pass there makes trouble with the SSL. Because i can't change it to https.
When change proxy_pass from http://api to https://api it will just be an nginx config error.

"host not found in upstream "api"

I did also try to leave proxy_pass http://api; and setup add
proxy_redirect http://api https//api

But this' did not solve the problem.

Maybe I have overlooked something

**Comment by bali105** [comment]
Hello, did you solved this issue? Having exactly the same problem with https

**Comment by mikeyb** [comment]
@bali105 what does your nginx configs look like?

EDIT: nevermind, i see your post in https://github.com/sammy007/open-ethereum-pool/issues/383#issuecomment-607266868
