### ISSUE TITLE
Malformed Stratum Request

### ISSUE THREAD

**Issue by ahrcoin** [sammy007/open-ethereum-pool#283]
#### System information

Geth version: Parity 1.8.6

Redis version: 4.0.6

OS & Version: Linux

Commit branch and hash: 

#### Expected behaviour

when running the pool config.json (payouts.json and unlocker.json not started) should get miners connect and pool starts sending out new work to them.

#### Actual behaviour
I am getting a large amount of "Malformed Stratum Request from IP #########. Invalid charater /x16 looking for beginning of value"

I am curious about what this means.

#### Steps to reproduce the behaviour
Installed pool and parity and set up all the config files as normal

#### Backtrace
2018/01/19 00:49:17 Stats collection finished 698.731µs
2018/01/19 00:49:20 Malformed stratum request from 176.83.234.120: invalid character '\x16' looking for beginning of value
2018/01/19 00:49:22 Stats collection finished 532.565µs
2018/01/19 00:49:27 Stats collection finished 704.587µs
2018/01/19 00:49:29 Malformed stratum request from 189.171.112.183: invalid character '\x16' looking for beginning of value
2018/01/19 00:49:32 Stats collection finished 561.276µs
2018/01/19 00:49:33 New block to mine on main at height 493
````
[backtrace]
````

**Comment by ghost** [comment]
I have seen these before. Would anyone have a reason to add your pool to a bot network?

**Comment by xenhim** [comment]
Me too . It's annoying to see it . how to fix ?

**Comment by sammy007** [comment]
> how to fix?

Just uninstall.

**Comment by xenhim** [comment]
> Just uninstall.

Is that a joke or are you upset with me? . If I'm sorry for the above question . Thank you

**Comment by sammy007** [comment]
You wanted to fix it, I said how. The only way to fix it is to uninstall because it's the only robust way to prevent people to connect to it by mistake using not a miner or incompatible miner, or a browser for example.

**Comment by xenhim** [comment]
> You wanted to fix it, I said how. The only way to fix it is to uninstall because it's the only robust way to prevent people to connect to it by mistake using not a miner or incompatible miner, or a browser for example.

oh. I do not have to keep asking this question. I only try sorry if that makes you uncomfortable. thank you

**Comment by ghost** [comment]
@xenhim I used to get 1,000s of these per day. Figured someone seeded some widely used software with my addresses because it doesn't happen on my other 8 pools while configuration being identical. I had my provider block the traffic based on packet sequence.

**Comment by xenhim** [comment]
@epoolio wow . Can you tell me what it is? Do not know what damn name is doing something 😢

**Comment by ghost** [comment]
Just had a miner report they couldn't connect. It seems they were dropped because of this Malformed request. Asking for more information on what software they are using. Hope to have more information soon.

**Comment by AnorakTech** [comment]
"Malformed Stratum Request from IP #########. Invalid charater /x16 looking for beginning of value" occurs when a worker tries to connect via SSL to a non-SSL port.

**Comment by aemet93** [comment]
summ

> You wanted to fix it, I said how. The only way to fix it is to uninstall because it's the only robust way to prevent people to connect to it by mistake using not a miner or incompatible miner, or a browser for example.

Hey, sammy. So, it is not possible to mock data for load testing? I have an issue after 1024 miners connected, it says too many open files. Trying to debug the place of problem, and want to try to load pool with fake machines. If you have any idea, will be cool.

**Comment by mikeyb** [comment]
@aemet93 look at your systems `ulimit` setting.  Most likely hitting max file descriptors if you max out at 1024

**Comment by aemet93** [comment]
<img width="1440" alt="screen shot 2018-09-24 at 16 07 57" src="https://user-images.githubusercontent.com/10106431/46351113-2a611b80-c65f-11e8-8947-15dc1f9b82f2.png">
<img width="925" alt="screen shot 2018-09-24 at 14 54 16" src="https://user-images.githubusercontent.com/10106431/46351128-2b924880-c65f-11e8-9e87-17a06956ebf4.png">

> @aemet93 look at your systems `ulimit` setting. Most likely hitting max file descriptors if you max out at 1024

thanks mikeyb. Already tried, ulimit ihave set to max. Thought problem is in creating a lot geth connections, but no, pool creating 2 connections, for main and for backup node. If you have any other ideas, highly appreciate. Thank you. Here is 2 screenshots with errors, maybe it could help to figure out. 

p.s I believe it is not correct place to discuss it. Can we chat somewhere, please?

**Comment by mikeyb** [comment]
Can you send me the output of these commands?
```
❯❯❯ cat /proc/sys/fs/file-max
6574823
❯❯❯ ulimit -n
1024
```

Feel free to email me on my github listed email address.  It still feels like a ulimit issue, perhaps the system didnt take a previous change?

**Comment by mikeyb** [comment]
[One time use discord invite](https://discord.gg/JuTuna) - much easier to reach me here
