### ISSUE TITLE
sgminer & open-ethereum-pool

### ISSUE THREAD

**Issue by windblown17** [sammy007/open-ethereum-pool#284]
Hello!
I tried to use this poll with genesismining/sgminer-gm 5.5.5
I see errors:
1. On request method "mining.subscribe" I see answer:
{
"code": -3,
"message": "Method not found"
}
2. On request method  "mining.authorize", same answer.
I change "mining.authorize" to  "eth_submitLogin" and after sucsesful login i have message
 
3. In miner log: Unknown stratum msg: {"id":0,"jsonrpc":"2.0","result":["0x715923862a934cb99c241496c4c533b5cd356594fccac6f4e903185b779f18a5","0x51e74ac038c9e3e66658ef25c1591
02238ecfd6ec09db5abc675fa9207530dad","0x0225c17d04dad2965cc5a02a23e254c0c3f75d9178046aeb27ce1ca574"]}

Can you test this pool with sgminer-gm?
Thank you.

**Comment by windblown17** [comment]
On request method "mining.subscribe"
I see answer:
 {
   "code": -3,
   "message": "Method not found"
}

**Comment by mikeyb** [comment]
Can you post the command you ran....Literally a useless issue report... Hint:  The pool works fine, you just don't know what you are doing.  Are using stratum protocol?

**Comment by windblown17** [comment]
Thank you for answer!
Yes, pool working fine with differents miners, but not with sgminer-gm.
I use stratum protocol

Samples of code:
 1. Request:
        sprintf(s, "{\"id\": %d, \"method\": \"mining.authorize\", \"params\": [\"%s\", \"%s\"]}",
      swork_id++, pool->rpc_user, pool->rpc_pass);
     Answer:
          Answer:  Unknown request method mining.subscribe from
        {
          "code": -3,
         "message": "Method not found"
       }


2. Request:
    sprintf(s, "{\"id\": %d, \"method\": \"mining.subscribe\", \"params\": []}", swork_id++);
                        or/and
    sprintf(s, "{\"id\": %d, \"method\": \"mining.subscribe\", \"params\": [\""PACKAGE"/"CGMINER_VERSION"\"]}", swork_id++);
   Answer:  Unknown request method mining.subscribe from
        {
          "code": -3,
         "message": "Method not found"
       }
3. Sgminer not understand (JSON parse error) replay like:
     {"id":0,"jsonrpc":"2.0","result":["0x715923862a934cb99c241496c4c533b5cd356594fccac6f4e903185b779f18a5","0x51e74ac038c9e3e66658ef25c1591
02238ecfd6ec09db5abc675fa9207530dad","0x0225c17d04dad2965cc5a02a23e254c0c3f75d9178046aeb27ce1ca574"]}

**Comment by Serpent6877** [comment]
That is Nicehash protocol. It is not supported on this pool.
