### ISSUE TITLE
Socket was closed remotely (by pool)

### ISSUE THREAD

**Issue by matrixkloud** [sammy007/open-ethereum-pool#287]
#### System information

Geth version: 1.7.3-stable
Redis version: 4.0.7

OS & Version: Linux/ubuntu 16.04 LTS 

I am expecting miner should connected to the pool. But I am getting error. 

#### Here is the error
ETH: Stratum - Connected (xxx.xxx.xxx.xxx:8888)
Socket was closed remotely (by pool)
ETH: Job timeout, disconnect, retry in 20 sec...

looking help from someone.

**Comment by wudics** [comment]
I have the same problem, did you fix it?

**Comment by matrixkloud** [comment]
I have used ip is:: 0.0.0.0 instead of 127.0.0.1.   It solved my issue.

**Comment by mikeyb** [comment]
Using 0.0.0.0 makes it listen on all interfaces, not just internal localhost.  If you are exposed to the internet, this is VERY BAD.  Make sure you use a very secure password to authenticate any requests to an externally open service.
