### ISSUE TITLE
Qtminer trouble unknow method

### ISSUE THREAD

**Issue by bayo31** [sammy007/open-ethereum-pool#29]
#### System information

Geth version:  last version stable
Redis version: last version stable

OS & Version: Linux/OSX ubuntu 14 lts

Commit branch and hash: master

I have 2 server running 2 version of proxy and both have trouble with qtminer

On  server A ( version a bit old like 20 day )  : Qtminer run is ok ( connected + share submit) but dont show stat on pool about this miner

On server B ( last version of github) : Qtminer get banned after 10 sec because of unknow method logs:

2016/06/07 06:41:40 Jobs broadcast finished 656ns
2016/06/07 06:41:45 Unknown request method eth_login from *.*.*.*
2016/06/07 06:41:48 Policy state refresh complete
2016/06/07 06:41:51 Unknown request method eth_login from *.*.*.*
2016/06/07 06:41:51 Banned 109.190.196.220 with timeout 1800 on ipset blacklist

I have try stop banning but still got this error 
Unknown request method eth_login 

Did you know something about this ??

**Comment by sammy007** [comment]
Not supported.
