### ISSUE TITLE
Unable to process payouts: authentication needed: password or unlock

### ISSUE THREAD

**Issue by wudics** [sammy007/open-ethereum-pool#298]
# System infomations

Pirl Version

OS & Version: ubuntu 16.04

# Issues
I have mined some block, and block is pending, I look in screen payout module, he said "Unable to process payouts: authentication needed: password or unlock", someone can tell me to fix it? and my password file do not have extral char like '\n'.

my pool is [http://pirl.sokuyun.cn/](http://pirl.sokuyun.cn/), looks fine, except balance pending.

my miner is [http://pirl.sokuyun.cn/#/account/0xff8806c00738d6cf16852d7022dfb61d6cf82545](http://pirl.sokuyun.cn/#/account/0xff8806c00738d6cf16852d7022dfb61d6cf82545)

# Startup script

```
#!/bin/bash

#Make sure no other pesky screens are running
killall screen
screen -wipe
sleep 1

cd /root/pirl-linux-amd64/
echo starting pirl
screen -LdmS pirl ./pirl --maxpeers 100 --rpc --rpcaddr "127.0.0.1" –-rpcapi "eth,net,web3" --unlock "0x03cb42164a498c019c0fc55acf59210b683ff09c" –-password "/root/pirl-linux-amd64/password"

#the file “/home/pirl/open-ethereum-pool/.walletpass” HAS to contain your wallet password, we did this though

sleep 10

cd /root/open-ethereum-pool/

#pool2b:
echo starting 2b pool
screen -LdmS pool ./build/bin/open-ethereum-pool pool2b.json

#pool9b:
echo starting 9b pool
screen -LdmS pirl-pool9b ./build/bin/open-ethereum-pool pool9b.json

#api:
echo starting API
screen -LdmS pirl-api ./build/bin/open-ethereum-pool api.json

#unlocker:
echo starting unlocker
screen -LdmS pirl-unlocker ./build/bin/open-ethereum-pool unlocker.json

#payout:
echo starting payout
screen -LdmS pirl-payout ./build/bin/open-ethereum-pool payout.json
```

# Config

my payout config and unlock confign like below:

```
"unlocker": {
    "enabled": false,
    "poolFee": 1.0,
    "poolFeeAddress": "0xff8806c00738d6cf16852d7022dfb61d6cf82545",
    "donate": false,
    "depth": 120,
    "immatureDepth": 5,
    "keepTxFees": true,
    "interval": "10m",
    "daemon": "http://127.0.0.1:6588",
    "timeout": "10s"
},

"payouts": {
    "enabled": true,
    "requirePeers": 25,
    "interval": "30m",
    "daemon": "http://127.0.0.1:6588",
    "timeout": "10s",
    "address": "0x03cb42164a498c019c0fc55acf59210b683ff09c",
    "gas": "21000",
    "gasPrice": "50000000000",
    "autoGas": true,
    "threshold": 1000000000,
    "bgsave": false
},
```

# Backtrace

Unable to process payouts: authentication needed: password or unlock

**Comment by xenhim** [comment]
need to unlock in geth or parity

**Comment by wudics** [comment]
but not working with --unlock or --password @xenhim

**Comment by xenhim** [comment]
You use pirl . you need unlock in ./pirl --unlock "xxxxx" --password "~/.password"

**Comment by xenhim** [comment]
pirl totally there. Please take a look at the tutorial

**Comment by wudics** [comment]
I already use this two params, but not working, in my startup script there are something wrong ? please help me to figure out

**Comment by xenhim** [comment]
check file passwork . was it correct path? . When the pirl run have see unlocked?

**Comment by wudics** [comment]
yes, it is the right path, I use below jsonrpc to check is correct or not : 
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sign","params":["0x03cb42164a498c019c0fc55acf59210b683ff09c", "0xdeadbeaf"],"id":1}' http://127.0.0.1:6588
```

when I use --unlock --password params , it is show account locked

when I use personal.unlockAccount in console model, it is show account unlock successfully

**Comment by xenhim** [comment]
Try a password.txt password file . when successfully unlocked. edit the content in the text file. Remove your password.

**Comment by wudics** [comment]
how to ?

**Comment by xenhim** [comment]
"nano password.txt" type password and save

restart ./pirl --maxpeers 100 --rpc --rpcaddr "127.0.0.1" –-rpcapi "eth,net,web3" --unlock "0x03cb42164a498c019c0fc55acf59210b683ff09c" –-password "/root/pirl-linux-amd64/password.txt"

**Comment by wudics** [comment]
hmmm, not working I just try, account still locks, it seems to ignore --unlock --password parameters

**Comment by wudics** [comment]
[solved] Thanks @xenhim , I fix it with recompiling the pirl source code and change the startup script like this:
```
screen -LdmS pirl ./pirl -maxpeers 100 -rpc -rpcaddr 127.0.0.1 -rpcapi eth,net,web3 -unlock 0x03cb42164a498c019c0fc55acf59210b683ff09c -password /root/pirl-linux-amd64/password
```
