### ISSUE TITLE
Previous payout failed, you have to resolve it.

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#299]
#### System information

Geth version:  Parity 1.8.6

Redis version: `redis-server --version`

OS & Version: Ubuntu 16.04

Commit branch and hash: (`master`, `ba60e1c`)

#### Actual behaviour
Running with payouts.json file produces this:

2018/02/20 09:19:33 Previous payout failed, you have to resolve it. List of failed payments:

#### Steps to reproduce the behaviour

I used Parity 1.8.9 for a while and I think payouts don't work with it.  Then I downgraded to 1.8.6 and so I have a pending payout.

When I look at the code I focus on this:
https://github.com/sammy007/open-ethereum-pool/blob/master/payouts/payer.go#L59

So I set the BASH environment variable RESOLVE_PAYOUT=1 before running both config.json and payouts.json.

Does anyone know the correct way to "resolve" a backlogged payout?

**Comment by sammy007** [comment]
Check out `docs/*.md`

**Comment by stone212** [comment]
Thank you.  It's funny.  I had already set the environment variable RESOLVE_PAYOUT=1 and it showed as 1 when I ran "echo $RESOLVE_PAYOUT" but this line works:

`RESOLVE_PAYOUT=1 ./build/bin/open-ethereum-pool payouts.json.`
