### ISSUE TITLE
./ether-pool config.json it give me error 

### ISSUE THREAD

**Issue by omjanu** [sammy007/open-ethereum-pool#3]
now when i type in ./ether-pool config.json it give me the error that
-bash: ./ether-pool: No such file or directory

**Comment by omjanu** [comment]
also when i type in the ip of my server i get this message Welcome to nginx on Debian!

If you see this page, the nginx web server is successfully installed and working on Debian. Further configuration is required.

For online documentation and support please refer to nginx.org

Please use the reportbug tool to report bugs in the nginx package with Debian. However, check existing bug reports before reporting a new bug.

Thank you for using debian and nginx.

so why i am not able to see the pool

**Comment by ExEric3** [comment]
Because you must learn nginx to handle api: [example](https://github.com/sammy007/open-ethereum-pool#serving-api-using-nginx)

**Comment by omjanu** [comment]
I am almost done with the pool i am just syuck with the front end it is not showing up

**Comment by omjanu** [comment]
Can any one help me with the front end

**Comment by sammy007** [comment]
I suggest to ask general installation questions to a people in a gitter chat https://gitter.im/sammy007/open-ethereum-pool
