### ISSUE TITLE
getsockopt: connection refused

### ISSUE THREAD

**Issue by nikhiljha** [sammy007/open-ethereum-pool#30]
#### System information

Geth version: `geth version` or commit hash if `develop`
Version: 1.4.5-stable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=/root/go
GOROOT=/usr/lib/go

Redis version: `redis-server --version`
Redis server v=3.2.0 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=3ceebb9e11c944d

OS & Version: Ubuntu 14.04 LTS running on a DigitalOcean Droplet ($10)

Commit branch and hash: Latest as of this issue, not sure how to check, sorry.

#### Expected behaviour
It works.

#### Actual behaviour
I'm not sure, googled around and it looks like it can't connect to the upstream thing.
Do I need to start geth before starting this?

#### Steps to reproduce the behaviour
Installed all dependencies then ran the commands given in README.md
exactly those commands, and edited config to enable the pool fee

#### Backtrace

root@sf1-core:~/open-ethereum-pool# ./ether-pool config.json
2016/06/08 20:57:43 Loading config: /root/open-ethereum-pool/config.json
2016/06/08 20:57:43 Running with 1 threads
2016/06/08 20:57:43 Backend check reply: PONG
2016/06/08 20:57:43 Starting payouts
2016/06/08 20:57:43 Set payouts interval to 2h0m0s
2016/06/08 20:57:43 No payees that have reached payout threshold
2016/06/08 20:57:43 Policy state refresh complete
2016/06/08 20:57:43 Set policy stats reset every 1h0m0s
2016/06/08 20:57:43 Set policy state refresh every 1m0s
2016/06/08 20:57:43 Running with 8 policy workers
2016/06/08 20:57:43 Upstream: main => http://127.0.0.1:8545
2016/06/08 20:57:43 Upstream: backup => http://127.0.0.2:8545
2016/06/08 20:57:43 Default upstream: main => http://127.0.0.1:8545
2016/06/08 20:57:43 Starting API on 0.0.0.0:8080
2016/06/08 20:57:43 Set stats collect interval to 5s
2016/06/08 20:57:43 Set purge interval to 10m0s
2016/06/08 20:57:43 Purged stale stats from backend, 0 shares affected, elapsed                                                                                                              time 536.184µs
2016/06/08 20:57:43 Stats collection finished 640.412µs
2016/06/08 20:57:43 Starting block unlocker
2016/06/08 20:57:43 Set block unlock interval to 10m0s
2016/06/08 20:57:43 Stratum listening on 0.0.0.0:8008
2016/06/08 20:57:43 Error while refreshing pending block on main: Post http://12                                                                                                             7.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/06/08 20:57:43 Error while refreshing pending block on main: Post http://12                                                                                                             7.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/06/08 20:57:43 Set block refresh every 120ms
2016/06/08 20:57:43 Starting proxy on 0.0.0.0:8888
2016/06/08 20:57:43 Unable to get current blockchain height from node: Post http                                                                                                             ://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/06/08 20:57:43 Unlocking suspended due to last critical error: Post http://                                                                                                             127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/06/08 20:57:43 Error while refreshing pending block on main: Post http://12                                                                                                             7.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/06/08 20:57:43 Error while refreshing pending block on main: Post http://12                                                                                                             7.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/06/08 20:57:43 Error while refreshing pending block on main: Post http://12                                                                                                             7.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused

**Comment by nikhiljha** [comment]
Wait nevermind, I just needed to start a geth node. Might want to add that to the readme :P

**Comment by joeglenn** [comment]
@nikhiljha Can you give any configuration info for the geth node?
