### ISSUE TITLE
Failed to get nodes stats from backend: redis: connection pool timeout

### ISSUE THREAD

**Issue by Marow** [sammy007/open-ethereum-pool#300]
Hi,

i get this error while running open-ethereum-pool for a while
`2018/02/21 13:36:36 Failed to get nodes stats from backend: redis: connection pool timeout`

**Comment by mvilera** [comment]
Use the template provided when you created the issue and fill the information required to help others identify your problem, with only that line I would check if redis is running properly and not crashing, also check if your api node has access and it's authorized to use your redis daemon.
