### ISSUE TITLE
Better Servers (more threads) for more users?

### ISSUE THREAD

**Issue by Marow** [sammy007/open-ethereum-pool#307]
Hi,

i had massive laggs with the open-ethereum-pool with over 100 users... If there much Workers you cannot open the Account Statistic Site.

So i want to fix and find the Problem. I look everywhere in the .go Files and cannot find anything wrong. Looks all good. But sometimes the log says redis connection failed or tcp errors.

So i want to ask if there is a list to find out, how much threads/cores my Root need for that to Fix that Problems.

I know thats not an issue like a "normal bug" but its a problem that all user gets when they have much users and only 2 threads.

**Comment by mikeyb** [comment]
You need to scale.  Add servers.  Load balance.  As with any web service that is under excess load.
