### ISSUE TITLE
Add stats user % of mined block

### ISSUE THREAD

**Issue by HelixiR** [sammy007/open-ethereum-pool#31]
Hi.

Can u add to miner account statistic page new tab with Round Share % of mined block?
All miners screaming to add this feature.

**Comment by sammy007** [comment]
I am working on extended stats, and one of planned addons will be a log of amounts credited to balance for each block. Not a percent, just amount. Don't think that percentage makes sense.

**Comment by HelixiR** [comment]
Okay. Waiting. ;)
