### ISSUE TITLE
cant start ./build.sh

### ISSUE THREAD

**Issue by itsmylife44** [sammy007/open-ethereum-pool#314]
cant start ./build.sh

./build.sh: line 3: ./node_modules/.bin/ember: No such file or directory

all installation are done ..

**Comment by mikeyb** [comment]
all installations are not done, as you can tell.  Use newer npm, read the docs, [try searching your error](https://github.com/sammy007/open-ethereum-pool/issues?utf8=%E2%9C%93&q=is%3Aissue+ember%3A+No+such+file+or+directory)

If you can't at least do this much, I would be very afraid to use your pool fwiw

**Comment by Jerry170617** [comment]
是国人不...

**Comment by Jerry170617** [comment]
帮忙回复一下#313的问题啊 大神们

**Comment by mikeyb** [comment]
Close your issue if this is resolved
