### ISSUE TITLE
How Many mh/s to resolve 1 block ? 

### ISSUE THREAD

**Issue by itsmylife44** [sammy007/open-ethereum-pool#316]
Hey guys , one question , how many mh/s you want to resolve 1 block ?

**Comment by mikeyb** [comment]
THIS ISSUE TRACKER IS FOR BUG REPORTING.  NOT LAZY PEOPLE WHO CANT GOOGLE.

THIS IS NOT A BUG.

You can solve a block with a pen and paper, so your question makes absolutely no sense.  Go learn
