### ISSUE TITLE
Not listening on Proxy and Stratum ports

### ISSUE THREAD

**Issue by wasiflaeeq** [sammy007/open-ethereum-pool#33]
I have installed the pool and it is not listening on the port 8888 and 8008. when checked, it says ports are closed. Firewall is also disabled.

To me, it looks like it is listening on ipv6...  I tried to add my IP in config file and it gives this error 2016/06/13 20:09:58 Failed to start proxy: listen tcp 130.211.144.117:8888: bind: cannot assign requested address

tcp6       0      0 :::8008                 :::*                    LISTEN
tcp6       0      0 :::8080                 :::*                    LISTEN
tcp6       0      0 :::80                   :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 :::8888                 :::*                    LISTEN
tcp6       0      0 :::30303                :::*                    LISTEN
tcp6       0      0 127.0.0.1:8080          127.0.0.1:46562         TIME_WAIT
tcp6       0      0 127.0.0.1:8080          127.0.0.1:46560         TIME_WAIT
tcp6       0      0 127.0.0.1:8080          127.0.0.1:46556         TIME_WAIT
tcp6       0      0 127.0.0.1:8080          127.0.0.1:46570         TIME_WAIT
tcp6       0      0 127.0.0.1:8080          127.0.0.1:46580         TIME_WAIT
tcp6       0      0 127.0.0.1:8080          127.0.0.1:46567         TIME_WAIT
tcp6       0      0 127.0.0.1:8080          127.0.0.1:46572         TIME_WAIT
tcp6       0      0 127.0.0.1:8080          127.0.0.1:46582         TIME_WAIT
tcp6       0      0 127.0.0.1:8080          127.0.0.1:46552         TIME_WAIT
tcp6       0      0 127.0.0.1:8080          127.0.0.1:46576         TIME_WAIT

**Comment by sammy007** [comment]
This message is pretty clear for me `listen tcp 130.211.144.117:8888: bind: cannot assign requested address`.

**Comment by sammy007** [comment]
Did you solve the problem btw? Looks like there is no such interface in your system with IP you specified.

**Comment by wasiflaeeq** [comment]
Thank you for the reply. I was not able to solve the problem. I agree that there was not the interface with that IP. It looks like traffic is being passed through proxy probably HA proxy and only IP assigned to system is private IP.  I enabled the reverse proxy option in config file and it still did not help. I was trying it on google cloud. I am going to arrange a physical server now to setup the pool there. What are the minimum hardware requirements I should look for? I am looking to accommodate around 100 workers.

**Comment by sammy007** [comment]
Just set it to "0.0.0.0" to bind to all available interfaces.

Reverse proxy option is only suitable for http endpoint behind haproxy or nginx, this option will extract X-Forwarded-For header to determine client's real IP. Your haproxy must properly set this header:

```
reqidel ^X-Forwarded-For:.* # force strip this header from client's X-Forwarded-For
option forwardfor # set client's IP to X-Forwarded-For
```

otherwise client cal forge value of `X-Forwarded-For` (check haproxy docs).

Pool is not greedy for RAM or CPU, geth is. So I suggest to run multi-core CPU and at least 8/16 GB RAM for geth with SSD. Log messages of geth which contains `Commit new work on block X ... Took ...` should not  exceed 20ms.

**Comment by sammy007** [comment]
Also, I invite you to set extradata to geth `geth --extradata "OpenEthereumPool/WHATEVER"` for the greater good. `WHATEVER` can be a geth version or something else, just don't exceed 32 ch. length. Thanks.

**Comment by wasiflaeeq** [comment]
ok, sure i will set the extradata.
