### ISSUE TITLE
Uncle Rewards ETC Mininig Pool

### ISSUE THREAD

**Issue by mobias** [sammy007/open-ethereum-pool#330]
Hi,

we are getting an incorrect block uncle reward (on ETC).
Everything works well on other blocks (around 4 ETC), but the uncle reward should be 0.125, not 3.
Am unable to find the correct parameter to change this?

Uncle Block:
https://gastracker.io/uncle/0x2adfc76a806043463ace9b9a01e4d5968b1aff03787b414dffb7a59802757eba
the result is that 3 etc is shared to all miners, but the pool received only 0.125.

how to fix this?
(I also tried the lechuckDE fork, but this one is even unable to unlock the blocks (wrong gas format error).

##### Request####
I don't understand what the error behind this if you have any solution please share your help will be appreciated also if you sure you can solve this issue please contact me I will pay you for your time.

#####Appologize#####
I know very well GitHub is not a helpdesk but I could not found any solution, please forgive.

Thanks 
MobiaS

**Comment by mikeyb** [comment]
Step 1.  Put crack pipe down
Step 2.  Turn off computer
Step 3.  If you insist on ignoring 1 & 2, do research, perhaps searching this repo for your answer.

Let me help: https://github.com/sammy007/open-ethereum-pool/issues/251#issuecomment-351806046

To accomplish this amazing feat of finding information, I put my cursor into the search field at the top of this page, typed the word 'uncle' and hit the Enter key.  Then I used my eyes to read the results, and in the results I found that post I just linked you to.  It took 4.5 seconds to accomplish.

**Comment by mobias** [comment]
I already read that. But there's not a proper answer so I decided to open a new issue can you please stop harassing everyone if you know the solution please post because everyone asking for it. I hope you understand. Why you kidding everyone please give a proper solution I promise that I will post it everywhere then no more issue about this.

Thanks For your 4.5 Sec.

**Comment by mikeyb** [comment]
Are you dense?  The answer was given, the exact, perfect, no other option exists answer.  In case your browser is broke:

`This pool is for ETH, you must patch unlocker for other coins yourself.`

Running financial service businesses require intelligence and knowledge of what you are doing.  You obviously do not know what you are doing, so until that time, you will be stuck with unpatched software.

You might consider hiring someone who knows what they are doing.

**Comment by mikeyb** [comment]
To all who need this patched.  I will do it for $500

**Comment by mobias** [comment]
I agree with you but I could not found a proper solution please read full post I also asked if somebody can solve this for me I will pay him for this time.

**Comment by mobias** [comment]
100$ is my offer if you will do then come.

**Comment by mobias** [comment]
Everything is working fine only issue with uncle blocks it shows 3 ETC instead of 0.123 ETC.

**Comment by mobias** [comment]
Here is the pool URL: https://etc.alhafeez.tech
You can check and contact me on facebook/WhatsApp/email whatever you want.

Thanks

**Comment by mikeyb** [comment]
My email is on my github profile if you need to contact me

**Comment by weldstech** [comment]
The solution is very simple and is an easy fix, problem here is no one reads the code to actually understand what the codes does.

**Comment by mobias** [comment]
I tried many times to read but don't understand properly. :(

**Comment by mobias** [comment]
@mikeyb please check your email.

from m.mobeen001@gmail.com

**Comment by da-tai** [comment]
Poor guy just needed direction

**Comment by mobias** [comment]
Please Help don't give arguments.

**Comment by mobias** [comment]
Please help :( @mikeyb I mailed you about 10 Hours ago but no reply please check mail and reply me. Thanks

**Comment by mobias** [comment]
Issue Solved Thanks Everyone :+1:

**Comment by hillbillie** [comment]
ThAnks, you closed the thread but you also promised to publish the solution.
Thanks for your contribution, close the thread with facts and code.
Rgds

**Comment by mobias** [comment]
Yea I promise to publish the solution if I got anything from here nobody gave me solution everybody talks shit someone needs money blah blah ...
Sorry, Guys I not got a solution from here. I bought  it in 300$ So, If anyone of you wants solution He/She can mail me So, I will give him/her solution (Not Free)

Thanks,
MobiaS
