### ISSUE TITLE
im newbie how to install open-ethereum pool for ubuntu 

### ISSUE THREAD

**Issue by mdikmetas** [sammy007/open-ethereum-pool#333]
im newbie how to install open-ethereum pool for ubuntu 

i need help 
im use to only local for solo my friends but  im search web youtube but i cant see install progress 

how i install.

**Comment by mikeyb** [comment]
piss off and read

**Comment by mdikmetas** [comment]
where i read

**Comment by RepoBike** [comment]
@mikeyb Please don't be a dick on github.  That's what Faceball's is for.

**Comment by mikeyb** [comment]
@RepoBike get over yourself, this isnt a help channel, it is a BUG TRACKER.  Learn to internet tardo

**Comment by mikeyb** [comment]
@mdikmetas In the god damn readme at the front of this repo

**Comment by digiuzman** [comment]
Don't mind a man named mikeyb..(maybe its wrong (monkeyb) )
(Türksün galiba ulaş yardımcı olayım hala pool kurmak istiyorsan.)

**Comment by mdikmetas** [comment]
@digiuzman nereden özel mesaj yazacağımı bulamadım kurdum yapıyı ancak mining de hata alıyorum
burada paylaştım : 
https://github.com/sammy007/open-ethereum-pool/issues/399 
nasıl ulaşabilirim size.

**Comment by digiuzman** [comment]
> @digiuzman nereden özel mesaj yazacağımı bulamadım kurdum yapıyı ancak mining de hata alıyorum
> burada paylaştım :
> #399
> nasıl ulaşabilirim size.

digiuzman@gmail.com buraya mail atabilirsen iletişim yardımcı olayım.
