### ISSUE TITLE
File open-ethereum-pool not found

### ISSUE THREAD

**Issue by PandemRus** [sammy007/open-ethereum-pool#338]
After build there is no bin folder in build. Clean Ubuntu 16.04

Log:
~/open-ethereum-pool$ make
build/env.sh go get -v ./...
github.com/gorilla/mux (download)
github.com/gorilla/context (download)
github.com/ethereum/go-ethereum (download)
Fetching https://gopkg.in/redis.v3?go-get=1
Parsing meta tags from https://gopkg.in/redis.v3?go-get=1 (status code 200)
get "gopkg.in/redis.v3": found meta tag main.metaImport{Prefix:"gopkg.in/redis.v3", VCS:"git", RepoRoot:"https://gopkg.in/redis.v3"} at https://gopkg.in/redis.v3?go-get=1
gopkg.in/redis.v3 (download)
Fetching https://gopkg.in/bsm/ratelimit.v1?go-get=1
Parsing meta tags from https://gopkg.in/bsm/ratelimit.v1?go-get=1 (status code 200)
get "gopkg.in/bsm/ratelimit.v1": found meta tag main.metaImport{Prefix:"gopkg.in/bsm/ratelimit.v1", VCS:"git", RepoRoot:"https://gopkg.in/bsm/ratelimit.v1"} at https://gopkg.in/bsm/ratelimit.v1?go-get=1
gopkg.in/bsm/ratelimit.v1 (download)
github.com/ethereum/ethash (download)
github.com/gorilla/context
github.com/ethereum/go-ethereum/common/hexutil
github.com/ethereum/go-ethereum/crypto/sha3
github.com/ethereum/go-ethereum/common/math
github.com/gorilla/mux
gopkg.in/redis.v3/internal
gopkg.in/redis.v3/internal/consistenthash
gopkg.in/redis.v3/internal/hashtag
gopkg.in/bsm/ratelimit.v1
gopkg.in/redis.v3/internal/pool
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1
gopkg.in/redis.v3
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto/sha3
github.com/ethereum/go-ethereum/common
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/rlp
github.com/sammy007/open-ethereum-pool/util
github.com/sammy007/open-ethereum-pool/rpc
github.com/ethereum/ethash/vendor/github.com/go-stack/stack
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/log
github.com/sammy007/open-ethereum-pool/storage
github.com/sammy007/open-ethereum-pool/api
github.com/sammy007/open-ethereum-pool/payouts
github.com/sammy007/open-ethereum-pool/policy
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto
github.com/ethereum/ethash
github.com/sammy007/open-ethereum-pool/proxy

**Comment by Astrates** [comment]
> Dependencies:
>     go >= 1.9

**Comment by PandemRus** [comment]
Thank You
