### ISSUE TITLE
API Config in Nginx??

### ISSUE THREAD

**Issue by zimbo123** [sammy007/open-ethereum-pool#34]
Hello, 

i have some Problems with the API in the ngnix.conf too. I don't know, if i configured it correct.
 Here is the part of the config-file:

server {
 listen 80;
 server_name Sub.domainname.com;
 }
 upstream api {
 server 127.0.0.1:8080;
 }
 location /api {
 proxy_pass http://api;
 }
 location / {
 proxy_pass http://localhost:8082;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header Host $http_host;
 proxy_set_header X-NginX-Proxy true;
    # Enables WS support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_redirect off;
 root    _/home/user/open-ethereum-pool/www/dist;_
}

Is that correct?
 For the configuration as a subdomain i must link in the Apache-Server to the Folder _/home/user/open-ethereum-pool/www/dist , is that correct?

Thank you very much.

Best regards 

Zimbo

**Comment by shenfeizi** [comment]
did you solve this problem yet?

**Comment by zimbo123** [comment]
Hello,

not really, is my config correct?
Thank you very much

**Comment by sammy007** [comment]
Example config is https://github.com/sammy007/open-ethereum-pool/blob/master/misc/nginx-default.conf

**Comment by shenfeizi** [comment]
@zimbo123 I already resolved this issue, per Sammy's instruction, let's go to https://gitter.im/sammy007/open-ethereum-pool to discuss this issue.
