### ISSUE TITLE
any solo mining tutorial ?

### ISSUE THREAD

**Issue by acathon** [sammy007/open-ethereum-pool#348]
Hey, does anyone know a possible way to setup Solo mining proxy on launched pool?

**Comment by mikeyb** [comment]
Setup pool, mine it...

**Comment by mikeyb** [comment]
Thumb my response down all you want, but you have a brick in your brain.  Your question actually answers your question.  Let me explain it in caps so an 8 year old can understand

SETUP A POOL, POINT IT AT OTHER POOL FOR WORK.  DONE.

Hard huh?  Thumb this down too you idiots.
