### ISSUE TITLE
Your Round Share 0%

### ISSUE THREAD

**Issue by AX-Turbo** [sammy007/open-ethereum-pool#35]
not directly an issue, but **always** a annoyance.

"Your round share" is maybe accurate after a hour or so. But it is unfair if pool finds two blocks within seconds and "Your round share" goes back to 0% after first block. A few seconds later second block is found, when top-above-average miner a) send his last share exceptionally "1 minute ago" and therefore gets nothing of 2nd block, bloody idle-miner b) send 2 or 3 shares in these seconds and make a fat haul. Top miner a) does it's (more) work of last 1-2 hours for nothing, lame miner b) makes a jig (for less work). Could be improved, however.

**Comment by sammy007** [comment]
Yes, it describes clearly that small miners should mine on small pools if they come for mid-term mining. On huge pools small miners loose a lot of rounds, it does not make any revenue hit long term, but those who are searching for a goldmine hopping from one pool to another always loose their profits eventually.

**Comment by HelixiR** [comment]
@sammy007 check pm on gitter pls.
