### ISSUE TITLE
Equihash

### ISSUE THREAD

**Issue by BaikalMine** [sammy007/open-ethereum-pool#352]
Hello! Is it possible to put on this assembly Equihash coin? I saw such pools (pool.sexy and 2miners) and unfortunately did not find any information :(

**Comment by atlanticcrypto** [comment]
I'm sure the dev would entertain selling it to you. I am certain it exists, but it is not cheap.

**Comment by sammy007** [comment]
> I am certain it exists, but it is not cheap

Correct.

Neither for sale nor for free. It does not make sense to run a public service if you can't do it yourself. It does not make sense to solo mine any of those coins as a hobbyist.

If zcash foundation will pay me for open sourcing it, I will, but not for less than $50,000 via bank transfer.
