### ISSUE TITLE
my blocks are not processed. they are located under New Block

### ISSUE THREAD

**Issue by djsmoke2018** [sammy007/open-ethereum-pool#364]
#### System information

Geth
Version: 1.8.12-stable
Go Version: go1.10
Operating System: linux

Redis version: `Redis server v=3.0.6`

OS & Version: Linux/OSX

{
        "redis": {
                "endpoint": "127.0.0.1:6379",
                "poolSize": 10,
                "database": 0,
                "password": ""
        },

        "unlocker": {
                "enabled": true,
                "poolFee": 1.0,
                "poolFeeAddress": "myadress",
                "donate": true,
                "depth": 120,
                "immatureDepth": 20,
                "interval": "10m",
                "daemon": "http://127.0.0.1:8545",
                "keepTxFees": false,
                "timeout": "10s"
                }
}

my blocks are not processed. they are located under New Block

I have executed unlocker.json

root@ETH:/var/www/html/open-ethereum-pool# ./build/bin/open-ethereum-pool unlocker.json
2018/07/29 20:55:50 Loading config: /var/www/html/open-ethereum-pool/unlocker.json
2018/07/29 20:55:50 Backend check reply: PONG
2018/07/29 20:55:50 Starting block unlocker
2018/07/29 20:55:50 Set block unlock interval to 10m0s
2018/07/29 20:55:50 No block candidates to unlock
2018/07/29 20:55:50 No immature blocks to credit miners

**Comment by poctek** [comment]
I recomend you to check if everything is OK with the geth node

**Comment by djsmoke2018** [comment]
i startet geth --rpc

INFO [07-29|21:23:38.423] Maximum peer count                       ETH=25 LES=0 total=25
INFO [07-29|21:23:38.423] Starting peer-to-peer node               instance=Geth/v1.8.12-stable-37685930/linux-amd64/go1.10
INFO [07-29|21:23:38.423] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=768 handles=512
INFO [07-29|21:23:39.062] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [07-29|21:23:39.063] Disk storage enabled for ethash caches   dir=/root/.ethereum/geth/ethash count=3
INFO [07-29|21:23:39.063] Disk storage enabled for ethash DAGs     dir=/root/.ethash               count=2
INFO [07-29|21:23:39.063] Initialising Ethereum protocol           versions="[63 62]" network=1
WARN [07-29|21:23:39.063] Head state missing, repairing chain      number=1 hash=8df219…09e297
INFO [07-29|21:23:39.063] Rewound blockchain to past state         number=0 hash=d4e567…cb8fa3
INFO [07-29|21:23:39.064] Loaded most recent local header          number=1 hash=8df219…09e297 td=34351349760
INFO [07-29|21:23:39.064] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [07-29|21:23:39.064] Loaded most recent local fast block      number=475169 hash=f1e62b…57d634 td=2505520639259542180
INFO [07-29|21:23:39.064] Loaded local transaction journal         transactions=0 dropped=0
INFO [07-29|21:23:39.064] Regenerated local transaction journal    transactions=0 accounts=0
INFO [07-29|21:23:39.065] Starting P2P networking 
INFO [07-29|21:23:41.589] UDP listener up                          self=enode://0907197af969208c9072d1f88558740e4637ff8dcca93f51a1a50a4387cbc0778fa026443b83a56d81756556cfd8008225cc86edbf5ac24bb140b92de70ed8d8@[::]:30303
INFO [07-29|21:23:41.589] RLPx listener up                         self=enode://0907197af969208c9072d1f88558740e4637ff8dcca93f51a1a50a4387cbc0778fa026443b83a56d81756556cfd8008225cc86edbf5ac24bb140b92de70ed8d8@[::]:30303
INFO [07-29|21:23:41.590] IPC endpoint opened                      url=/root/.ethereum/geth.ipc
INFO [07-29|21:23:41.590] HTTP endpoint opened                     url=http://127.0.0.1:8545    cors= vhosts=localhost
INFO [07-29|21:23:41.675] Etherbase automatically configured       address=Myadress
INFO [07-29|21:23:41.675] Starting mining operation 
INFO [07-29|21:23:41.675] Commit new mining work                   number=1      txs=0 uncles=0 elapsed=455.194µs
INFO [07-29|21:23:51.589] Block synchronisation started 
INFO [07-29|21:23:51.590] Mining aborted due to sync 
INFO [07-29|21:23:51.702] Network syncing, will start miner afterwards 
INFO [07-29|21:23:51.823] Network syncing, will start miner afterwards 
INFO [07-29|21:23:51.943] Network syncing, will start miner afterwards 
INFO [07-29|21:23:52.064] Network syncing, will start miner afterwards 
INFO [07-29|21:23:52.185] Network syncing, will start miner afterwards 
INFO [07-29|21:23:52.306] Network syncing, will start miner afterwards 
INFO [07-29|21:23:52.427] Network syncing, will start miner afterwards 
INFO [07-29|21:23:52.497] Network syncing, will start miner afterwards 
INFO [07-29|21:23:52.547] Network syncing, will start miner afterwards 
INFO [07-29|21:23:52.581] Imported new block headers               count=0 elapsed=2.743ms   number=475361 hash=4673a6…b6a489 ignored=192
INFO [07-29|21:23:52.668] Network syncing, will start miner afterwards 
INFO [07-29|21:23:52.779] Imported new block receipts              count=0 elapsed=185.022µs number=475176 hash=faf089…20eb8f size=0.00B ignored=7
INFO [07-29|21:23:52.789] Network syncing, will start miner afterwards 
INFO [07-29|21:23:52.910] Network syncing, will start miner afterwards

**Comment by poctek** [comment]
That's it. You need to wait for the full sync. You can check if geth is syncing via JSON RPC:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' 'http://127.0.0.1:8545'
```

**Comment by djsmoke2018** [comment]
when I execute I get an error message

invalid content type, only application/json is supported

**Comment by djsmoke2018** [comment]
my fault 
I have now started

 geth --rpc curl -X POST --data '{"jsonrpc": "2.0", "method": "eth_syncing", "params":[], "id":1}' 'http://127.0.0.1:8545''


root@ETH:~# geth --rpc curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' 'http://127.0.0.1:8545'
INFO [07-29|21:38:58.138] Maximum peer count                       ETH=25 LES=0 total=25
INFO [07-29|21:38:58.139] Starting peer-to-peer node               instance=Geth/v1.8.12-stable-37685930/linux-amd64/go1.10
INFO [07-29|21:38:58.139] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=768 handles=512
INFO [07-29|21:39:00.520] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [07-29|21:39:00.520] Disk storage enabled for ethash caches   dir=/root/.ethereum/geth/ethash count=3
INFO [07-29|21:39:00.520] Disk storage enabled for ethash DAGs     dir=/root/.ethash               count=2
INFO [07-29|21:39:00.520] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [07-29|21:39:00.521] Loaded most recent local header          number=2 hash=b495a1…4698c9 td=51514445824
INFO [07-29|21:39:00.521] Loaded most recent local full block      number=76170 hash=b95d93…8abdc1 td=97001573111884933
INFO [07-29|21:39:00.521] Loaded most recent local fast block      number=2     hash=b495a1…4698c9 td=51514445824
INFO [07-29|21:39:00.521] Loaded local transaction journal         transactions=0 dropped=0
INFO [07-29|21:39:00.521] Regenerated local transaction journal    transactions=0 accounts=0
WARN [07-29|21:39:00.521] Blockchain not empty, fast sync disabled
INFO [07-29|21:39:00.521] Starting P2P networking
INFO [07-29|21:39:02.881] UDP listener up                          self=enode://0907197af969208c9072d1f88558740e4637ff8dcca93f51a1a50a4387cbc0778fa026443b83a56d81756556cfd8008225cc86edbf5ac24bb140b92de70ed8d8@[::]:30303
INFO [07-29|21:39:02.881] RLPx listener up                         self=enode://0907197af969208c9072d1f88558740e4637ff8dcca93f51a1a50a4387cbc0778fa026443b83a56d81756556cfd8008225cc86edbf5ac24bb140b92de70ed8d8@[::]:30303
INFO [07-29|21:39:02.882] IPC endpoint opened                      url=/root/.ethereum/geth.ipc
INFO [07-29|21:39:02.882] HTTP endpoint opened                     url=http://127.0.0.1:8545    cors= vhosts=localhost
INFO [07-29|21:39:02.948] Etherbase automatically configured       address=myadress
INFO [07-29|21:39:02.948] Starting mining operation
INFO [07-29|21:39:02.948] Commit new mining work                   number=76171 txs=0 uncles=0 elapsed=181.312µs

**Comment by djsmoke2018** [comment]
the blocks are paid out or the shares are sent to the miner. after the syncronation

**Comment by djsmoke2018** [comment]
Okay, my problem is over. Thanks.
