### ISSUE TITLE
About possible issue .js

### ISSUE THREAD

**Issue by millenniumcm** [sammy007/open-ethereum-pool#367]
Hi dudes

Do you know about this file .....   .test.js.swp     ,  its a issue ? can i delete it ?  its about 141 GB !

https://imgup.cz/images/2018/08/01/screenshot2.png

**Comment by mikeyb** [comment]
.*.ext.swp is a swapfile from that file being edited.  If you don't need any changes in that swap file, you can delete it.  Not sure that is part of this software

**Comment by millenniumcm** [comment]
ok, thanks,
