### ISSUE TITLE
Parity Problem

### ISSUE THREAD

**Issue by djsmoke2018** [sammy007/open-ethereum-pool#368]
maybe someone can help me. I can't get any further.

i startet parity --rpc

root@ETH-Pool:/var/www/html/open-ethereum-pool# ./build/bin/open-ethereum-pool config.json
2018/08/02 15:33:27 Loading config: /var/www/html/open-ethereum-pool/config.json
2018/08/02 15:33:27 Running with 2 threads
2018/08/02 15:33:27 Backend check reply: PONG
2018/08/02 15:33:27 Starting API on 127.0.0.1:8080
2018/08/02 15:33:27 Set stats collect interval to 5s
2018/08/02 15:33:27 Set purge interval to 10m0s
2018/08/02 15:33:27 Policy state refresh complete
2018/08/02 15:33:27 Set policy stats reset every 1h0m0s
2018/08/02 15:33:27 Set policy state refresh every 1m0s
2018/08/02 15:33:27 Purged stale stats from backend, 0 shares affected, elapsed time 184.467µs
2018/08/02 15:33:27 Running with 8 policy workers
2018/08/02 15:33:27 Upstream: main => http://127.0.0.1:8545
2018/08/02 15:33:27 Upstream: backup => http://127.0.0.2:8545
2018/08/02 15:33:27 Default upstream: main => http://127.0.0.1:8545
2018/08/02 15:33:27 Stratum listening on 144.76.28.118:8008
2018/08/02 15:33:27 Stats collection finished 300.849µs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7610da]

goroutine 18 [running]:
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).fetchPendingBlock(0xc420194000, 0xc4200a00a0, 0xc420150000,                                                           0x44, 0xa0, 0x44)
        /root/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/blocks.go:106 +0x18a
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).fetchBlockTemplate(0xc420194000)
        /root/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/blocks.go:52 +0xc7
github.com/sammy007/open-ethereum-pool/proxy.NewProxy(0xcc46c0, 0xc42010ade0, 0xc420128280)
        /root/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/proxy.go:70 +0x474
main.startProxy()
        /root/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/main.go:26 +0x39
created by main.main
        /root/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool/main.go:94 +0x264
root@ETH-Pool:/var/www/html/open-ethereum-pool#

**Comment by terryxsq** [comment]
@djsmoke2018  did you fix it? if so how?

**Comment by mikeyb** [comment]
If you submit an issue, use the template it loads instead of deleting it.  People wonder why their issues go un-answered.  Why would anyone help you if you dont help us?  

https://github.com/sammy007/open-ethereum-pool#alternative-ethereum-implementations

STOP USING PARITY!!!

**Comment by stone212** [comment]
@djsmoke2018 Did you find a solution to this?  Obviously not using Parity is not practical for everyone.  Geth is must less sophisticated and does not handle all of the options Parity does.

**Comment by stone212** [comment]
@djsmoke2018 If you want help please give more info like mikeyb so politely said.  If it is fixed why not close the issue?
