### ISSUE TITLE
Running 2 Poolserver in the same machine (ETH & ETC)

### ISSUE THREAD

**Issue by millenniumcm** [sammy007/open-ethereum-pool#369]
Hi guys

I am trying running  2 poolserver (ETH & ETC); in the same machine, i wonder if it will be possible ?

Its possible running 2 nginx instances with upstream API, in differents ports,  do you have the .conf file  for share ?

Thanks!

P.d. i can run 2 instances , geth, redis and open-ethereum-pool

**Comment by mikeyb** [comment]
Just setup a second server entry in nginx -> https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf

**Comment by millenniumcm** [comment]
I have tried launching  2 nginx services.... and i got "duplicated upstream" error.... do you have the .conf file for share? thanks

**Comment by mikeyb** [comment]
so don't duplicate the upstream, create a second upstream and point it at second token pool

**Comment by mikeyb** [comment]
```
upstream etc {
  upstream info;
}
upstream eth {
  upstream info;
}
```

**Comment by millenniumcm** [comment]
this is my base config file:

-----------------------------------------------------------



upstream api {
    server 127.0.0.1:8080;
}

server {
    listen 80;
    server_name myethpool.dynu.net;
    root /home/poolserver/open-ethereum-pool/www/dist;
    index index.html index.htm;
    location / {
    try_files $uri $uri/ /index.html;
    }
    location /api {
        proxy_pass http://api;
    }
}

**Comment by millenniumcm** [comment]
do you mean  ?????????

----------------------------------------------------------------------------------------------------


upstream etc {
upstream api {
server 127.0.0.1:8081;
}

server {
listen 80;
server_name myetcpool.dynu.net;
root /home/poolserver/open-ethereum-pool-classic/www/dist;
index index.html index.htm;
location / {
try_files $uri $uri/ /index.html;
}
location /api {
proxy_pass http://api;
}
}
upstream eth {
  upstream api {
server 127.0.0.1:8080;
}

server {
listen 80;
server_name myethpool.dynu.net;
root /home/poolserver/open-ethereum-pool/www/dist;
index index.html index.htm;
location / {
try_files $uri $uri/ /index.html;
}
location /api {
proxy_pass http://api;
}
}

**Comment by mikeyb** [comment]
```
upstream eth {
  server 127.0.0.1:8080;
}
upstream etc {
  server 127.0.0.1:8081;
}
server {
  listen 80;
  server_name server.dns.eth;
  root /home/poolserver/open-ethereum-pool/www/dist;
  index index.html index.htm;
  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api {
    proxy_pass http://eth;
  }
server {
  listen 80;
  server_name server.dns.etc;
  root /home/poolserver/open-ethereum-pool/www/dist;
  index index.html index.htm;
  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api {
    proxy_pass http://etc;
  }
}
```
So creating a second upstream and server would be something like this...

**Comment by millenniumcm** [comment]
I will try  your code and come back with the feedback !  thanks!

**Comment by millenniumcm** [comment]
![nginxerror](https://user-images.githubusercontent.com/40300525/43813119-2f2e5804-9abc-11e8-8af3-b851daa9c5c4.png)

Hi,  i am having , **"server" directive is not allowed here**.........   error

I have 2 upstream in  base config ,    but  i dont figure how work out, this is my #nginx-conf

![nginxconf](https://user-images.githubusercontent.com/40300525/43813328-2453ca76-9abd-11e8-8164-79ec439a4d17.png)

**Comment by mikeyb** [comment]
put it in the http block [nginx docs are fantastic](https://www.nginx.com/resources/wiki/start/topics/examples/full/)

**Comment by millenniumcm** [comment]
I have put it in http block,  and still getting  ... **"server" directive is not allowed here**......... error   ,  i must add it in /etc/hosts  also  ?

**Comment by mikeyb** [comment]
put it in gist or something useful for us to look at

**Comment by millenniumcm** [comment]
Ok , now its working the 2 nginx,  thanks !

**Comment by mikeyb** [comment]
please close if working

**Comment by millenniumcm** [comment]
Just  reporting to me  a "conflict" warning  dns1   &  dns2  ,  0.0.0.0:port ,  but i think it will be solved easy,  thanks!

**Comment by mikeyb** [comment]
you probably are trying to bind to port 80 as a non root user

**Comment by millenniumcm** [comment]
at this moment, ...."dns1"  is working perfectly,    and "dns2"  its showing "500 Internal Server Error"

**Comment by mikeyb** [comment]
Those are variables which you havent set.  Try setting the variables if you want to use them.  Or set the dns manually, or remove the dns line altogether and let it use the system.  Im not here to play nginx tech support.  I suggest you seek the answers for system configuration elsewhere.  This issue tracker is for bugs, not support

**Comment by millenniumcm** [comment]
ok, thanks anyways!
