### ISSUE TITLE
wrong information

### ISSUE THREAD

**Issue by djsmoke2018** [sammy007/open-ethereum-pool#370]
my pool is displaying incorrect information.
 
ETH Blockchain information 

Network Difficulty: 17.171 G
 Network Hash Rate: 1.19 GH
 Blockchain Height: 1
 Current Round Variance: 35%

maybe someone can help me or give me a tip

**Comment by mikeyb** [comment]
Looks like you didnt sync the chain first.  ie. download the other blocks

**Comment by djsmoke2018** [comment]
i startet geth --fast --cache=1024

I've been waiting for days. How long does this take?


> eth.syncing
{
  currentBlock: 6086972,
  highestBlock: 6087055,
  knownStates: 93104600,
  pulledStates: 93096328,
  startingBlock: 6086924
}
>
