### ISSUE TITLE
Poll does not work

### ISSUE THREAD

**Issue by djsmoke2018** [sammy007/open-ethereum-pool#372]
#### System information####
Geth
Version: 1.8.12-stable
Architecture: amd64
Go Version: go1.10
Operating System: linux

Redis version: `redis-server --version`Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

OS & Version: Linux/OSX
Ubuntu 16.04

> eth.syncing
{
  currentBlock: 6094432,
  highestBlock: 6094505,
  knownStates: 67931170,
  pulledStates: 67908288,
  startingBlock: 4439155
}

Filesystem      Size  Used Avail Use% Mounted on
/dev/loop5      433G  109G  303G  27% /

 I startet geth --fast --cache=1024 and ./build/bin/open-ethereum-pool config.json

but I get false information from blockchain

 Network Difficulty: 17.171 G
 Network Hash Rate: 1.19 GH
 Blockchain Height: 1
 Current Round Variance: 326%

Aug 05 19:57:29 ETH open-ethereum-pool[5799]: 2018/08/05 19:57:29 Stats collection finished 394.121<C2><B5>s
Aug 05 19:57:34 ETH open-ethereum-pool[5799]: 2018/08/05 19:57:34 Stats collection finished 237.374<C2><B5>s
Aug 05 19:57:39 ETH open-ethereum-pool[5799]: 2018/08/05 19:57:39 Stats collection finished 396.465<C2><B5>s
Aug 05 19:57:44 ETH open-ethereum-pool[5799]: 2018/08/05 19:57:44 Stats collection finished 426.095<C2><B5>s
Aug 05 19:57:49 ETH open-ethereum-pool[5799]: 2018/08/05 19:57:49 Stats collection finished 549.273<C2><B5>s
Aug 05 19:57:54 ETH open-ethereum-pool[5799]: 2018/08/05 19:57:54 Stats collection finished 363.023<C2><B5>s
Aug 05 19:57:59 ETH open-ethereum-pool[5799]: 2018/08/05 19:57:59 Stats collection finished 517.803<C2><B5>s
Aug 05 19:58:04 ETH open-ethereum-pool[5799]: 2018/08/05 19:58:04 Stats collection finished 317.724<C2><B5>s
Aug 05 19:58:09 ETH open-ethereum-pool[5799]: 2018/08/05 19:58:09 Stats collection finished 545.296<C2><B5>s
Aug 05 19:58:14 ETH open-ethereum-pool[5799]: 2018/08/05 19:58:14 Stats collection finished 323.326<C2><B5>s

what am I doing wrong. can someone perhaps give me an idea.

**Comment by mvilera** [comment]
the result of eth.syncing iirc should be false, since it's showing information it means it's still syncing, if your geth/parity node is still syncing it can provide work for the pool to work.
