### ISSUE TITLE
Stale/Invalid Shares.  Also miners do not show in UI.

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#374]
#### System information

Geth version: Parity v1.10.8-stable

Redis version: Redis server v=3.0.6

OS & Version: Ubuntu 16.04

Commit branch and hash: master

#### Expected behaviour

After `Stratum miner connected` message in console I expect to see two things:

1. *Valid* shares.
2. The miner shows up in the UI.

#### Actual behaviour

But instead I see `Invalid share from <Address>` and the miner does not show up in the UI

This is strange.  I would think that even if the *shares* are invalid that the *miner* (which the console says is connected) would show up in the UI.  Maybe with an error next to it.

#### Steps to reproduce the behaviour

Set up the pool.  Connect two stratum miners.  Let it run for a while.  It seems great!  Sometimes the miners disconnect and reconnect (problem with miners).  Then one day the situation described above start to happen. 
#### Backtrace

````
[backtrace]
````

**Comment by mikeyb** [comment]
use develop branch of this repo for parity stable

**Comment by stone212** [comment]
That solved the problem.  Thank you.
