### ISSUE TITLE
Error running dual Poolserver ETH & ETC  in the same machine

### ISSUE THREAD

**Issue by millenniumcm** [sammy007/open-ethereum-pool#375]
Hi guys i am trying running dual poolserver (ETH  & ETC) in the same machine,  ETH pool is running perfectly,   Nginx servers are running

But when i launch  ./open-ethereum-pool  config.json   for running ETC pool,  i am gotting this error:

"  **2018/08/09 22:19:52 Error while refreshing pending block on main: Post http://127.0.0.1:8544: dial tcp 127.0.0.1:8544: connect: connection refused**
"

config.json  in ETH is setup at 8545   and  in ETC config.json is 8544

**_config.json in ETH_**
   // Geth instance node rpc endpoint for unlocking blocks
    "daemon": "http://127.0.0.1:8545",

**_config.json in ETC_**
   // Geth instance node rpc endpoint for unlocking blocks
    "daemon": "http://127.0.0.1:8544",

**Comment by mikeyb** [comment]
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour


#### Actual behaviour


#### Steps to reproduce the behaviour


#### Backtrace

````
[backtrace]
````

**Comment by millenniumcm** [comment]
¿?

**Comment by mikeyb** [comment]
Thats the stuff you deleted when you created the issue..  Might wanna post your config as well as what was requested.

**Comment by mikeyb** [comment]
The error you are getting means geth rpc is not running on 8544.  You need to fix your geth setup

**Comment by millenniumcm** [comment]
I am running  geth  with   --port 30304 --rpcport 8544   , for ETC poolserver......

ETH poolserver is running perfectly at  port 30303 and  rpcport 8545 

But still getting error with geth (ETC), at launching

I have opened both ports in the router  (8545  & 8544)

**Comment by millenniumcm** [comment]
this is my config.json  (ETC)


{
	"threads": 2,
	"coin": "etc",
	"name": "main",

	"proxy": {
		"enabled": true,
		"listen": "0.0.0.0:8887",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 20000000000,
		"hashrateExpiration": "3h",

		"healthCheck": true,
		"maxFails": 100,

		"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8007",
			"timeout": "120s",
			"maxConn": 8192
		},

		"policy": {
			"workers": 8,
			"resetInterval": "60m",
			"refreshInterval": "1m",

			"banning": {
				"enabled": false,
				"ipset": "blacklist",
				"timeout": 1800,
				"invalidPercent": 30,
				"checkThreshold": 30,
				"malformedLimit": 5
			},
			"limits": {
				"enabled": false,
				"limit": 30,
				"grace": "5m",
				"limitJump": 10
			}
		}
	},

	"api": {
		"enabled": true,
		"purgeOnly": false,
		"purgeInterval": "10m",
		"listen": "0.0.0.0:8081",
		"statsCollectInterval": "5s",
		"hashrateWindow": "30m",
		"hashrateLargeWindow": "3h",
		"luckWindow": [64, 128, 256],
		"payments": 30,
		"blocks": 50
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://127.0.0.1:8544",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://127.0.0.2:8544",
			"timeout": "10s"
		}
	],

	"redis": {
		"endpoint": "127.0.0.1:6380",
		"poolSize": 10,
		"database": 0,
		"password": ""
	},

	"unlocker": {
		"enabled": true,
		"poolFee": 0.05,
		"poolFeeAddress": "0x0",
		"depth": 120,
		"immatureDepth": 20,
		"keepTxFees": false,
		"interval": "10m",
		"daemon": "http://127.0.0.1:8544",
		"timeout": "10s"
	},

	"payouts": {
		"enabled": true,
		"requirePeers": 12,
		"interval": "120m",
		"daemon": "http://127.0.0.1:8544",
		"timeout": "10s",
		"address": "0x0",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500000000,
		"bgsave": false
	},

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}

**Comment by mikeyb** [comment]
Have you verified you have geth running on 8544.  Like I previously said, it wasn't running according to your error.  Check the processes, check your ports in use `netstat -tapn|grep LIST` (paste this to me, it will show if your 8544 port is actually in use, ie. geth is running properly)

**Comment by millenniumcm** [comment]
Hi this my  netstat  ,  and this is my geth (ETC),  command line:

`sudo ./geth --datadir /root/.ethereum-classic --fast --cache=1024 --port 30304 --rpcport 8544 --unlock 0x0.........`


tcp        0      0 127.0.0.1:8545          0.0.0.0:*               LISTEN      2926/geth           
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      2755/redis-server 1 
tcp        0      0 127.0.0.1:6380          0.0.0.0:*               LISTEN      2767/redis-server 1 
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1269/nginx: master  
tcp        0      0 127.0.0.1:5939          0.0.0.0:*               LISTEN      1325/teamviewerd    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      840/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1309/sshd           
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      3891/cupsd          
tcp6       0      0 :::30304                :::*                    LISTEN      3241/./geth         
tcp6       0      0 :::8008                 :::*                    LISTEN      2949/./build/bin/op 
tcp6       0      0 :::8080                 :::*                    LISTEN      2949/./build/bin/op 
tcp6       0      0 :::80                   :::*                    LISTEN      1269/nginx: master  
tcp6       0      0 :::22                   :::*                    LISTEN      1309/sshd           
tcp6       0      0 ::1:631                 :::*                    LISTEN      3891/cupsd          
tcp6       0      0 :::8888                 :::*                    LISTEN      2949/./build/bin/op 
tcp6       0      0 :::30303                :::*                    LISTEN      2926/geth

**Comment by mikeyb** [comment]
Yeah.  You arent telling geth to run rpc

https://github.com/ethereumproject/go-ethereum#programatically-interfacing-geth-nodes

**Comment by millenniumcm** [comment]
sudo ./geth --datadir /root/.ethereum-classic --fast --cache=1024 --port 30304 -**_-rpcport_** 8544 --unlock 0x0.........



**_--rpc-port_**     (maybe for one dash  ??)

**Comment by millenniumcm** [comment]
I am launching now......

`sudo ./geth --datadir /root/.ethereum-classic --fast --cache=1024 --port 30304 --rpc-port 8544 --unlock 0x0-----`

and appear.....   netstats

tcp        0      0 127.0.0.1:8545          0.0.0.0:*               LISTEN      2926/geth           
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      2755/redis-server 1 
tcp        0      0 127.0.0.1:6380          0.0.0.0:*               LISTEN      2767/redis-server 1 
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1269/nginx: master  
tcp        0      0 127.0.0.1:5939          0.0.0.0:*               LISTEN      1325/teamviewerd    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      840/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1309/sshd           
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      3891/cupsd          
tcp6       0      0 :::30304                :::*                    LISTEN      5564/./geth         
tcp6       0      0 :::8008                 :::*                    LISTEN      2949/./build/bin/op 
tcp6       0      0 :::8080                 :::*                    LISTEN      2949/./build/bin/op 
tcp6       0      0 :::80                   :::*                    LISTEN      1269/nginx: master  
tcp6       0      0 :::22                   :::*                    LISTEN      1309/sshd           
tcp6       0      0 ::1:631                 :::*                    LISTEN      3891/cupsd          
tcp6       0      0 :::8888                 :::*                    LISTEN      2949/./build/bin/op 
tcp6       0      0 :::30303                :::*                    LISTEN      2926/geth 



ETC geth command   is working the port part  (30304)  but   RPCport is not working (8544)

Do you know what would be the correct command line for geth (ETC) ?  thanks!

**Comment by mikeyb** [comment]
1.  You need to read the link I sent you and look at **ALL** the RPC options (you are forgetting one).
2.  That error means you have an instance of geth running, kill it before trying to start another

**Comment by millenniumcm** [comment]
1.     

--rpc  Enable the HTTP-RPC server
--rpc-addr HTTP-RPC server listening interface (default: "localhost")
--rpc-port HTTP-RPC server listening port (default: 8545)

I think iam not missing rpcport !?.... launching now....

`./geth --datadir /root/.ethereum-classic --rpcport 8544 --port 30304 --unlock 0x0.......`


2.

My ETH instance is working perfectly..... but i dont know why ETC instance dont want work RPC...!

3. Netstat  .. works  2 redis  , 2 nginx  and also in GETH  works  (8545, 30303 , 30304 ....)  but not 8544   ?????

**Comment by millenniumcm** [comment]
Ok...... i workout the  geth command......

`sudo ./geth --datadir /root/.ethereum-classic --rpc --rpcport 8544 --port 30304 --unlock 0x0...`

Now its working !
