### ISSUE TITLE
Soft fork and gas usage

### ISSUE THREAD

**Issue by General-Beck** [sammy007/open-ethereum-pool#39]
Dear owners of pools!
You should warn your users that they did not use accounts with contracts. This is the main reason for a safe transition to soft fork in the next week.
Pools are encouraged to use 30k gas for payouts which should ensure smooth operation during the soft fork.
#### System information

Geth version: `geth version` 1.4.8
Parity version : `parity version` 1.2.0+

OS & Version: Linux/OSX

**Comment by sammy007** [comment]
Pools must suspend payouts and block unlocking during transition or temporarily set `depth` to some high value like 32768.

**Comment by 9600-** [comment]
Is this valid considering the recent release and current trend forward?

**Comment by General-Beck** [comment]
@9600- 
Soft-fork failed. But in order to save funds when payments are made, the parameter "depth" to be useful.
