### ISSUE TITLE
Any plans to update npm packages for pool frontend?

### ISSUE THREAD

**Issue by ghost** [sammy007/open-ethereum-pool#390]
@sammy007

**Comment by DavidDah** [comment]
It's not possible to build frontend on ubuntu 18.04 LTS due to outdated npm packages.

**Comment by ghost** [comment]
@dzevadhadzic Same here 😂

**Comment by mikeyb** [comment]
You should be using NVM to install specific npm versions.  Ubuntu has always shipped with old ass npm versions.  This has nothing to do with this repo.

If you want npm packages updated, make a PR.  @sammy007 said in https://github.com/sammy007/open-ethereum-pool/issues/386#issue-357225637 he has no time.  So if you want updated packages, flip the bits you deem necessary and make a PR.

@dzevadhadzic your issue has nothing to do with this repo, you need to use nvm like every other dev

**Comment by ghost** [comment]
@mikeyb I am feature requesting cause I have no time to commit changes for the requested changes.

Are you @sammy007's sub account or why are you bothering for this??

**Comment by ghost** [comment]
@mikeyb Please delete your comments lol, I think origjnal author has a responsibility to fix his big on repo

**Comment by sammy007** [comment]
> author has a responsibility

My only responsibility is to put meat on the table. And definitely not on your table. If you are running a for profit service you must do it for yourself and stop requesting me.

Told many times this project is on life support.
