### ISSUE TITLE
Any plans to support multiple API endpoint for pool frontend??

### ISSUE THREAD

**Issue by ghost** [sammy007/open-ethereum-pool#392]
Related with https://github.com/sammy007/open-ethereum-pool/issues/5

**Comment by mikeyb** [comment]
https://github.com/sammy007/open-ethereum-pool/issues/386#issue-357225637 feature requests should be submitted as PRs

**Comment by ghost** [comment]
@mikeyb I am feature requesting cause I have no time to commit changes for the requested changes.

Are you @sammy007's sub account or why are you bothering for this??
