### ISSUE TITLE
Using for solo mining

### ISSUE THREAD

**Issue by KentaOnline** [sammy007/open-ethereum-pool#398]
Please how to use the pool for solo mining service?

Thanks.

**Comment by mikeyb** [comment]
https://github.com/sammy007/open-ethereum-pool/blob/master/README.md

**Comment by KentaOnline** [comment]
Thank you, I read this many times but I don't find where I can change PPLNS reward to SOLO. Thanks for helping.

**Comment by mikeyb** [comment]
You just mine it by yourself

**Comment by KentaOnline** [comment]
Yes of course, but what if I want to create a solo-mining pool?

**Comment by mikeyb** [comment]
Setup pool, mine it by yourself.  THAT IS A SOLO POOL

**Comment by KentaOnline** [comment]
Sorry to insist but you seem not to get my point, I want to create a solo mining pool where people can mine together but only the one who solves the block gets the reward, like many other pools do

**Comment by mikeyb** [comment]
That is not a solo pool.  Solo = 1
You need to alter the code, or use different software. This is a PPLNS pool software

**Comment by mikeyb** [comment]
```
Solo (Noun):
a performance in which the performer has no partner or associate : something undertaken or done alone 
Solo (Adverb)
without a companion
```
See where I might get confused by the incorrect usage of the word solo?

**Comment by KentaOnline** [comment]
Thank you for the academic lesson, does it mean that you don’t know the answer?

**Comment by mikeyb** [comment]
DID YOU READ MY ANSWER???????????????????????

**Comment by mikeyb** [comment]
You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software
 You need to alter the code, or use different software. This is a PPLNS pool software

a bunch more copies of it in case you missed it the first time..

**Comment by KentaOnline** [comment]
You are very just very rude

**Comment by KentaOnline** [comment]
Thank you and bye

**Comment by mikeyb** [comment]
Sorry English language confuses you.  Sorry the answer was not the one you wanted.  Let me know where you blog about your experience

**Comment by KentaOnline** [comment]
This is a public place where people come to learn. The attitude of shouting is certainly inappropriate. There are pools using this software and reward “solo” mining, like, for example, clona.org . I guess the instructions are in other modules of the software to be modified before running build.sh but I might be wrong as well. If anybody can help it would be highly appreciated. Thank you.

**Comment by mikeyb** [comment]
Yet you get mad when I educate you.  Like I said MODIFY THE SOFTWARE if you want it to WORK DIFFERENTLY.  This is a PPLNS POOL.  I literally can't make it any more clear for someone who doesnt understand this technology at all

**Comment by KentaOnline** [comment]
People can check out the pool that I am building @ 
http://172.104.145.150/#/ please do not mine there because payments are disabled. I will need more help and I hope to find a fair support.

**Comment by KentaOnline** [comment]
Mikeyb, please don’t educate me, I am not a child

**Comment by mikeyb** [comment]
`This is a public place where people come to learn`

**Comment by KentaOnline** [comment]
You can teach, but I don’t need Education, I don’t shout..... I am closing this because it’s going nowhere, or maybe there is interest of retaining the knowledge and that’s the reason

**Comment by hillbillie** [comment]
MikeyB was not rude at all:
https://coinguides.org/pps-vs-pplns/

I hope the above clarification helps you

**Comment by KentaOnline** [comment]
I still feel like he was quite rude, despite your comment. I know all the stuff written in the article you sent, I am looking for the way to reward the miner who found the block using the pool. I will find the solution, as I always do. I was just hoping to find support, but I did not. Best. Kenta.

**Comment by mikeyb** [comment]
This isnt a support tracker, it is an ISSUE TRACKER.  I also gave you the exact same answer after we clarified your mis-understanding English.  So yes, you do need education, obviously.  It is about as clear as day.  When I provided the education, you asked again as if I didnt answer.  That is when I got annoyed and you felt attacked.  THIS IS A BUG ISSUE TRACKER.  NOT YOUR HELPDESK TO CODE

**Comment by KentaOnline** [comment]
You guys are just pathetic. I am sorry for you. You were the one to feel attacked and responded in a rude way, shouting and treating me like a child, I guess that’s the way it works in Vietnam. By the way, you did not answer the question, probably because you cannot. In any case, you are allowed to have the last word, as you abviously need to..... good luck.

**Comment by marts2007** [comment]
Guys, are you sure that it IS PPLNS pool and not PROP?
since i have found this ticket with information that it was PROP pool in 2016 https://github.com/sammy007/open-ethereum-pool/issues/96
