### ISSUE TITLE
Frontend Temporarily Down

### ISSUE THREAD

**Issue by mmitech** [sammy007/open-ethereum-pool#4]
I can't  get the frontend to work, and I know that the problem has to do with my nginx config.

```
upstream api {
    server 127.0.0.1:8080;
}

server {
    listen 80;
    #listen 443 ssl;
    #ssl_certificate /etc/nginx/ssl/nginx.crt;
    #ssl_certificate_key /etc/nginx/ssl/nginx.key;


    server_name localhost;





    location /api {
        proxy_pass http://api;
    }

    location / {
        proxy_pass http://localhost:8082;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        # Enables WS support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
    }

}
```

**Comment by sammy007** [comment]
After ./build.sh within `www` folder you will have `www/dist` folder with static website generated. U must serve it as static website:

    location / {
        root    /path/to/www/dist;
    }

Edit your / location properly. if you see "frontend is down" look at js console in browser for errors.

And as i said, don't use `ember server ...` in production.

**Comment by mmitech** [comment]
Ok, got it, thank you.

**Comment by sammy007** [comment]
To make it clear, browser will poll api from client browser, if you see "frontend down" inspect errors using built in browser development tools, you will see a reason why you can't access API in js console. Api must be available on `your.domain/api/stats`. You can even bind api in config to 0.0.0.0 and don't configure nginx upstream for it.

**Comment by mmitech** [comment]
I will try it as soon as I get access to the server again, will reply/close this issue when I fix the problem. 
Thanks.

**Comment by mmitech** [comment]
Fixed, Thanks.

**Comment by zimbo123** [comment]
Hello, 

i have some Problems with the API in the ngnix.conf too. I don't know, if i configured it correct.
Here is the part of the config-file:

server {
     listen       80;
     server_name  _Sub.domainname.com_;
}
upstream api {
    server 127.0.0.1:8080;
}
location /api {
    proxy_pass http://api;
}
location / {
        proxy_pass http://localhost:8082;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        # Enables WS support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
	 root    _/home/user/open-ethereum-pool/www/dist;_
    }


Is that correct?
For the configuration as a subdomain i must link in the Apache-Server to the Folder _/home/user/open-ethereum-pool/www/dist , is that correct?

Thank you very much.

Best regards 

Zimbo

**Comment by goodthebest** [comment]
@mmitech can you please tell how did you fix it? I'm having exactly the same issue as you did.
