### ISSUE TITLE
Community: Whitelist Protocol Ideas?

### ISSUE THREAD

**Issue by stone212** [sammy007/open-ethereum-pool#402]
I see a way to blacklist IP addresses.  Has anyone used a reverse tactic where you only whitelist particular IP addresses?  How did you accomplish it?

**Comment by Jlonghi** [comment]
Set your firewall to block incoming requests from anything but your whitelisted IP's on the stratum port

**Comment by stone212** [comment]
@Jionghi That is a method sure.  I wanted to do it in the software because the person who runs the mining software will not have root access to the server.

**Comment by stone212** [comment]
I will close this because I do not think it is possible in the software.  @Jlonghi gave the suggestion that I am using: whitelist portsa 8008 and 8888 (or whatever ports you use) to only specific IP.
