### ISSUE TITLE
Need help to setup a pool liker wtcpool.net (for wtc)

### ISSUE THREAD

**Issue by VercauterenK** [sammy007/open-ethereum-pool#403]
Hi,

All i know its not really an issue but i am willing to pay for someone who could setup a pool like wtcpool.net . Yes i know that the pool is a scam but, at least it works on his wallet adres. So what i need is the same pool buth with my private key on it.
Willing to pay a reasonable price.

Thanks in advance all.

**Comment by minernl** [comment]
hey do you need help to set it up completely like daemon and pool.
i run my own pools so should be no problem.

**Comment by VercauterenK** [comment]
The guy off wtcpool.net <http://wtcpool.net/> has a pool were you can mine wtc the only problem is that he uses his account.
So after the token swap i get nothing.

we are willing to pay for an exact copy off wtcpool.net <http://wtcpool.net/> but just that the miner adres is mine adres.

**Comment by minernl** [comment]
you got mail... you can remove you mail address so you do not receive spam

**Comment by weldstech** [comment]
> 
> 
> Hi,
> 
> All i know its not really an issue but i am willing to pay for someone who could setup a pool like wtcpool.net . Yes i know that the pool is a scam but, at least it works on his wallet adres. So what i need is the same pool buth with my private key on it.
> Willing to pay a reasonable price.
> 
> Thanks in advance all.

Hit me up and i can build you a full pool with frontend and backend, any coin and our frontend is custom

**Comment by VercauterenK** [comment]
> > Hi,
> > All i know its not really an issue but i am willing to pay for someone who could setup a pool like wtcpool.net . Yes i know that the pool is a scam but, at least it works on his wallet adres. So what i need is the same pool buth with my private key on it.
> > Willing to pay a reasonable price.
> > Thanks in advance all.
> 
> Hit me up and i can build you a full pool with frontend and backend, any coin and our frontend is custom

How much do you ask for setting up my a pool for wtc with my mining account.

**Comment by VercauterenK** [comment]
Offering 1BTC for the guy who could make me a pool  today with my wallet for mining wtc...

**Comment by weldstech** [comment]
> 
> 
> Offering 1BTC for the guy who could make me a pool today with my wallet for mining wtc...

check your email
