### ISSUE TITLE
very high round variance

### ISSUE THREAD

**Issue by rastko1996** [sammy007/open-ethereum-pool#41]
Hey, there has been very high round variance lately.. around 500% what can be done about that?
Pool has around 2GH, and yet no blocks found last 2 days due to high variance.

**Comment by sammy007** [comment]
I don't comment on "luck questions", but when I do I say it's ok. Even 1000% happens, everywhere with each miner with high or small hashrate.

**Comment by rastko1996** [comment]
It just never happened before, and it's happening now that last week variance is very high so it appeared strange. Thanks, then all I can do is wait.

**Comment by etherninja** [comment]
yeah no fun when you loose 50% of your hash to nake maters worse. 350℅ seems to be the number when miners start dropping. i have my suspension but its unrelated to the pool software.

**Comment by sammy007** [comment]
I had no block for 10 hours with 10GH. Only monthly average matters for such hashrate.

**Comment by etherninja** [comment]
i know. it really plays tricks on the mind

**Comment by LeChuckDE** [comment]
do 5 blocks in 25 hrs with 200 mh/s and a variance of avg. 62 %

**Comment by sammy007** [comment]
This is going to nowhere.

Block stats are there: http://eth.poolto.be/#/blocks PooltoBe is good managed pool and it has very good "luck", so it's an example how pool performs, if you are solo mining with low hashrate prepare yourself to be nervous during several days.
