### ISSUE TITLE
Can you add more stratum ports?

### ISSUE THREAD

**Issue by LukeYaldo** [sammy007/open-ethereum-pool#410]
Not all rigs use the same difficulty. 2 Billion is high for some people and extremely low for other rigs. For this reason, pools such as NOMP allow you to create unlimited stratum ports each with different difficulties so that all levels of hashing power can hash at the ideal difficulty. I cannot figure out how to add more stratum ports with different difficulty levels on this pool. Has anyone been able to figure this out? It's an extremely useful feature in my opinion.

**Comment by mikeyb** [comment]
Just run multiple instances of the proxy module with different difficulties set

**Comment by MasterDeflate** [comment]
> Just run multiple instances of the proxy module with different difficulties set

How to do that? Example?

**Comment by mikeyb** [comment]
Read the config...
