### ISSUE TITLE
Front end not updating config changes

### ISSUE THREAD

**Issue by bonkingbob** [sammy007/open-ethereum-pool#415]
I can’t seem to get changes to pool fees etc. to show up in the front end. I’ve updated both config and environment.js and restarted the pool but it’s still showing the original details.

Is there a specific process to get the updates pushed through to the front end?

**Comment by mikeyb** [comment]
after making changes run `make` again to build, then restart

**Comment by bonkingbob** [comment]
Apologies its still not updating :(

**Comment by bonkingbob** [comment]
I got it. 

Cd www
Sudo ./build.sh
