### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by mdikmetas** [sammy007/open-ethereum-pool#416]
cd pools
git clone https://github.com/sammy007/open-ethereum-pool.git
cd open-ethereum-pool
make

but here  write error and not complate  where is problem

$ make
build/env.sh go get -v ./...
github.com/gorilla/mux (download)
package context: unrecognized import path "context" (import path does not begin with hostname)
github.com/ethereum/go-ethereum (download)
Fetching https://gopkg.in/redis.v3?go-get=1
Parsing meta tags from https://gopkg.in/redis.v3?go-get=1 (status code 200)
get "gopkg.in/redis.v3": found meta tag main.metaImport{Prefix:"gopkg.in/redis.v3", VCS:"git", RepoRoot:"https://gopkg.in/redis.v3"} at https://gopkg.in/redis.v3?go-get=1
gopkg.in/redis.v3 (download)
Fetching https://gopkg.in/bsm/ratelimit.v1?go-get=1
Parsing meta tags from https://gopkg.in/bsm/ratelimit.v1?go-get=1 (status code 200)
get "gopkg.in/bsm/ratelimit.v1": found meta tag main.metaImport{Prefix:"gopkg.in/bsm/ratelimit.v1", VCS:"git", RepoRoot:"https://gopkg.in/bsm/ratelimit.v1"} at https://gopkg.in/bsm/ratelimit.v1?go-get=1
gopkg.in/bsm/ratelimit.v1 (download)
github.com/ethereum/ethash (download)
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by mdikmetas** [comment]
for ubuntu 16.04 i use 8.8.8.8 dns

**Comment by mikeyb** [comment]
use a newer golang version (not ubuntu package, probably same with node/npm as they are old)

**Comment by elbochi22** [comment]
same problem on all ubuntu versions......
