### ISSUE TITLE
if you change www folder inside information what needs www build or?

### ISSUE THREAD

**Issue by mdikmetas** [sammy007/open-ethereum-pool#420]
www folder inside change all time  start?

npm install -g ember-cli@2.9.1
npm install -g bower
npm install
bower install
./build.sh

**Comment by mikeyb** [comment]
rephrase question, not making sense really.  If you run build.sh you need to restart

**Comment by mdikmetas** [comment]
sory my english 

im now three day ago start my pool 

but


I changed the content on the help page inside but not change web page inside. how to activate my change.
