### ISSUE TITLE
Wrong block number and newtwork difficulty!

### ISSUE THREAD

**Issue by ahonder** [sammy007/open-ethereum-pool#423]
#### System information

Geth version: `5.5.2`

Redis version: `redis-server --version`

OS & Version: Ubuntu 16.04

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````
Hi,
Fully synced (i saw %100 and counting on geth console)with geth --fast --rpc  command but frontend showing block number 1.  I'm closed geth and reopen showing same problem. How can i fix this?

**Comment by mikeyb** [comment]
Fix your config

**Comment by ahonder** [comment]
Which config?

**Comment by mdikmetas** [comment]
pool config file

**Comment by ahonder** [comment]
> pool config file

Türk olduğunuzu düşünerek soruyu detaylı sorabilirim.(Geth 5.5.3 ETC) pool config dosyasında hangi kısım? normal senkronizasyonda neredeyse bir haftaya yakın zaman geçti ve senkronize olmadı. fast komutuyla senkronize ettiğimde senkronize olsada havuz önyüzünde blok numarası sürekli 1 gösteriyor. senkronizasyonu kapatıp tekrar açtığımda chaindb dolu olduğu için normal senkronizasyon şeklinde başlıyor. geth komutunu bazen tekrar kapatıp açtığımda havuz önyüzünde blok 1 den farklı ve senkronizasyondan farklı numaralarda gösteriyor. 
Son olarak API bir süre sonra kapanıyor(arka planda senkronizasyon sürüyor) ve api kapandığı zamanda madenci bağlantı sağlayamıyor yani havuz işlemide kapanmış oluyor.Hepsi tek server içinde.

**Comment by ahonder** [comment]
I'm closing issue, because not actualy an issue. Why? 
After sync with geth, need some more extra time for completely sync(at fast sync mode). type in terminal "geth attach" and web3.eth.syncing you will see everything about sync progress like that;
`{ 
    currentBlock: 1600000,
    highestBlock: 1700000,
    knownStates: 1190000,
    pulledStates: 1140000,
    startingBlock: 1730000
}`
This mean syn not finished yet and dont worry about when behind 60 or 100 or maybe more on geth sync screen. 
When you see in geth attach screen block numbers close to real block number, proably a few minutes after will fully sinced and you will see in pool frontent too right block number.
I'm writing this for novice users (like me)because a lot of question about this when i searched about this.
