### ISSUE TITLE
Can't establish connection to backend: dial tcp: missing address

### ISSUE THREAD

**Issue by eug13768** [sammy007/open-ethereum-pool#43]
#### System information

Geth version: `geth version` or commit hash if `develop`
Version: 1.4.9-stable-b7e3dfc5
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=/home/ubuntu/go
GOROOT=/opt/google/go

Redis version: `redis-server --version`
Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9

OS & Version: Linux/Ubuntu 14.04

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
Unlocker does its job

#### Actual behaviour
2016/07/25 12:59:36 Loading config: /home/ubuntu/open-ethereum-pool/unlocker.json
2016/07/25 12:59:36 Can't establish connection to backend: dial tcp: missing address
2016/07/25 12:59:36 Starting block unlocker
2016/07/25 12:59:36 Set block unlock interval to 10m0s
2016/07/25 12:59:36 Failed to get block candidates from backend: dial tcp: missing address
2016/07/25 12:59:36 Unlocking suspended due to last critical error: dial tcp: missing address

This error appears when running separate instance of ether-pool with unlocker.json:

{
        "unlocker": {
                "enabled": true,
                "poolFee": 0.9,
                "poolFeeAddress": "0x<some_address_set_here>",
                "donate": true,
                "depth": 120,
                "immatureDepth": 20,
                "interval": "10m",
                "daemon": "http://127.0.0.1:8545",
                "keepTxFees": false,
                "timeout": "10s"
                }
}

Please suggest what can be the issue.

**Comment by eug13768** [comment]
Defined redis section in unlocker conf, now it finally started. 

Another question - all blocks have been counted as new so far, no any immature. So it does not unlock any again. Some of them are few days old. Please suggest what special must be done to make the pool change the state of "new" blocks.

**Comment by sammy007** [comment]
> Please suggest what special must be done to make the pool change the state of "new" blocks.

Sync chain. Run unlocker.

**Comment by eug13768** [comment]
root@ip#:~/open-ethereum-pool# ./ether-pool ./unlocker.json
2016/07/25 16:43:40 Loading config: /home/ubuntu/open-ethereum-pool/unlocker.json
2016/07/25 16:43:40 Backend check reply: PONG
2016/07/25 16:43:40 Starting block unlocker
2016/07/25 16:43:40 Set block unlock interval to 10m0s
2016/07/25 16:43:40 No block candidates to unlock
2016/07/25 16:43:40 No immature blocks to credit miners
2016/07/25 16:53:40 No block candidates to unlock
2016/07/25 16:53:40 No immature blocks to credit miners

loop.

**Comment by eug13768** [comment]
In issue #24 HelixR wrote he run it with config where were unlocker and payout only and that worked out. Will that be ok as you strongly recommend to run unlocker and only then payout?

**Comment by sammy007** [comment]
Yes I strongly recommend, but this is not an issue.

**Comment by sammy007** [comment]
> How many blocks to wait?

Depends on depth serttings. `immatureDepth` must be default and you usually will get immature blocks after 32 blocks mined back. The `depth` param must be something close to 256 and will completely unlock block and credit balance.

**Comment by eug13768** [comment]
immatureDepth is 20 (default) and depth is 120 (also default). I believe the last is okay as there's already 2184 block mined back.

root@ip:~/open-ethereum-pool# ./ether-pool ./unlocker.json
2016/07/25 16:43:40 Loading config: /home/ubuntu/open-ethereum-pool/unlocker.json
2016/07/25 16:43:40 Backend check reply: PONG
2016/07/25 16:43:40 Starting block unlocker
2016/07/25 16:43:40 Set block unlock interval to 10m0s
2016/07/25 16:43:40 No block candidates to unlock
2016/07/25 16:43:40 No immature blocks to credit miners
2016/07/25 16:53:40 No block candidates to unlock
2016/07/25 16:53:40 No immature blocks to credit miners
2016/07/25 17:03:40 No block candidates to unlock
2016/07/25 17:03:40 No immature blocks to credit miners
2016/07/25 17:13:40 No block candidates to unlock
2016/07/25 17:13:40 No immature blocks to credit miners
2016/07/25 17:23:40 No block candidates to unlock
2016/07/25 17:23:40 No immature blocks to credit miners
2016/07/25 17:33:40 No block candidates to unlock
2016/07/25 17:33:40 No immature blocks to credit miners
2016/07/25 17:43:40 No block candidates to unlock
2016/07/25 17:43:40 No immature blocks to credit miners
2016/07/25 17:53:40 No block candidates to unlock
2016/07/25 17:53:40 No immature blocks to credit miners
2016/07/25 18:03:40 No block candidates to unlock
2016/07/25 18:03:40 No immature blocks to credit miners
2016/07/25 18:13:40 No block candidates to unlock
2016/07/25 18:13:40 No immature blocks to credit miners

still :(

**Comment by sammy007** [comment]
Create a gist with a config file, remove sensitive data and show me,

**Comment by sammy007** [comment]
make sure you have this param in unlocker config https://github.com/sammy007/open-ethereum-pool/blob/master/config.example.json#L3

**Comment by eug13768** [comment]
https://gist.github.com/eug13768

Although I did not try to run payouts unless unlocker fnished okay.

Oh, yeah! Your last advice about adding "coin" did help!

2016/07/25 18:46:45 Mature block 1934666 with 1 tx, hash: 0x101d60ef
2016/07/25 18:46:45 Mature block 1934668 with 0 tx, hash: 0xcd8cb2c7
2016/07/25 18:46:45 Mature block 1934673 with 1 tx, hash: 0x9dfd67c1
2016/07/25 18:46:46 Mature block 1934682 with 2 tx, hash: 0x62c809d7
2016/07/25 18:46:46 Mature uncle 1934719/1934718 of reward 4375000000000000000 with hash: 0xf9862a7b
2016/07/25 18:46:46 Mature block 1934723 with 0 tx, hash: 0xe630e17d
2016/07/25 18:46:46 Mature block 1934769 with 0 tx, hash: 0x4250e3d8
2016/07/25 18:46:46 Mature block 1934790 with 1 tx, hash: 0xbff45c33
2016/07/25 18:46:46 Mature block 1934833 with 0 tx, hash: 0x44318ce2
2016/07/25 18:46:46 Mature block 1934845 with 0 tx, hash: 0xc1939be4
2016/07/25 18:46:46 Mature block 1934852 with 0 tx, hash: 0xfb27f3bf

**Comment by eug13768** [comment]
Please wait a second, let me run payouts.

**Comment by sammy007** [comment]
I see your blocks are now immature, let them mature now.

**Comment by sammy007** [comment]
For payouts make sure your coinbase account is unlocked with `geth --unlock '0x...'` and you  have enough peers on this node. This is configurable.

**Comment by eug13768** [comment]
Now it shows 

Blocks: 2184 Immature: 0 New; 2

Yes, geth is running with --unlock. Anything special to add to payouts.json ("coin": "eth")?

**Comment by sammy007** [comment]
Usually configs must be equal just enabled/disable particular modules.

**Comment by eug13768** [comment]
Payouts go. 

Thank you for your help!

**Comment by sammy007** [comment]
Good luck with your classic pool, make sure `donate: true` is there.

**Comment by eug13768** [comment]
It's there and will stay there - you should have some ETC when the process finish and further.

**Comment by sammy007** [comment]
I suggest you to rise payout threshold to 1 Ether otherwise your payouts will last forever.
