### ISSUE TITLE
No worker stats

### ISSUE THREAD

**Issue by pool2mine** [sammy007/open-ethereum-pool#435]
Hi!
I recently installed open-ethereum-pool, got my geth synced and connected miners, everything looks great, I already got one block, but what i cannot get done is for the pool to show me each worker from each miner account. I think i tried everything, Claymore, Ethminer, Sgminer and nothing worked. normally I use Claymore, I tried setting worker name as password, also WALLET.WORKER, WALLET/WORKER, -eworker, etc. but always get "0" workers.

Can you please point me in the right direction? 

Thanks in advance!

![Screenshot 2019-06-14 20 31 13](https://user-images.githubusercontent.com/38216354/59544823-a8aad880-8ee3-11e9-9338-efbd9e0615f1.png)

**Comment by mathias7799** [comment]
Thats offline workers.

**Comment by pool2mine** [comment]
Ok, you're right about the picture, but I only have one worker shown, I updated the picture below.
I am connected over stratum mode on default port 8008, is that ok? i didn't wanted to connect over http because normally it's slower.

![Screenshot 2019-06-14 21 14 24](https://user-images.githubusercontent.com/38216354/59545251-ffb3ac00-8ee9-11e9-9f86-16e66f00fb98.png)

**Comment by mathias7799** [comment]
Yep all good.

**Comment by pool2mine** [comment]
but still no worker names shown

**Comment by pool2mine** [comment]
hi @sammy007 any fix for this issue? please let me know

**Comment by pool2mine** [comment]
I found the problem. the pool does not recognize workers with more than 8 characters. all workers were showing together as one under the name of "0". After several days just reduced the length of the name and showed without any problem.

**Comment by edradev** [comment]
> I found the problem. the pool does not recognize workers with more than 8 characters. all workers were showing together as one under the name of "0". After several days just reduced the length of the name and showed without any problem.

where can I change this too?

**Comment by mathias7799** [comment]
@edradev 

Inside the proxy/handlers.go theres a regex expression "var workerPattern = regexp.MustCompile("^[0-9a-zA-Z-_]{1,8}$")"
1,8 part of it tells whats the min and max chars. But! I don't know if it'll break anything if you change it.

**Comment by edradev** [comment]
@mathias7799 thanks, I already changed it and works fine.
