### ISSUE TITLE
Blank Front End (only footer and background showing)

### ISSUE THREAD

**Issue by pool2mine** [sammy007/open-ethereum-pool#440]
Hi,
First of all, I know this has been posted before, but my case is a little strange. I have a running server with open ethereum pool installed. I set it up about 3 months ago and it's working fine, but as i wanted to make some changes and as I am new with open ethereum pool I didn't want to do it on my running server without testing first, so I installed same ubuntu 16.04 from same image on another server just to make those tests there first.

Here is the thing, I am running same commands, from same set up instructions:
https://blog.taiker.space/eth-pool/
I was able to install everything and my pool starts, but now i can't get the front end to show stats. when i stop the pool the home page shows "Stats API Temporarily Down" which is correct, but when i start the pool again the home page goes blank, no stats at all, just background and footer is showing, I already made more than 15 fresh installs, tried different node versions, ember versions, this thing is driving me crazy... why the first time worked and now it does not? now I don't want to change anything in my running front end because I'm afraid that if i build again i may loose my home page.
did something changed on some repositories this last months? why it worked the first time and not now? anybody having this issue?

**Comment by pool2mine** [comment]
@sammy007 i know you are not giving any more support but still i am willing to donate an ether if you could help me with this issue. would you take a look?

**Comment by pool2mine** [comment]
Ok it finally worked, a guy in another forum gave me the solution, the problem is somehow there were missing modules inside node_modules folder, so i replaced the whole intl-format-cache folder with the one i had in another server that was working fine, which i also installed months ago, then build again and worked, the only thing i cannot explain is why the first time i installed the front end worked and then i did the exact same thing on SEVERAL fresh installs and didn't work. why is this module missing now?, anyway if someone is still having the same problem just let me know and i'll send you the working folder.

**Comment by piemadd** [comment]
@pool2mine Hey bro, can you send me the folder?

**Comment by pool2mine** [comment]
Sure buddy, here it is.

[intl-format-cache.zip](https://github.com/sammy007/open-ethereum-pool/files/4468161/intl-format-cache.zip)

**Comment by piemadd** [comment]
@pool2mine You've saved my a** man, and I really appreciate it. Let me know if you ever need a favor lol!

**Comment by pool2mine** [comment]
Thanks man! I'm happy to help the miner community! is your pool for Ethereum or some other fork?

**Comment by piemadd** [comment]
I'm doing this for ethereum, and boy has the setup process been tiring. Do
you know the correct formatting of how to connect a miner to the pool? I've
tried and been unsuccessful!

**Comment by mikeyb** [comment]
@pieromqwerty POOL <--> STRATUM PROXY <--> MINER

**Comment by pool2mine** [comment]
if you are using claymore use this config

-epool [your-pool]:[port] -ewal [your-wallet] -epsw X -eworker [rig-name] -mode 1 -esm 0

I don't know if it's default but i recommend to use -esm 0, otherwise i wont connect.

Another important thing is that your address is your login... you cannot use [address.worker] or [address/worker/email]... on the -ewal use ONLY your wallet address otherwise you wont be able to login

**Comment by pool2mine** [comment]
hey @mikeyb i know this is off topic but i saw you are following this project for some time. Do you know by any chance if it's possible to ban addresses or IP? like a blacklist or something. I'm having some trouble in my pool with some wallets hopping with nicehash power... or even better... is there a way to block connections from nicehash?

**Comment by mikeyb** [comment]
@pool2mine You would probably want to use a local firewall.  Something like Fail2Ban can be configured to watch traffic to that port and do blocking dynamically based on traffic.  Or you can use something like `ufw` (iptables wrapper) to easily block ip addresses/ranges.

Feel free to email me (address on github profile) if you want to discuss further (so we don't derail this issue)

**Comment by piemadd** [comment]
I saw in the setup file there is a blacklist option, but I didn't look into
it. You might be able to create a text file and add IPs that way.

**Comment by piemadd** [comment]
Thanks! Actually figured it out, but your help was amazing anyways. Also,
@pool2mine , my web interface still wasn't working even after I added your
folder. Would you be able to call on discord or something like that
tomorrow or friday to help me out?

**Comment by pool2mine** [comment]
did you build the site again after pasting the files? remember you have to paste the folder inside the node_modules but after that you need to ./build again

**Comment by piemadd** [comment]
Oh I should try that.

**Comment by def670** [comment]
when i have to add intl-format-cache i have had to go into node-modules/intl-format-cache and do 
sudo npm install and then back out to www/ and ./build.sh

**Comment by Canefis** [comment]
> Sure buddy, here it is.
> 
> [intl-format-cache.zip](https://github.com/sammy007/open-ethereum-pool/files/4468161/intl-format-cache.zip)

Finally, thank a lot for your help!!!
