### ISSUE TITLE
More pool instances on server

### ISSUE THREAD

**Issue by ExEric3** [sammy007/open-ethereum-pool#45]
Is possible config nginx and more pools on same server? If yes how should looks configs?

**Comment by sammy007** [comment]
Yes. How - this is question for nginx stackoverflow section.

**Comment by sammy007** [comment]
Hint: google how to configure subdomains in nginx.

**Comment by ExEric3** [comment]
This  should work?

upstream api {
        server 127.0.0.1:8080;
	server 127.0.0.1:8090;
}

server {
        listen 0.0.0.0:80;
        root /home/erik/shift-pool/www/dist;
        index index.html index.htm;

        server_name shf.miners-zone.net;

        location /api {
                proxy_pass http://api;
        }

        location / {
                try_files $uri $uri/ /index.html;
        }
}

server {
        listen 0.0.0.0:80;
        root /home/erik/shifttest-pool/www/dist;
        index index.html index.htm;

        server_name shftest.miners-zone.net;

        location /api {
                proxy_pass http://api;
        }

        location / {
                try_files $uri $uri/ /index.html;
        }
}

**Comment by sammy007** [comment]
Just try it, I can't parse it in a head :)

**Comment by LeChuckDE** [comment]
will not work ! you have configured round robin at /api ...
Try to modify source to server ap2 at second and so on, do a upstream for /apix and proxy_pass apix
works for me eth,etc and exp on same server (okay its a 16 core.64 GB Xeon highperformance system, wouldn't do that with a vps)

**Comment by sammy007** [comment]
FYI: you don't have to pass api through nginx, you can simply configure `environment.js` to directly talk with api endpoint of the pool. The original idea behind passing it through nginx is limiting for additional safety which must be configured too but I don't cover it in config example.

**Comment by ExEric3** [comment]
Which section sammy? ApiUrl? LeChuckDE you mean modify server.go (api subdir) file in pool source?

**Comment by sammy007** [comment]
> ApiUrl?

Correct.

Make sure your `coin` settings in pool config are different, otherwise you will screw your database if all pools for both $ETC & $ETH talk to the same redis instance.

**Comment by LeChuckDE** [comment]
```
./api/server.go:        r.HandleFunc("/api3/stats", s.StatsIndex)
./api/server.go:        r.HandleFunc("/api3/miners", s.MinersIndex)
./api/server.go:        r.HandleFunc("/api3/blocks", s.BlocksIndex)
./api/server.go:        r.HandleFunc("/api3/payments", s.PaymentsIndex)
./api/server.go:        r.HandleFunc("/api3/accounts/{login:0x[0-9a-fA-F]{40}}", s.AccountIndex)
```

```

./www/app/templates/account/index.hbs:    <strong>Your bulk stats JSON API URL:</strong> <a href="/api3/accounts/{{model.login}}">/api/accounts/{{model.login}}</a>
./www/app/routes/blocks.js:    var url = config.APP.ApiUrl + 'api3/blocks';
./www/app/routes/application.js:    var url = config.APP.ApiUrl + 'api3/stats';
./www/app/routes/payments.js:    var url = config.APP.ApiUrl + 'api3/payments';
./www/app/routes/account.js:            var url = config.APP.ApiUrl + 'api3/accounts/' + params.login;
./www/app/routes/miners.js:    var url = config.APP.ApiUrl + 'api3/miners';
```


In these files you have to change it, recompile both (open-ethereum-pool) and you could also change the database in config file, REDIS comes with 64 empty databases.starting with 0. 
In my opinion safest to choose database 1 - X in config 

```
        "redis": {
                "endpoint": "xxxxxxxx",
                "poolSize": 10,
                "database": 1,
                "password": "xxxxxxxxxxxx"
                 }
```

**Comment by ExEric3** [comment]
Thanks guys for help. Yeah sammy Im running standalone redis instance for that pool. Have a nice day.

**Comment by sammy007** [comment]
@ExEric3  pull latest from develop.
