### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ahonder** [sammy007/open-ethereum-pool#459]
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````
Hi,
when i run inside main folder "make all" command giving error  like;
ethereum/go-ethereum/common/math/integer.go:84:21: undefined: bits.Sub64
ethereum/go-ethereum/common/math/integer.go:90:19: undefined: bits.Add64
ethereum/go-ethereum/common/math/integer.go:96:12: undefined: bits.Mul64
*
*
*
Makefile:10 recipe for target 'all' failed.

What is the solution? i was before installed many times.

**Comment by joey-crypto** [comment]
same error, i want to know if it need  update the version of golang?

**Comment by ahonder** [comment]
i fixed with golang 1.13
