### ISSUE TITLE
make failed, cannot find main module

### ISSUE THREAD

**Issue by fuqiangZ** [sammy007/open-ethereum-pool#461]
#### System information

OS & Version: Linux/OSX
> ubuntu 16.04
> go version go1.13.15 linux/amd64

Commit branch and hash: (`master`, `ba60e1c`)
> branch: master

#### Expected behaviour
> make build success

#### Actual behaviour
```
build/env.sh go get -v ./...
go: cannot find main module, but found .git/config in /opt/bitcoin/pool/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool
	to create a module there, run:
	go mod init
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1
```

#### Steps to reproduce the behaviour
```
# git clone  https://github.com/sammy007/open-ethereum-pool.git
#cd open-ethereum-pool
# export GO111MODULE=on
# export GOPROXY=https://goproxy.io
# source /etc/profile
# make

```

Is my go version too hight or any env wrong ? 
 I'd appreciate some help.

**Comment by lmxdawn** [comment]
Excuse me, how was it solved? I also encountered the same problem

**Comment by 0xIbrahim-t** [comment]
> #### System information
> OS & Version: Linux/OSX
> 
> > ubuntu 16.04
> > go version go1.13.15 linux/amd64
> 
> Commit branch and hash: (`master`, `ba60e1c`)
> 
> > branch: master
> 
> #### Expected behaviour
> > make build success
> 
> #### Actual behaviour
> ```
> build/env.sh go get -v ./...
> go: cannot find main module, but found .git/config in /opt/bitcoin/pool/open-ethereum-pool/build/_workspace/src/github.com/sammy007/open-ethereum-pool
> 	to create a module there, run:
> 	go mod init
> Makefile:10: recipe for target 'all' failed
> make: *** [all] Error 1
> ```
> 
> #### Steps to reproduce the behaviour
> ```
> # git clone  https://github.com/sammy007/open-ethereum-pool.git
> #cd open-ethereum-pool
> # export GO111MODULE=on
> # export GOPROXY=https://goproxy.io
> # source /etc/profile
> # make
> ```
> 
> Is my go version too hight or any env wrong ? I'd appreciate some help.

try export GO111MODULE=auto
