### ISSUE TITLE
Payouts in automatic mode

### ISSUE THREAD

**Issue by eug13768** [sammy007/open-ethereum-pool#47]
Actually it's not an issue but more a question.

If there's a need to run unlocker then payouts in a sequence by cron, then before running payouts it need to wait for unlocker to finish (better with success error code). However, when unlocker is done it stays running so there's no automatic way to identify when payout must be started.

Please suggest what should the best strategy here.

Thanks.

**Comment by sammy007** [comment]
Just run payouts and unlocker and let them do their jobs, there is an interval configurable, you don't have to run it via cron.

**Comment by eug13768** [comment]
Thanks.
