### ISSUE TITLE
Frontend 

### ISSUE THREAD

**Issue by igorwhite** [sammy007/open-ethereum-pool#50]
Hello. Have a nice day.
#### System information

Geth version: `geth version` -- 1.4.10  geth --oppose-dao-fork

Redis version: `redis-server --version` -- 2.8.4

OS & Version: Linux/OSX -- Ubuntu 14.04.04

Node version -- v0.12.15
Npm version -- 2.15.1
Nginx version -- 1.4.6

Clean system.
All compile without error and without sudo.
Frontend looks.  https://yadi.sk/i/seky4pyithNi2
What could be the problem?
What am I doing wrong?
Best Regards Igor.

**Comment by sammy007** [comment]
I see no CSS loaded. You must build frontend and serve `www/dist` as a static website, no idea why your server or browser ignore CSS.

**Comment by igorwhite** [comment]
I have changed nginx.conf --- need default in site-available
Sorry to trouble you.
