### ISSUE TITLE
hi,please help me!

### ISSUE THREAD

**Issue by skygong** [sammy007/open-ethereum-pool#52]
hi,please help me!

root@ubuntu:~/open-ethereum-pool# make
build/env.sh go get -v ./...
github.com/ethereum/go-ethereum/crypto/secp256k1
# github.com/ethereum/go-ethereum/crypto/secp256k1
exec: "gcc": executable file not found in $PATH
make: *** [all] Error 2
root@ubuntu:~/open-ethereum-pool#

**Comment by skygong** [comment]
reboot system, re make, prompt

root@ubuntu:~/open-ethereum-pool# make
build/env.sh go get -v ./...
build/env.sh: 32: exec: go: not found
make: *** [all] Error 127
root@ubuntu:~/open-ethereum-pool#

**Comment by sammy007** [comment]
Please stop opening such nonsense issues. Go to gitter and ask people for help. U need to install `apt-get install build-essential` and `apt-get install golang`. In other words you need to prepare your system for compilation by installing gcc, make, etc.

**Comment by skygong** [comment]
Thank you, I am a novice.
