### ISSUE TITLE
Ironic - ETH donations address on a ETC pool

### ISSUE THREAD

**Issue by yt-bg** [sammy007/open-ethereum-pool#54]
I am building ETC pool with open-ethereum-pool. Thank you for your work.

Please, create for yourself an ETC address, or eventually BTC address and add it/them commented into the html footer.

I dislike ETH and I hesitate whether to leave your address in the footer or to remove it ...

**Comment by sammy007** [comment]
Best you can do is just to set `donate: true` in block unlocker configuration section. Check out README for all options and description. Address is hard coded in unlocker and universal for both ETH & ETC. If donations enabled I'll receive 10% from pool fees.

https://github.com/sammy007/open-ethereum-pool/blob/master/payouts/unlocker.go#L38

PS: Don't waste time adding it to footer, no one donates in crypto.

Cheers.

**Comment by sammy007** [comment]
When you will be up and running PM me on gitter I will list your pool in wiki https://github.com/sammy007/open-ethereum-pool/wiki/List-Of-Open-Pools

**Comment by yt-bg** [comment]
Quick answer. Thank you.

I noticed this option. Now it is 0% or 10%. My opinion is that you deserve something between these numbers. My suggestion: make this integer and set it 5 in the default config. Small/startup pools are holding every wei tightly and will set this to 0. When their business starts to grow they can make it 2, 5, 10, 20, 30 - depending on the operators gratitude.

**Comment by sammy007** [comment]
Small pools can just disable it for a while. But I will consider your suggestion. The initial idea is that if pool can't afford it, pool should not exist or should disable it.

**Comment by yt-bg** [comment]
Often pool operators are also miners and in our case everything earned is invested in video cards. I appreciate your work, but we cannot afford to donate 10% of our earnings until the moment X when the pool is big enough. Give me chance to give you money earlier.

**Comment by sammy007** [comment]
The chance is here https://github.com/sammy007/open-ethereum-pool/blob/master/payouts/unlocker.go#L37 but better disable it for the time being.

**Comment by yt-bg** [comment]
Now it will be 0, But I will not forget you later. If there is later.

Thank you and thank you for your work.
