### ISSUE TITLE
How to process payments?

### ISSUE THREAD

**Issue by blckeagls** [sammy007/open-ethereum-pool#55]
#### System information

Geth version: `geth version` or commit hash if `develop`
Version: 1.4.10-stable
Redis version: `redis-server --version`
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42
OS & Version: Linux/OSX
Ubuntu 16
Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
1. Payments get processed. 
2. Blocks moving from "New Block" to "Immature" to "Blocks"
3. User's payout incrementing in miner view

#### Actual behaviour
Not seeing payouts being sent.  Mined block stuck in "New Block" for over 4 hour

#### Steps to reproduce the behaviour
Don't know

#### Backtrace

````
[backtrace]
````

**Comment by sammy007** [comment]
Do you have block unlocker enabled? Do you have geth in sync properly? Without unlocker logs I can't help. This is not about payouts it's all about block maturity. Make sure `coin` config param is equal in all of your config files.

**Comment by blckeagls** [comment]
That started to work better... but now I get this error:  

Unable to process payouts: account is locked

**Comment by sammy007** [comment]
Because you must run geth for payouts with `geth --unlock 0`. It;s good to read logs they are awesome along with some understanding.

**Comment by blckeagls** [comment]
Thanks!  That worked...
