### ISSUE TITLE
Expand on the nginx configuration please. 

### ISSUE THREAD

**Issue by mbush78** [sammy007/open-ethereum-pool#56]
Would it be possible for you to please expand on the nginx portion. 
This pool has so many ports etc I've become completely lost.

**Comment by mbush78** [comment]
I'm not exactly sure but I think I got it working.

Here is my "eth-pool" site configuration. (Side note: Don't forget to open the external ports on your firewall :) )

upstream root {
    server 0.0.0.0:8888;
}

upstream api {
    server 0.0.0.0:8080;
}

server {
    server_name pool.your.server.com;

    access_log  /var/log/nginx/open-ethereum-pool.access.log;
    error_log   /var/log/nginx/open-ethereum-pool.error.log;

    location / {
        root /var/www/dist;
    }

    location /api {
        proxy_pass http://api;
    }

}

**Comment by sammy007** [comment]
Hundreds of manuals already out there about nginx upstreams and virtual hosts configuration.
