### ISSUE TITLE
Failover Pool and Change minimal withdrawal

### ISSUE THREAD

**Issue by igorwhite** [sammy007/open-ethereum-pool#58]
Hello Dear Sir.

How to Failover Pool?
In what file edit change minimal withdrawal?

Excuse for troubling.
I have little experience.

Best regards Igor.

**Comment by shenfeizi** [comment]
in the README

/* List of geth nodes to poll for new jobs. Pool will try to get work from
    first alive one and check in background for failed to back up.
    Current block template of the pool is always cached in RAM indeed.
  */
  "upstream": [
    {
      "name": "main",
      "url": "http://127.0.0.1:8545",
      "timeout": "10s"
    },
    {
      "name": "backup",
      "url": "http://127.0.0.2:8545",
      "timeout": "10s"
    }
  ],

**Comment by sammy007** [comment]
@igorwhite there is a `threshold` option in payout section of the config file.

**Comment by sammy007** [comment]
What does "How to Failover Pool?" mean? If you need a failover geth/parity node you have to specify several upstreams like @shenfeizi said.

For multi-mining endpoint setup you have to point several processes of the pool to a single secured redis instance.

**Comment by igorwhite** [comment]
Thank you.
How to be a database redis?

**Comment by yt-bg** [comment]
redis:
apt-get install -y redis-server

**Comment by igorwhite** [comment]
Oh, my bad english
On the spare server database redis must be the same?

**Comment by sammy007** [comment]
Redis instance must be one and only and all nodes must talk with it.

**Comment by sammy007** [comment]
If you have problems with understanding of distributed setup of this pool I suggest to not do that.

**Comment by igorwhite** [comment]
sammy007 you GuruI am learning. 
And really I want to run the pool. Now I seem to have understood all

**Comment by sammy007** [comment]
I just suggested to start from simple setup and then add complexity

**Comment by igorwhite** [comment]
I can no longer distract you stupid questions.
Last question.
How many powerful need a server?

**Comment by sammy007** [comment]
It depends. If you gun geth you need at least multi-core low level XEON with min. 32 GB RAM. If you run https://github.com/ethcore/parity you need less resources. I suggest to ask people on gitter.

**Comment by igorwhite** [comment]
Many thanks
