### ISSUE TITLE
A new problem has arisen.

### ISSUE THREAD

**Issue by skygong** [sammy007/open-ethereum-pool#59]
A new problem has arisen.

Normal mining
but www ember server：
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Web page display：
Stats API Temporarily Down
Usually it's just a temporal issue and mining is not affected.

**Comment by goodthebest** [comment]
@skygong did you find a solutin?
