### ISSUE TITLE
Genoil's miner stratum support, vardiff support

### ISSUE THREAD

**Issue by davembg** [sammy007/open-ethereum-pool#6]
I'm close to have this implemented with only minor additions.
@sammy007 Are you open to adding this to your codebase?

I could fork it, but sometimes I think that's rude.

**Comment by sammy007** [comment]
As I already said on gitter, there is no way to securely provide vardiff. Feel free to wok in your own fork for now, I'll look onto it and if stratum is ok I'll cherry-pick stratum related code or do my own impl. based on yours.

**Comment by sammy007** [comment]
> I could fork it, but sometimes I think that's rude.

Everyone can do whatever they want with this project until it violates GPLv3. That's why it was released under this license. People forking, adding features and eventually good modifications appear in mainline like in every OS projects.

**Comment by sammy007** [comment]
Regarding vardiff: https://github.com/sammy007/open-ethereum-pool/issues/10
Regarding stratums: we will look into this later.
