### ISSUE TITLE
The documentation is a bit unclear about payment and unlocking processes.

### ISSUE THREAD

**Issue by yt-bg** [sammy007/open-ethereum-pool#61]
The documentation is a bit unclear about payment and unlocking processes.

I have read 
```
- Mining instance - 1x (it depends, you can run one node for EU, one for US, one for Asia)
- Unlocker and payouts instance - 1x each (strict!)
- API instance - 1x
```
but it is a little short on the details.

Should I run 4 instances of open-ethereum-pool?
one with enabled **proxy + redis + upstream** (do I need redis here?)
second with enabled **unlocker + redis**
third with enabled **payouts + redis**
forth with enabled **api + redis**

Not as CRON jobs, I now this. (This info also missing from the README)

Thank you for your effort and time.

**Comment by sammy007** [comment]
Config file must be the same with just particular modules enabled and disabled.

**Comment by yt-bg** [comment]
Thank you!

I as an absolute novice started just one instance with everything enabled.

Proposal: Split cfg file into 4 cfgs OR put "WARNING - you must run 4 instancess at least" - this point is easily omitted by a novice.

Thank you again.
