### ISSUE TITLE
The problem with the failed payment

### ISSUE THREAD

**Issue by Igmin** [sammy007/open-ethereum-pool#63]
A problem has occurred in the production of payment. Now, according to a pool: 
_"Previous payout failed, you have to resolve it. List of failed payments:
         Address: 0x3603fb7ce88e40bf7d0ff2470c49ce137fae3eb3, Amount: 2389940003 Shannon,"_
And the payment is not made. But the funds for this payment on blockchain passed. What to do? How to fix the failed payment?

#### System information
Geth version: 1.4.10  
Redis version: Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9
OS & Version: Linux Ubuntu server 14.04

**Comment by yt-bg** [comment]
Just for you:
https://github.com/sammy007/open-ethereum-pool/blob/master/docs/PAYOUTS.md

Look for manual resolving.

**Comment by Igmin** [comment]
Thank you. In this guide, and I solved the problem.
