### ISSUE TITLE
Can't connect to stratnum

### ISSUE THREAD

**Issue by robbmcmahan** [sammy007/open-ethereum-pool#64]
#### System information

Geth version: `geth version` or commit hash if `develop`
1.5.0-stable

Redis version: `redis-server --version`
3.23

OS & Version: Linux/OSX
Ubuntu 16.04

Commit branch and hash: (`master`, `ba60e1c`)
master

#### Expected behaviour
Stratnum working

#### Actual behaviour
Stratnum not working

#### Steps to reproduce the behavior

Hi Sammy. Thanks fpr your hard work!
I seem to have everything running without any errors and the frontend is showing stats but when I try to connect to the stratnum server my eth-proxy is not able to connect (it works fine with other pools). Any ideas why and what I can check? I'm using the example config as is.

Thanks

**Comment by sammy007** [comment]
Make sure you connect it to stratum port of the pool, not to http.

**Comment by sammy007** [comment]
Also I'd like to look on errors.

**Comment by sammy007** [comment]
I see it works on my side.

```
2016-08-07 10:36:23,409 INFO proxy # NEW_JOB MAIN_POOL
2016-08-07 10:36:33,158 INFO proxy # NEW_JOB MAIN_POOL
```

**Comment by robbmcmahan** [comment]
Thanks for the fast reply, the problem was the port was not open.
