### ISSUE TITLE
www shows stats api down

### ISSUE THREAD

**Issue by robbmcmahan** [sammy007/open-ethereum-pool#65]
Hi Sammy,
In the read me you have
"Change ApiUrl: '//example.net/' in www/config/environment.js to match your domain name. "

I have changed that to my //mydomainname.com/ however if I go to www.mydomainname.com (when you add the www) it shows the "stats api down".

What do I need to do to make it work for both?

Thanks

**Comment by sammy007** [comment]
Because I guess you missed port.

**Comment by robbmcmahan** [comment]
What do you mean missed port? I don't see anywhere in the environment.js to add a port for the domain. Do you mean a different configure file? If so what and where?


    APP: {
      // API host and port
      ApiUrl: '//example.net/',

      // HTTP mining endpoint
      HttpHost: 'http://example.net',
      HttpPort: 8888,

      // Stratum mining endpoint
      StratumHost: 'example.net',
      StratumPort: 8008,

      // Fee and payout details
      PoolFee: '1%',
      PayoutThreshold: '0.5 Ether',

      // For network hashrate (change for your favourite fork)
      BlockTime: 14.4
    }
  };


Thanks

**Comment by sammy007** [comment]
I meant port on which API is listening for requests. By default it's 8080 if you didn't set up nginx upstream for it.

**Comment by robbmcmahan** [comment]
I put the upstream in the nginx exactly like the read me example shows.

**Comment by sammy007** [comment]
Soma make sure you can access `/api/stats` URL from external machine. keep in mind that changes to `environment.js` does not give immediate effect, you must build it again.

**Comment by robbmcmahan** [comment]
Yes, I can access /api/stats from mydomain.com/api/stats 
I can also access them from www.mydomain.com/api/stats (when I include www prefix)

eveything works fine at mydomain.com
but when I go to www.mydomain.com (when I include the www) it shows Stats API Temporarily Down

**Comment by sammy007** [comment]
So don't include it or fix subdomain configuration in web server.
