### ISSUE TITLE
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by etherx-dev** [sammy007/open-ethereum-pool#67]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

Warning while installing with NPM. We may need to change the minimatch version.

**Comment by sammy007** [comment]
It's not an issue because it works and only used once to generate static website. Warnings will vanish after planned update to new Ember LTS.
