### ISSUE TITLE
[Question] Please tell me how to change coin from eth to etc pool 

### ISSUE THREAD

**Issue by phucvinh52** [sammy007/open-ethereum-pool#68]
Please tell me how to change coin from eth to etc pool !
Thank you.
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````

**Comment by sammy007** [comment]
https://github.com/sammy007/open-ethereum-pool/blob/master/config.example.json#L3

```javascript
{
  // Prefix for keys in redis store
  "coin": "eth",
}
```

**Comment by phucvinh52** [comment]
Thank you very much for two fast response. <3

**Comment by sammy007** [comment]
I hope you understand that you must run different chain for classic and not only change pool config?

**Comment by phucvinh52** [comment]
Yes, Is chain still ethereum? . I'm begining join to :P, so very concept that I don't know. Thank you very much :+1:

**Comment by phucvinh52** [comment]
Can you detail for me config payout. I'm Pending Balance in 6hour still now.
My config
`"payouts": {
		"enabled": true,
		"requirePeers": 5,
		"interval": "5m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s",
		"address": "0x0",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500000000,
		"bgsave": false
	}
`

**Comment by sammy007** [comment]
Should work with default config. I highly suggest to join pool, not run your own due to lack of basic knowledge.

**Comment by phucvinh52** [comment]
Last question :P, i'm running with EthDrcMiner64.exe but it alert 

> Probably you are trying to mine Ethereum fork. Please specify "-allcoins 1" option. Check "Readme" file for details

Please tell me why how to fix it thank you :).

**Comment by sthong80** [comment]
I'm getting this issue as well:

> Probably you are trying to mine Ethereum fork. Please specify "-allcoins 1" option. Check "Readme" file for details
