### ISSUE TITLE
[Question] My pool block is 0

### ISSUE THREAD

**Issue by phucvinh52** [sammy007/open-ethereum-pool#69]
This is my site http://pooleth.uibasic.com/, my pool block is always 0. Please tell me how to fix it.
Thank you very much for your prev response.
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````

**Comment by sammy007** [comment]
You can fix it only if you will continue to mine.

**Comment by sammy007** [comment]
Last Block Found: 1 minute ago. Just fixed it for you.
