### ISSUE TITLE
Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by axelxod** [sammy007/open-ethereum-pool#71]
Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
ubunta, all do how in you guide.

````

**Comment by FelixWeis** [comment]
Is parity/geth running on that port? Does normal curl json-rpc call work?

**Comment by axelxod** [comment]
yes geth working, mining started 
root@aspercoin:/var/www/open-ethereum-pool# ./build/bin/open-ethereum-pool config.json
2016/08/15 08:57:33 Loading config: /var/www/open-ethereum-pool/config.json
2016/08/15 08:57:33 Running with 2 threads
2016/08/15 08:57:33 Backend check reply: PONG
2016/08/15 08:57:33 Starting payouts
2016/08/15 08:57:33 Set payouts interval to 2h0m0s
2016/08/15 08:57:33 Starting API on 0.0.0.0:8080
2016/08/15 08:57:33 Set stats collect interval to 5s
2016/08/15 08:57:33 Set purge interval to 10m0s
2016/08/15 08:57:33 Policy state refresh complete
2016/08/15 08:57:33 Set policy stats reset every 1h0m0s
2016/08/15 08:57:33 Set policy state refresh every 1m0s
2016/08/15 08:57:33 Running with 8 policy workers
2016/08/15 08:57:33 Upstream: mains => http://127.0.0.1:8545
2016/08/15 08:57:33 Upstream: backup => http://127.0.0.2:8545
2016/08/15 08:57:33 Default upstream: mains => http://127.0.0.1:8545
2016/08/15 08:57:33 Stratum listening on 0.0.0.0:8008
2016/08/15 08:57:33 No payees that have reached payout threshold
2016/08/15 08:57:33 Purged stale stats from backend, 0 shares affected, elapsed time 3.004974ms
2016/08/15 08:57:33 New block to mine on mains at height 2074236 / 0x3bd0ed37
2016/08/15 08:57:33 Set block refresh every 25ms
2016/08/15 08:57:33 Starting proxy on 0.0.0.0:8888
2016/08/15 08:57:33 Broadcasting new job to 0 stratum miners
2016/08/15 08:57:33 Jobs broadcast finished 8.723µs
2016/08/15 08:57:33 Stats collection finished 7.0211ms
2016/08/15 08:57:38 Stats collection finished 420.652µs

**Comment by axelxod** [comment]
curl -X POST http://127.0.0.1:8545 -d '{"jsonrpc":"2.0","method":"eth_getWork","params":[],"id":0}'
{"jsonrpc":"2.0","id":0,"result":["0xd1449ddb1e8982128d18638979dd3d7487a63f587daa3589ef9524fee653da04","0x46862965466b5f8011ebefb35a0d1a0b7290c3ba38c11e916c74c347e00ed903","0x00000000001c253bed9e4a51f475063259506191b73b2e3e61e835e5fb6718c6"]}
