### ISSUE TITLE
Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused

### ISSUE THREAD

**Issue by chun007** [sammy007/open-ethereum-pool#76]
#### System information

Geth version: `geth version` or commit hash if `develop`
Version: 1.4.11-stable-fed692f6
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.6

Redis version: `redis-server --version`
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

OS & Version: Linux/OSX
Ubuntu 16.04
Linux pool 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Commit branch and hash: (`master`, `ba60e1c`)

#### Actual behaviour
2016/09/11 19:48:05 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused

#### Backtrace
:~/open-ethereum-pool$ build/bin/open-ethereum-pool
2016/09/11 20:36:27 Loading config: /home/admpool/open-ethereum-pool/config.json
2016/09/11 20:36:27 Running with 2 threads
2016/09/11 20:36:27 Backend check reply: PONG
2016/09/11 20:36:27 Starting API on 0.0.0.0:8080
2016/09/11 20:36:27 Set stats collect interval to 5s
2016/09/11 20:36:27 Set purge interval to 10m0s
2016/09/11 20:36:27 Purged stale stats from backend, 0 shares affected, elapsed time 29.540062ms
2016/09/11 20:36:27 Policy state refresh complete
2016/09/11 20:36:27 Set policy stats reset every 1h0m0s
2016/09/11 20:36:27 Set policy state refresh every 1m0s
2016/09/11 20:36:27 Running with 8 policy workers
2016/09/11 20:36:27 Upstream: main => http://127.0.0.1:8545
2016/09/11 20:36:27 Upstream: backup => http://127.0.0.2:8545
2016/09/11 20:36:27 Default upstream: main => http://127.0.0.1:8545
2016/09/11 20:36:27 Stats collection finished 1.77789ms
2016/09/11 20:36:27 Stratum listening on 0.0.0.0:8008
2016/09/11 20:36:27 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/09/11 20:36:27 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/09/11 20:36:27 Set block refresh every 120ms
2016/09/11 20:36:27 Starting proxy on 0.0.0.0:8888
2016/09/11 20:36:27 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/09/11 20:36:27 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/09/11 20:36:27 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2016/09/11 20:36:27 Error while refreshing pending block on main: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
````
[backtrace]
````
config.json default

/home/pool/open-ethereum-pool/www/config/environment.js
....
    APP: {
      // API host and port
      ApiUrl: '//localhost/',

      // HTTP mining endpoint
      HttpHost: 'http://127.0.0.1',
      HttpPort: 8888,

      // Stratum mining endpoint
      StratumHost: '127.0.0.1',
      StratumPort: 8008,
...
/etc/nginx/sites-available/default
upstream api {
        server 127.0.0.1:8080;
}

server {
        listen 0.0.0.0:80;
        root /home/pool/open-ethereum-pool/www/dist;
        index index.html index.htm;

        server_name localhost;

        location /api {
                proxy_pass http://api;
        }

        location / {
                try_files $uri $uri/ /index.html;
        }

netstat -pan
[sudo] password for admpool: 
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      2526/redis-server 1
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2597/nginx -g daemo
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2496/sshd       
tcp        0      1 192.168.1.122:38584     99.71.221.168:19595     SYN_SENT    3315/geth       
tcp        0      1 192.168.1.122:33366     62.45.212.112:30303     SYN_SENT    3315/geth       
tcp        0      1 192.168.1.122:34536     110.20.194.162:30303    SYN_SENT    3315/geth       
tcp        0    196 192.168.1.122:22        192.168.1.107:50278     ESTABLISHED 3341/sshd: admpool 
tcp        0      1 192.168.1.122:37662     223.81.140.218:30303    SYN_SENT    3315/geth       
tcp        0      1 192.168.1.122:47114     74.12.189.158:30303     SYN_SENT    3315/geth       
tcp        0      1 192.168.1.122:42534     108.172.13.206:30303    SYN_SENT    3315/geth       
tcp        0      0 192.168.1.122:41862     62.195.118.11:30303     FIN_WAIT2   -               
tcp        0    532 192.168.1.122:45144     178.59.206.165:30303    FIN_WAIT1   -               
tcp        0      0 192.168.1.122:22        192.168.1.107:49684     ESTABLISHED 2774/sshd: admpool 
tcp        0      0 127.0.0.1:49756         127.0.0.1:6379          ESTABLISHED 3334/open-ethereum-
tcp        0      0 192.168.1.122:22        192.168.1.107:49644     ESTABLISHED 2619/sshd: admpool 
tcp        0      1 192.168.1.122:39510     86.150.73.200:30303     SYN_SENT    3315/geth       
tcp        0      1 192.168.1.122:42904     78.228.47.91:30303      SYN_SENT    3315/geth       
tcp        0      0 192.168.1.122:47994     104.220.25.135:30303    ESTABLISHED 3315/geth       
tcp        0    241 192.168.1.122:41222     24.85.182.52:30303      LAST_ACK    -               
tcp        0      0 127.0.0.1:49758         127.0.0.1:6379          ESTABLISHED 3334/open-ethereum-
tcp        0      0 192.168.1.122:40168     208.59.160.253:30303    ESTABLISHED 3315/geth       
tcp        0      0 127.0.0.1:6379          127.0.0.1:49756         ESTABLISHED 2526/redis-server 1
tcp        0      1 192.168.1.122:41814     109.190.104.108:30303   SYN_SENT    3315/geth       
tcp        0      0 127.0.0.1:6379          127.0.0.1:49758         ESTABLISHED 2526/redis-server 1
tcp        0      1 192.168.1.122:36660     163.239.27.31:30303     SYN_SENT    3315/geth       
tcp        0      0 192.168.1.122:48624     173.184.91.235:30303    ESTABLISHED 3315/geth       
tcp6       0      0 :::8008                 :::*                    LISTEN      3334/open-ethereum-
tcp6       0      0 :::8080                 :::*                    LISTEN      3334/open-ethereum-
tcp6       0      0 :::22                   :::*                    LISTEN      2496/sshd       
tcp6       0      0 :::8888                 :::*                    LISTEN      3334/open-ethereum-
tcp6       0      0 :::30303                :::*                    LISTEN      3315/geth       
udp        0      0 0.0.0.0:68              0.0.0.0:*                           2438/dhclient   
udp6       0      0 :::30303                :::*                                3315/geth       

All services are running on a single computer.

**Comment by mikeyb** [comment]
I don't see anything running on port 8545 on your system:

```
tcp 0 0 127.0.0.1:6379 0.0.0.0:* LISTEN 2526/redis-server 1
tcp 0 0 0.0.0.0:80 0.0.0.0:* LISTEN 2597/nginx -g daemo
tcp 0 0 0.0.0.0:22 0.0.0.0:* LISTEN 2496/sshd
tcp6 0 0 :::8008 :::* LISTEN 3334/open-ethereum-
tcp6 0 0 :::8080 :::* LISTEN 3334/open-ethereum-
tcp6 0 0 :::22 :::* LISTEN 2496/sshd
tcp6 0 0 :::8888 :::* LISTEN 3334/open-ethereum-
tcp6 0 0 :::30303 :::* LISTEN 3315/geth
```

Make sure you have geth running with rpc enabled

```
geth --help|grep rpc
  --rpc			Enable the HTTP-RPC server
  --rpcaddr value	HTTP-RPC server listening interface (default: "localhost")
  --rpcport value	HTTP-RPC server listening port (default: 8545)
  --rpcapi value	API's offered over the HTTP-RPC interface (default: "eth,net,web3")
  --rpccorsdomain value	Comma separated list of domains from which to accept cross origin requests (browser enforced)
```

**Comment by chun007** [comment]
running with key --rpcport 8545 given nothing

~/go-ethereum$ ./build/bin/geth --rpcport 8545
I0912 13:01:26.181741 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/admpool/.ethereum/chaindata
I0912 13:01:27.145616 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0912 13:01:27.145682 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0912 13:01:27.145711 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0912 13:01:27.145739 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0912 13:01:27.145766 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0912 13:01:27.273192 ethdb/database.go:169] closed db:/home/admpool/.ethereum/chaindata
I0912 13:01:27.318468 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/admpool/.ethereum/chaindata
I0912 13:01:27.576918 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /home/admpool/.ethereum/dapp
I0912 13:01:27.666454 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0912 13:01:27.686649 eth/backend.go:201] Blockchain DB Version: 3
I0912 13:01:27.707028 core/blockchain.go:206] Last header: #272198 [50103220…] TD=1206583562529435662
I0912 13:01:27.707305 core/blockchain.go:207] Last block: #272198 [50103220…] TD=1206583562529435662
I0912 13:01:27.707464 core/blockchain.go:208] Fast block: #272198 [50103220…] TD=1206583562529435662
I0912 13:01:27.975763 p2p/server.go:313] Starting Server
I0912 13:01:28.791553 p2p/discover/udp.go:217] Listening, enode://93b7e7780a552093f8d03434afebeded58e95cf54699c0db73571742733c187017a8cfcf4639ebac82bd5c08ffc88becb803e87b56a1717b6f0a40de9a11064e@[::]:30303
I0912 13:01:28.807013 p2p/server.go:556] Listening on [::]:30303
I0912 13:01:28.812615 node/node.go:296] IPC endpoint opened: /home/admpool/.ethereum/geth.ipc
I0912 13:01:48.809039 eth/downloader/downloader.go:319] Block synchronisation started

sudo netstat -pan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      2521/redis-server 1
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2591/nginx -g daemo
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2499/sshd
tcp        0      0 192.168.1.122:42644     52.74.57.123:30303      ESTABLISHED 3143/geth
tcp        0      0 192.168.1.122:46330     31.208.74.225:30303     ESTABLISHED 3143/geth
tcp        0      0 192.168.1.122:48480     23.22.38.23:30303       ESTABLISHED 3143/geth
tcp        0      0 192.168.1.122:49582     78.142.19.33:30303      ESTABLISHED 3143/geth
tcp        0      0 192.168.1.122:38026     47.90.10.43:30403       TIME_WAIT   -
tcp        0      0 192.168.1.122:40568     128.199.249.143:30303   FIN_WAIT2   -
tcp        0      1 192.168.1.122:42594     173.27.113.190:30303    SYN_SENT    3143/geth
tcp        0    208 192.168.1.122:22        192.168.1.107:52071     ESTABLISHED 3100/sshd: admpool
tcp        0      0 192.168.1.122:22        192.168.1.107:51727     ESTABLISHED 2950/sshd: admpool
tcp        0    128 192.168.1.122:60384     85.0.78.194:30303       ESTABLISHED 3143/geth
tcp        0      1 192.168.1.122:44140     89.143.92.39:30303      SYN_SENT    3143/geth
tcp        0      0 192.168.1.122:56550     188.167.179.190:30303   FIN_WAIT2   -
tcp        0      1 192.168.1.122:44596     94.251.30.161:30303     SYN_SENT    3143/geth
tcp6       0      0 :::22                   :::*                    LISTEN      2499/sshd
tcp6       0      0 :::30303                :::*                    LISTEN      3143/geth
udp        0      0 0.0.0.0:68              0.0.0.0:*                           2427/dhclient
udp6       0      0 :::30303                :::*                                3143/geth


GETH not listening on port 8545

**Comment by mikeyb** [comment]
Because you still have **NOT ENABLED RPC**

> Make sure you have geth running with rpc **enabled**

```
❯❯❯ geth --help | grep rpc | grep Enable
  --rpc			Enable the HTTP-RPC server
```

8545 is the default port, there is no need to set that...

**Comment by mikeyb** [comment]
Also, for future reference.  To list the ports listening on your system try:
`sudo netstat -pan | grep LIST`

**Comment by chun007** [comment]
Thank you very much.
web frontend issues:
Stats API Temporarily Down
Usually it's just a temporal issue and mining is not affected.

I have something else wrong configured?

**Comment by mikeyb** [comment]
Did you setup nginx?

**Comment by chun007** [comment]
yes, in report netstat -pan
tcp 0 0 0.0.0.0:80 0.0.0.0:* LISTEN 2597/nginx -g daemo

vim /etc/nginx/sites-available/default
upstream api {
        server 127.0.0.1:8080;
}

server {
        listen 0.0.0.0:80;
        root /home/pool/open-ethereum-pool/www/dist;
        index index.html index.htm;

        server_name localhost;

        location /api {
                proxy_pass http://api;
        }

        location / {
                try_files $uri $uri/ /index.html;
        }
![etherium](https://cloud.githubusercontent.com/assets/22134344/18438902/add154fe-791c-11e6-8098-c197845983df.png)

**Comment by mikeyb** [comment]
I would check the nginx logs and see why its failing and work from there.

**Comment by boehla** [comment]
I think it is because the html config /home/pool/open-ethereum-pool/www/config/environment.js
Your config now:
```
...
APP: {
// API host and port
ApiUrl: '//localhost/',
...
```

Try:
```
...
APP: {
// API host and port
ApiUrl: '//192.168.1.122/',
...
```

**Comment by chun007** [comment]
error logs for desert today, although today I rebooted the computer. Log access, past rows

192.168.1.107 - - [12/Sep/2016:17:32:10 +0300] "GET /ember-cli-live-reload.js HTTP/1.1" 304 0 "http://192.168.1.122/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:48.0) Gecko/20100101 Firefox/48.0"
192.168.1.107 - - [12/Sep/2016:17:32:10 +0300] "GET /assets/vendor.css HTTP/1.1" 304 0 "http://192.168.1.122/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:48.0) Gecko/20100101 Firefox/48.0"
192.168.1.107 - - [12/Sep/2016:17:32:10 +0300] "GET /assets/pool.css HTTP/1.1" 304 0 "http://192.168.1.122/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:48.0) Gecko/20100101 Firefox/48.0"
192.168.1.107 - - [12/Sep/2016:17:32:10 +0300] "GET /assets/vendor.js HTTP/1.1" 304 0 "http://192.168.1.122/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:48.0) Gecko/20100101 Firefox/48.0"
192.168.1.107 - - [12/Sep/2016:17:32:10 +0300] "GET /assets/pool.js HTTP/1.1" 304 0 "http://192.168.1.122/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:48.0) Gecko/20100101 Firefox/48.0"
192.168.1.107 - - [12/Sep/2016:17:32:10 +0300] "GET /bg.png HTTP/1.1" 304 0 "http://192.168.1.122/assets/pool.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:48.0) Gecko/20100101 Firefox/48.0"

**Comment by chun007** [comment]
@boehla      corrected environment.js - the problem is not solved

**Comment by mikeyb** [comment]
I would suggest re-reading the entire [README.md](https://github.com/sammy007/open-ethereum-pool/blob/master/README.md) as it works just fine when setup correctly

**Comment by chun007** [comment]
I re-install open-ethereum-pool
/home/pool/open-ethereum-pool/www/
The following commands had to execute with sudo:
sudo npm install -g ember-cli@2.4.3
sudo npm install -g bower
continue instructions for
npm install
bower install
./build.sh

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

watchman need?

If execute npm install -g ember-cli@2.4.3 then error 
npm install -g ember-cli@2.4.3
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ember-cli@2.4.3"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/ember-cli/node_modules/ember-router-generator/node_modules/recast' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admpool/open-ethereum-pool/www/npm-debug.log

Ether-Proxy I not install.

**Comment by chun007** [comment]
Have any thoughts?

**Comment by chun007** [comment]
Have any thoughts?

**Comment by innova-market** [comment]
```
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
```

**Comment by chun007** [comment]
I forgot to write that everything web is working. The problem was in setting www/config/environment.js

**Comment by innova-market** [comment]
Show the correct settings environment.js

**Comment by robyle** [comment]
@chun007  Please,show the correct setting of www/config/environment.js
