### ISSUE TITLE
web interface: Stats API Temporarily Down

### ISSUE THREAD

**Issue by chun007** [sammy007/open-ethereum-pool#77]
System information

Geth version: geth version or commit hash if develop
Version: 1.4.11-stable-fed692f6
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.6

Redis version: redis-server --version
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

OS & Version: Linux/OSX
Ubuntu 16.04
Linux pool 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Commit branch and hash: (`master`, `ba60e1c`)

#### Actual behaviour
web frontend issues:
Stats API Temporarily Down
Usually it's just a temporal issue and mining is not affected.
![etherium](https://cloud.githubusercontent.com/assets/22134344/18588348/83fee260-7c3f-11e6-93d4-7b62f3c214de.png)

#### Backtrace

````
[backtrace]
````

**Comment by mikeyb** [comment]
nginx isnt configured properly

**Comment by chun007** [comment]
vim /etc/nginx/sites-available/default
upstream api {
        server 127.0.0.1:8080;
}

server {
        listen 0.0.0.0:80;
        root /home/pool/open-ethereum-pool/www/dist;
        index index.html index.htm;

        server_name 192.168.1.122;

        location /api {
                proxy_pass http://api;
        }

#       location / {
#               try_files $uri $uri/ /index.html;
#       }
}

vim /etc/nginx/nginx.conf  - conig default

**Comment by chun007** [comment]
I need to correct?

**Comment by LeChuckDE** [comment]
servername should not be an ip-address .... 
how did your www/config/enviroment.js looks ?

**Comment by chun007** [comment]
```
/* jshint node: true */

module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'pool',
    environment: environment,
    baseURL: '/',
    locationType: 'hash',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // API host and port
      ApiUrl: '//192.168.1.122/',

      // HTTP mining endpoint
      HttpHost: 'http://127.0.0.1',
      HttpPort: 8888,

      // Stratum mining endpoint
      StratumHost: '127.0.0.1',
      StratumPort: 8008,

      // Fee and payout details
      PoolFee: '1%',
      PayoutThreshold: '0.5 Ether',

      // For network hashrate (change for your favourite fork)
      BlockTime: 14.4
    }
  };

  if (environment === 'development') {
    /* Override ApiUrl just for development, while you are customizing
      frontend markup and css theme on your workstation.
    */
    ENV.APP.ApiUrl = 'http://localhost:8080/'
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.baseURL = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {

  }

  return ENV;
};
```

**Comment by murendie** [comment]
I'm having the same issue, 

my ngix config:


upstream api {
        server 127.0.0.1:8080;
}

server {
        listen 0.0.0.0:80;
        root /var/www/open-ethereum-pool/www/dist;
        index index.html index.htm;

        server_name etcpool.xyz www.etcpool.xyz;

        location /api {
                proxy_pass http://api;
        }

        location / {
                try_files $uri $uri/ /index.html;
        root /var/www/open-ethereum-pool/www/dist;
        }
             

My Environment Config
  APP: {
      // API host and port
      ApiUrl: '//etcpool.xyz/',

      // HTTP mining endpoint
      HttpHost: 'http://etcpool.xyz',
      HttpPort: 8888,

      // Stratum mining endpoint
      StratumHost: 'etcpool.xyz',
      StratumPort: 8008,

      // Fee and payout details
      PoolFee: '1%',
