### ISSUE TITLE
very stable and low CPU consumtion pool

### ISSUE THREAD

**Issue by trustfarm-dev** [sammy007/open-ethereum-pool#78]
#### System information

Geth version: `geth version` or commit hash if `develop`
1.4.13 , ETH and 1.4.10 ETC 
Redis version: `redis-server --version`
most lately
OS & Version: Linux/OSX
Linux unbunt 14.04
Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour
ETH : etherscan.io
ETC : gastracker.io

#### Actual behaviour
Good!

Very good variance (around 100% convergence) on suitable hash (ETH : over 10GH, ETC: over 3GH)
I can expect 100 % +- 10% then very good. rewards.

#### Steps to reproduce the behaviour
NA

#### Backtrace
NA
````
[backtrace]
````
NA

**Comment by trustfarm-dev** [comment]
just my private pool after use

**Comment by sammy007** [comment]
Please set extradata on ETH node like I ask everyone in wiki.

**Comment by trustfarm-dev** [comment]
I've already extraday on my managing pool. over 8 includes ETC/ETH.
when you first posted.

**Comment by sammy007** [comment]
Only makes sense for ETH.

**Comment by trustfarm-dev** [comment]
I'll follow your workings.

**Comment by trustfarm-dev** [comment]
How you can fast reply ? ^^ , anyway thanks. here's over 2AM.

**Comment by trustfarm-dev** [comment]
In case of private pool , small hash compared with public famous pools.
ETH pool not many use of open-ethereum.
I've made some statistics, over 20GH private pool for ETH is meaningful statistics.
and 4GH for ETC is meaningful statistics.

Anyway, ETHASH algorithm is good for solo mining. there's also uncles rewards.
now, ETH diff is 82TH , viewable hashrates for solo or private minging is I guess at least 10GH.

**Comment by trustfarm-dev** [comment]
In case of ETC, at least 3GH will get enough stats for mining is well.
and rewards is most better than public famous pools. using your pool.

**Comment by trustfarm-dev** [comment]
And I'll give the another key information is 
1. using pool server with real server located in IDC. not using cloud service (it's VM based service).
for performance.
2. not using postfix or anyother unusable service except pool operations.
3. geth latest patch . after 1.4.13 is very stable on DDOS attack. very low cpu consumption compared with 1.4.12 + gas option patch.  [ make geth cpu usage under 20% , per 1 core]
4.  locate pool server in your country or domestic location. fast IDC.
It's brief checking the ping poolserver , tracert (win), traceroute (linux) - little hope and less connection time.  It's easily compared with network hop.  
if miner location spends time to 200ms to pool server. it needs double time to get work and submit work.

It makes rewards difference by long term (over 1weeks) statistics.

5. final closure::
open-ethereum pool is native language codes.
so, make pool server locates in real server.
make locates pool server to domestic region or very little network hop and less network time.
If same node condition then, you can get more rewards compared than long distance public pools.

**Comment by trustfarm-dev** [comment]
on yesterday, one of my customer has very good luck. on my pool with 11GH.
almost double rewards, on ETH. over 1200$ on 83TH. 

Ok. It's just one day's luck. but, very happy.
He's smart miner, switching to ETC on your pool SW.

**Comment by trustfarm-dev** [comment]
I hope you get the your wanting statistics, If you want another data, then contact me.
I'll try to contributes to you.

**Comment by sammy007** [comment]
Since difficulty on ETH is so fucked up and jumps up.down 10%, I have a problems with luck ith 8GH customer. Must be ok in average for 1 month. Also there are several disasters over this month so stats are fucked too.

**Comment by trustfarm-dev** [comment]
Anyway your customer gets enough rewards, compare than public.
in case of public, there's so many fake hash and If Big hash miner has come in and out then, small hashier will get less rewards relatively.
So, I've recommends to 8GH that normal situations, do what he wants.
But, recent days of DDOS, there's several orphan (no rewards, before geth patch), I've recommend to switching ETC mining. that's well rewards, very stable geth load.
except my recommendation, one of my customer has intelligent switching to other pools (it's some public pools) . so he gets' more rewards.

And my experience from monitoring of my customer,

there's some stuck case (over 2~300%) , he changed pool or add more hash (from his own hash or rental hash) overcome the get block. after that, most of case variance will be well.

and our third party , who making mining management SW, gets variance from pool and auto adds or minus hash for overcome deadlock situation.
or switching to ETC or other lucked pool.

I think 8GH pools are not expected to get average viewable results on this shaking diff case (from 60T ~ 80T).

If someone mine ETC , also good profit.
