### ISSUE TITLE
Dear sammy, API documentation or usage examples needs

### ISSUE THREAD

**Issue by trustfarm-dev** [sammy007/open-ethereum-pool#79]
#### System information

Geth version: `geth version` or commit hash if `develop`
1.4.13 (ETH), 1.4.10(ETC) - all is patched Gas option preventing DDOS.

Redis version: `redis-server --version`
latest
OS & Version: Linux/OSX
ubuntu 14.04 base and updates some parts.

Commit branch and hash: (`master`, `ba60e1c`)
lates

#### Expected behaviour
I want to get block's luck or variance by api. 
But, I can't know how to use.

#### Actual behaviour
just shows all statistics.

#### Steps to reproduce the behaviour
/api/blocks/

#### Backtrace

````
[backtrace]
````

-------

open ethereum pools good showing stat information is Luck or Variance statistics.
But , I've almost newbie in go lang, c and c++ is good enough.
So, a little bit confusing to me.

thus, if there's guide to implement or expand pool's api or usage examples, then very helpful.

**Comment by trustfarm-dev** [comment]
I hope to extend add variance.
1. add variance thru api call
2. make unlocking and payout, make whitelist payout address.
thnx

**Comment by sammy007** [comment]
What statistic? Currently there is luck per block and per N (configurable) blocks.

**Comment by sammy007** [comment]
Variance is not a variance actually, I regret I used this term. it's SUM(shares)/blockDiff.

**Comment by sammy007** [comment]
All stats available via API, otherwise how frontend render them?

**Comment by trustfarm-dev** [comment]
ok, thanks for fast reply.

when I call api/blocks their block statistics.

block no,   

blockno	Hash	time	  variance	   reward
2,337,113	0x6d570d324d04c0041f735cb5d1f58957d3286f059b06ecec31037d8e9e4bd88a	2016. 9. 28. 오후 2:27:05	99%	5.000000

I want to get call 99% (variance) .
but, I can't know block's api call.

**Comment by trustfarm-dev** [comment]
I'm using your codes, changing the some term and words.

**Comment by sammy007** [comment]
There is `/api/blocks`.

```
{ "difficulty":X,"shares":Y }
```

Divide shares by diff to get luck.

**Comment by trustfarm-dev** [comment]
ok thanks. I'll try.
