### ISSUE TITLE
POOL not update balance

### ISSUE THREAD

**Issue by waldirsp11** [sammy007/open-ethereum-pool#80]
Geth version: Version: 1.5.0-unstable

Redis version: 3.0.6

OS & Version: Ubuntu 16.04

Commit branch and hash: master

My problem:
I deployed a server, but dont update miner account ... see:
http://ethash.org/#/account/0x13b1094886dc928f479c9a7a13abeca5af34cd3e

I have mined from hours, and stay in 0 my balance ...
Immature Balance: 0.00000000
Pending Balance: 0.00000000

My config.json
...
        "unlocker": {
                "enabled": true,
                "poolFee": 1.0,
                "poolFeeAddress": "0x7618c7675606f9B70A2d87871FD2E10e229E7D93",
                "donate": false,
                "depth": 120,
                "immatureDepth": 20,
                "keepTxFees": false,
                "interval": "10m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s"
        },

        "payouts": {
                "enabled": true,
                "requirePeers": 25,
                "interval": "10m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s",
                "address": "0x7618c7675606f9B70A2d87871FD2E10e229E7D93",
                "gas": "21000",
                "gasPrice": "50000000000",
                "autoGas": true,
                "threshold": 100000000,
                "bgsave": false
        }, 
...

I have tried wi defaul values and set my eth address ... but with out succes ...

Can someone help me?

Thank you!

**Comment by sammy007** [comment]
Maybe because you need to find some blocks first?
