### ISSUE TITLE
Why is not paid if the minimum is 0.1 eth in config.json?

### ISSUE THREAD

**Issue by waldirsp11** [sammy007/open-ethereum-pool#81]
Geth version: 1.5.0-unstable

Redis version: 3.0.6

OS & Version: ubuntu server 16.04

Commit branch and hash: master

Why i not paid if i setup config.json to pay every 0.1 eth as say in: https://github.com/sammy007/open-ethereum-pool

    // Send payment only if miner's balance is >= 0.5 Ether
    "threshold": xxxxx,

Look my conf:    http://51.254.101.234/config.json

How i can see how much I mined? I think need this because i want open a public pool but if not have this ... i think is impossible do this ...

nobody can help me?

thank you!

**Comment by sammy007** [comment]
I believe if you have such kind of problems you should not go public with it. Please consider mining on one of existing pools. All info is clear and documentation is fine. There is an entry barrier in this kind of systems. Ask for help on gitter, issue tracker is not for education.

**Comment by waldirsp11** [comment]
hey man ... i can pay for you ... please help finish my pool ... add skype:   waldir.pedroso

**Comment by waldirsp11** [comment]
i only have some question to finish ... email: wap113hot@hotmail.com / skype: waldir.pedroso

**Comment by sammy007** [comment]
I am not available for hire especially if it leads to nothing. Ask for help in gitter channel (badge with link in README). If you have question how to finish you will have question how to run/fix.
