### ISSUE TITLE
ETH Job timeout

### ISSUE THREAD

**Issue by chun007** [sammy007/open-ethereum-pool#82]
#### System information

Geth version: geth version or commit hash if develop
Version: 1.4.11-stable-fed692f6
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.6

Redis version: redis-server --version
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

OS & Version: Linux/OSX
Ubuntu 16.04
Linux pool 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Commit branch and hash: (`master`, `ba60e1c`)
#### Actual behaviour

Anonimous miner look not work (job timeout)
![111](https://cloud.githubusercontent.com/assets/22134344/19036290/955cd20c-8977-11e6-98a4-eaf12110d1b0.png)

command node miner:
EthDcrMiner64.exe -epool ip_1:8888 -ewal 0xxxxxxxxxxxxxxx -eworker xxx -epsw x -dpool stratum+tcp://lbry.suprnova.cc:6256 -dwal Insert.xxx -dpsw xxx -dcoin lbc -dcri xx -dbg 0 -r -1 -mport xx -mode 0 -tstop 90 -ethi xx -tt -xx

ip_1 - local ip address (192.168._._)
Ip address web interface etherium-pool public (81._._.*)
#### Backtrace

```
[backtrace]
```

**Comment by chun007** [comment]
Even when I run local geth --rpc  --mine 
Miner in web interface are not displayed.
![miner](https://cloud.githubusercontent.com/assets/22134344/19038165/f08f82ea-8982-11e6-8ee3-0d79e7db11fb.png)

**Comment by trustfarm-dev** [comment]
change port from 8888 to 8008

**Comment by chun007** [comment]
result connect on 8008:
![img-20161005-wa0000](https://cloud.githubusercontent.com/assets/22134344/19116455/450466dc-8b1e-11e6-9df8-5e24f0aced1f.jpg)

**Comment by LeChuckDE** [comment]
@chun007 use a good miner like genoils ethminer .... works like a charm

pls post the config for stratum part from your config

**Comment by chun007** [comment]
environment.js     
 // HTTP mining endpoint
      HttpHost: 'http://192.168.20.250',
      HttpPort: 8888,

      // Stratum mining endpoint
      StratumHost: '127.0.0.1',
      StratumPort: 8008,

config.json
  "stratum": {
                        "enabled": true,
                        "listen": "0.0.0.0:8008",
                        "timeout": "120s",
                        "maxConn": 8192
                },

**Comment by LeChuckDE** [comment]
try this flag at this shity miner -allpools 1 -allcoins 1

**Comment by LeChuckDE** [comment]
ah see the message says work not ready ... this means your poolwallet isn't fully synced or crashed due journal attack at eth and etc network

**Comment by chun007** [comment]
> try this flag at this shity miner -allpools 1 -allcoins 1
no work

**Comment by chun007** [comment]
> ah see the message says work not ready ... this means your poolwallet isn't fully synced or crashed due journal attack at eth and etc network

what should be done?

**Comment by LeChuckDE** [comment]
> what should be done?

read ethereum whitepaper 1st...

**Comment by chun007** [comment]
More details can be?
