### ISSUE TITLE
Payment error ...

### ISSUE THREAD

**Issue by waldirsp11** [sammy007/open-ethereum-pool#83]
#### System information

Geth version: 1.5.0-unstable

Redis version:  Redis server v=3.0.6

OS & Version: Ubuntu 16.04

Commit branch and hash: master

Hi,
I am getting error to process payments, look:

> ./open-ethereum-pool payout.json
2016/10/03 15:24:08 Loading config: /home/open-ethereum-pool/payout.json
2016/10/03 15:24:08 Running with 2 threads
2016/10/03 15:24:08 Backend check reply: PONG
2016/10/03 15:24:08 Starting block unlocker
2016/10/03 15:24:08 Set block unlock interval to 10m0s
2016/10/03 15:24:08 Starting payouts
2016/10/03 15:24:08 Set payouts interval to 10m0s
2016/10/03 15:24:08 No payees that have reached payout threshold
2016/10/03 15:24:09 Error while retrieving block -15 from node: invalid blocknumber "0x-f"
2016/10/03 15:24:09 Failed to unlock blocks: invalid blocknumber "0x-f"
2016/10/03 15:24:09 Unlocking suspended due to last critical error: invalid blocknumber "0x-f"

My payout.json

{
        "threads": 2,
        "coin": "eth",
        "name": "main",

        "proxy": {
                "enabled": false,
                "listen": "0.0.0.0:8888",
                "limitHeadersSize": 1024,
                "limitBodySize": 256,
                "behindReverseProxy": false,
                "blockRefreshInterval": "120ms",
                "stateUpdateInterval": "3s",
                "difficulty": 2000000000,
                "hashrateExpiration": "3h",

                "healthCheck": true,
                "maxFails": 100,

                "stratum": {
                        "enabled": false,
                        "listen": "0.0.0.0:8008",
                        "timeout": "120s",
                        "maxConn": 8192
                },

                "policy": {
                        "workers": 8,
                        "resetInterval": "60m",
                        "refreshInterval": "1m",

                        "banning": {
                                "enabled": false,
                                "ipset": "blacklist",
                                "timeout": 1800,
                                "invalidPercent": 30,
                                "checkThreshold": 30,
                                "malformedLimit": 5
                        },
                        "limits": {
                                "enabled": false,
                                "limit": 30,
                                "grace": "5m",
                                "limitJump": 10
                        }
                }
        },

        "api": {
                "enabled": false,
                "purgeOnly": false,
                "purgeInterval": "10m",
                "listen": "0.0.0.0:8080",
                "statsCollectInterval": "5s",
                "hashrateWindow": "30m",
                "hashrateLargeWindow": "3h",
                "luckWindow": [64, 128, 256],
                "payments": 30,
                "blocks": 50
        },

        "upstreamCheckInterval": "5s",
        "upstream": [
                {
                        "name": "main",
                        "url": "http://127.0.0.1:8545",
                        "timeout": "10s"
                },
                {
                        "name": "backup",
                        "url": "http://127.0.0.2:8545",
                        "timeout": "10s"
                }
        ],

        "redis": {
                "endpoint": "127.0.0.1:6379",
                "poolSize": 10,
                "database": 0,
                "password": ""
        },

        "unlocker": {
                "enabled": true,
                "poolFee": 1.0,
                "poolFeeAddress": "0x58529b4f05191ceccc109925752b15b9b93d6d31",
                "donate": false,
                "depth": 120,
                "immatureDepth": 20,
                "keepTxFees": false,
                "interval": "10m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s"
        },

        "payouts": {
                "enabled": true,
                "requirePeers": 25,
                "interval": "10m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s",
                "address": "0x58529b4f05191ceccc109925752b15b9b93d6d31",
                "gas": "21000",
                "gasPrice": "50000000000",
                "autoGas": true,
                "threshold": 100000000,
                "bgsave": false
        },

        "newrelicEnabled": false,
        "newrelicName": "MyEtherProxy",
        "newrelicKey": "SECRET_KEY",
        "newrelicVerbose": false
}

How i can fix this? Thank you!

**Comment by trustfarm-dev** [comment]
No payees that have reached payout threshold

reciever doesn't over 1ether.
codition is reached then, retry.

**Comment by sammy007** [comment]
Yes either wait for 1 ETH on balance on any miner or reduce threshold (remove single zero to make it 0.1).

**Comment by mnfikrifx** [comment]
Failed to unlock blocks: invalid blocknumber "0x-f" and block never matured ... can anyone help ? googled and not found solution
