### ISSUE TITLE
Node switching automatically btw   geth  and parity

### ISSUE THREAD

**Issue by trustfarm-dev** [sammy007/open-ethereum-pool#84]
Request switching mining nodes btw geth and parity.

Now I'm installed parity and syncing now.
geth --rpcport 18545 --port 30303
parity --rpcport 18540  --port 30300

I want to change backend node , when some nodes has problems. 

Now, from this morning (10hours ago) geth can't mining now. 
stuck on block height 2376xxx . latest block heights are 2378529 (from etherscan.io)

#### System information

Geth version: `geth version` or commit hash if `develop`
geth 1.4.15~  and Parity 1.3.2~

OS & Version: Linux/OSX

Ubuntu 14.04 or any platforms (iOS/Windows)

Commit branch and hash: (`master`, `ba60e1c`)

#### Expected behaviour

Expected no error on block height increasing.
On this time parity nodes has run. theother days, geth has run well, but parity was not.

#### Actual behaviour

Latest geth has still problem on DDOS Contract attack.
So, this geth nodes has hanged on blockno 2376xxx

https://github.com/ethereum/go-ethereum/issues/3083
https://www.reddit.com/r/ethereum/comments/55rd3j/attacker_is_gearing_up_again_for_new_spam_deluge/ 
https://www.reddit.com/r/ethereum/comments/55s085/geth_nodes_under_attack_again_we_are_actively/

#### Steps to reproduce the behaviour
Just run

#### Backtrace

````
[backtrace]
````

**Comment by mikeyb** [comment]
So your problem is geth is getting hung on the bad contract block?  This doesn't sound like an open-ethereum-pool issue.  Verify your geth is current as it should get around this block just fine with latest client.

**Comment by trustfarm-dev** [comment]
Hi @mikeyb  , you may be read above reddit and github release issues first.

**Comment by mikeyb** [comment]
Ahh I see what you are saying.  You want open-ethereum-pool to switch between wallet clients.

I think creating code to do auto-switching is a waste of time.  I would suggest support for both clients and let the pool owner choose via config.  

Auto-switching would require having both clients installed which seems a bit excess to me.

Not sure if sammy007 has plans to implement parity support, but I have a feeling this Issue is a non issue.  You might consider creating a pull request instead with the code you want to see changed to add parity support.

**Comment by trustfarm-dev** [comment]
@sammy007  please your comments.
thnx

**Comment by trustfarm-dev** [comment]
@sammy007  It may be helpful to use main/backup channel configurations.
in config.json

  "upstream": [
    {
      "name": "main",
      "url": "http://127.0.0.1:18545",   <--- geth
      "timeout": "10s"
    },
    {
      "name": "backup",
      "url": "http://127.0.0.2:18540",    <-- parity
      "timeout": "10s"
    }
  ],

or vice versa.

close this issue.
