### ISSUE TITLE
Parity 1.3.3 works too !

### ISSUE THREAD

**Issue by LeChuckDE** [sammy007/open-ethereum-pool#86]
Not an Issue,

tested parity 1.3.3 now for round about 24 hrs, 30 Blocks, 3 Uncles found, all things working fine !
Tested at Ethereum Classic.
Use parity 1.3.3 for Ethereum and Ethereum Classic.

**Comment by Eliovp** [comment]
I can confirm this, same goes for 1.3.4

**Comment by sammy007** [comment]
Yes must work, I screwed my startup script and forgot to add `--jsonrpc-hosts all`.
