### ISSUE TITLE
Join function in redis.go reduces float64 to precision of zero

### ISSUE THREAD

**Issue by MemeticParadigm** [sammy007/open-ethereum-pool#88]
Not sure if issues is the right place for this, but I noticed that, in the "join" function of the redis.go file, the float64 case uses a precision of 0 when it calls the strconv.FormatFloat function - if this value is changed to -1 (smallest number of digits necessary such that ParseFloat will return f exactly), is this liable to subtly break anything? If not, is there a particular reason a precision of 0 was used?

**Comment by sammy007** [comment]
Can you point to specific line of code or prolly create a failing test case for that?

**Comment by sammy007** [comment]
Or just gimme an example of code.

**Comment by sammy007** [comment]
Also if you think this applies as security issue, do it via PM.

**Comment by sammy007** [comment]
Redis backed of this pool does not store any floating points so it's ok, `join` used only to prepare data for insertion into redis.
