### ISSUE TITLE
Payments suspended due to last critical error

### ISSUE THREAD

**Issue by taczc64** [sammy007/open-ethereum-pool#89]
#### System information

Geth version: `parity v1.3.8`

OS & Version: Linux ubuntu 16

#### Expected behaviour
i  connect my own computer to the pool for mining, very lucky, i got  a block yesterday, and pool get 5.000 reward. it expected to pay all of the reward to the only miner(the pool only connect to my own computer)
and i set payout config like this:
"payouts": {
                "enabled": true,
                "requirePeers": 1,
                "interval": "2m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s",
                "address": "0x33a5a5d058df1397946ceb178abc25ea8d72fea3",
                "gas": "21000",
                "gasPrice": "50000000000",
                "autoGas": true,
                "threshold": 500000000,
                "bgsave": false
        },
#### Actual behaviour
but in fact, it cannot pay the reward to my only  miner, and here is the log about payout:
Payments suspended due to last critical error: Insufficient funds. Account you try to send transaction from does not have enough funds. Required 5018800000000000000 and got: 5000000000000000000.
why the real payment to my miner address is more than five ether?

**Comment by sammy007** [comment]
If fee is zero you have no funds for tx fee.
