### ISSUE TITLE
Parity Question

### ISSUE THREAD

**Issue by godeagle** [sammy007/open-ethereum-pool#90]
This is not issue it's only a  question and a new test that i'm trying to do, just trying to use parity instead geth, i use the command "parity --pruning fast --no-dapps --no-signer --unlock "MY WALLET ADRESS" --jsonrpc-hosts all --password ~/pass.txt"  but when i try to run the pool give's me this message "Error while refreshing block template on main: Still syncing." pool is working, i did not test yet start mining to the pool, first test, test and test... :)
 This message that i have when trying to start pool is normal? 

Thanks
Kind  Regards
Nuno Borges

**Comment by sammy007** [comment]
Because **Still syncing**.

**Comment by godeagle** [comment]
So It's Normal :) just for checking that i'm doing the right thing, Thanks @sammy007
