### ISSUE TITLE
Question about Parity command

### ISSUE THREAD

**Issue by godeagle** [sammy007/open-ethereum-pool#91]
Hi there i don't think that i need to put all information :) but i'm configured everything and before that i had my blockchain syncronized i be able to run the pool, with parity previously: 
"parity --pruning fast --no-dapps --no-signer --unlock "0xMyPayouadress" --jsonrpc-hosts all --password ~/pass.txt"
Now i have my blockchain syncronized i started to get this message "parity --pruning fast --no-dapps --no-signer --unlock --author "0xMyPayouadress" --jsonrpc-hosts all --password ~/pass.txt"

"Error while refreshing block template on main: Author not configured. Run Parity with --author to configure."

i allready had tryed to putt --author before my adress like but still the same error...am i missing something?

Kind regards
Nuno Borges

**Comment by sammy007** [comment]
`--author "0xWHERE-BLOCKS-WILL-RAIN"` and `--unlock "0xWHERE-I-HAVE-FUNDS-FOR-PAYOUTS"` both equal usually. Also add `--geth` option.
