### ISSUE TITLE
Balance still at Zero?

### ISSUE THREAD

**Issue by godeagle** [sammy007/open-ethereum-pool#92]
#### System information

Parity Version 1.3.9-beta

Redis version:  3.2.5

OS & Version: Linux/OSX

Ubuntu 16.04

#### Expected behaviour
 
Show Pending Balance 

#### Actual behaviour

Still 0
#### Steps to reproduce the behaviour
A question to be shure of anything

Hello there, i configure all my pool and everything is working as expected, now i have a question that..

For testing i put like 500MH on this pool, with only a worker, i allready am mining like for a couple of hours and on my balance stays "'0"  if i making shares and send them to the pool should i see some balance?
Or do i only get some balance after find a block? if so... this is like solo mining.... in my thoughts i think i should get some value rigth??

Sorry for another question Sammy :) 

Kind Regards
NB

**Comment by sammy007** [comment]
Learn what solo mining is.

**Comment by godeagle** [comment]
But this is not solo mining is a pool right? now i confused!! :S

**Comment by mikeyb** [comment]
Solo mining is when you solo mine...If you are the only one mining, you are solo mining.  Solo means "something that is done without another person".  So if you are solo mining in a pool, you are still solo mining.  You only get rewards when you mine something.  Make sense?

The pool doesnt create tokens out of thin air, you have to mine them.  Then the pool rewards you based on your contribution.  If you are solo mining a pool, you get 100% of the reward, when you find a block.

You do not need a pool to solo mine.

**Comment by godeagle** [comment]
thanks @mikeyb i get it, and make sense of course :) i thought that in the pool i could see the shares and the balance, thanks you this confirmation

Apreciate :)

Kind Regards
Nuno Borges

**Comment by godeagle** [comment]
what can i do is, since i have 3 rigs, for each rig create a ETH adress and mine for these adresses, for the pool theres 3 people mining for the pool and should appear balance right ? heheheh :)

I Just want to see some balance there, only for my understanding :)

Kind Regards

**Comment by mikeyb** [comment]
No.  Absolutely not.  There should be NO BALANCE UNTIL YOUR POOL MINES A BLOCK.  You could have 10,000,000 mining rigs, but until you actual mine something there is no balance.  You should however see shares being submitted for the mining round.  Those shares will turn into a balance when the pool mines a block.

Just like real mining in the ground.  You get nothing until you find something.  Just because you and 1,000 of your friends are digging in the dirt, doesn't mean you get gold payments.  You have to find the gold first...

**Comment by mikeyb** [comment]
What is your pool website?  I can take a look and see if everything looks normal statistically.

**Comment by sammy007** [comment]
Pool can't generate coins itself out of thin air, someone must find a block on it.

**Comment by godeagle** [comment]
hmm ok  i've got shares being submitted in the pool, i allready had check that in the api
"{"candidatesTotal":0,"hashrate":366666666,"immatureTotal":0,"maturedTotal":0,"minersTotal":3,"nodes":[{"difficulty":"57129983463891","height":"2565055","lastBeat":"1478266986","name":"main"}],"now":1478266987247,"stats":{"roundShares":8450000000000}}"

@mikeyb 
Thanks for your replay's and help let's wait for the block :)

**Comment by godeagle** [comment]
@mikeyb  http://nunoborges.myddns.me/

my pool website, i'm testing things

**Comment by mikeyb** [comment]
Yeah everything looks fine to me there.  Just wait for a block and you will see earnings

**Comment by godeagle** [comment]
thanks one more time for support @mikeyb
