### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by basicsk8r13** [sammy007/open-ethereum-pool#93]
I need to get ahold of the author sammy007 in regards to the zcash mining proxy.

What's your email?

**Comment by sammy007** [comment]
I am available in [zcash community slack](https://zcashcommunity.slack.com) and on [gitter](https://gitter.im/sammy007/open-ethereum-pool?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
