### ISSUE TITLE
Do i've got a Block?

### ISSUE THREAD

**Issue by godeagle** [sammy007/open-ethereum-pool#94]
Hi there if got this mensage in my log's pool in my pool don't show me any information telling me that this miner found a block.

"No block candidates to unlock
No immature blocks to credit miners"
and i have  "Current Round Variance: 105% "
at the moment i do not have any miners first trying to figure this out, 

But since i've got this mensage it means that i found a block? sorry about this question... i'm starting to learn pool things.

Can anyone explain me this... previously i've got payouts and unlocker enable in config.json, now i create a new file for both of them and restarted pool with this disable.

One thing is when i try to run the unlocker give's me the a mensage  telling me that i do no have permission to run unlocker? not eaven with sudo command
"bash: ./unlocker.json: Permission denied"

am i doing something wrong? 
Sorry for all this questions :)

Kind Regards
Nuno Borges

**Comment by sammy007** [comment]
Block explorer like https://etherscan.io is an awesome tool to check if you mined block.

```
"bash: ./unlocker.json: Permission denied"
```

You are trying to run a text file, of course it's impossible.

Due to lack of basic skills please consider public pool for mining instead https://github.com/sammy007/open-ethereum-pool/wiki/List-Of-Open-Pools.

**Comment by godeagle** [comment]
Hi Sammy as i sair i am learning how to bulid a pool and Making some tests, if we want something we need to study and of course we have questions.
I thougth that no need to Out this file as executable because config.json is not executable, but with this comment you have me one ideia run this file...  Out this files in the same Göldert as config.json and try to runnit.
Sorry for all this questions,  but we have to start with something, not pretending to to on-line if i have questions and do not know how to solve ir right :)
