### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by dailydose1** [sammy007/open-ethereum-pool#97]
cant get this to install properly.

seems like a problem when i get to ember-cli part of the install? Is there a more detailed installation guide? Or can i pay $50 for someone to install this on my server haha

**Comment by defaler** [comment]
I can install it for you on your server :)

**Comment by dailydose1** [comment]
ok sounds good, do you want me log in info and whatnot?


    On Saturday, December 24, 2016 6:19 AM, defaler <notifications@github.com> wrote:
 

 I can install it for you on your server :)—

**Comment by defaler** [comment]
Ok, i need log in info and install path. Wrire me at antikrutomer (at) gmail.com
