### ISSUE TITLE
How to buil a pool to ETC and ETH 

### ISSUE THREAD

**Issue by margotpaon** [sammy007/open-ethereum-pool#99]
Hi Sammy, thank you very much for carrying out this project! I would like to know how can I create a pool for the ETC? Need to change some configuration in particular or when we compile and configure the source is ready for both ETH and ETC to same URL? Thank you for your attention again.

**Comment by mikeyb** [comment]
Have a look at https://github.com/LeChuckDE/open-ethereumclassic-pool

**Comment by margotpaon** [comment]
@mikeyb thanks a lot fot this! I didn't know about another project(Fork) to ETC!

**Comment by sammy007** [comment]
There is no difference between eth and etc. Use parity with classic mode and run it like regular eth pool.

**Comment by sony87** [comment]
It's worth mentioning that in the LeChuckDE's ETC pool the 10% donation is hard-coded and parameter to disable it is deleted. Not an issue since all the code is visible and can be edited but it's correct such changes to be reported publicly.

**Comment by vts86** [comment]
Hi Sammy, could you please tell me about this error "Error while refreshing block template on main: no mining work available yet", I can't find explanation of this error nowhere, I will be very appreciate if you can help me
Thank you in advance!

**Comment by EWIT521** [comment]
no synced
